### ISSUE TITLE
每次插入引用内容后无法显示光标，就不能输入其他东西了

### ISSUE THREAD

**Issue by wulucxy** [margox/braft-editor#1]
chrome浏览器每次插入引用内容后无法显示光标，就不能输入其他东西了 @margox

**Comment by margox** [comment]
你是用的什么浏览器？

**Comment by margox** [comment]
点击插入引用内容或者代码块之类的，编辑区域会失去焦点的，试试再点击一下编辑区域？不过感觉这个地方，可以改造一下，自动再让编辑器区域重新获得一下焦点，下版本试试看

**Comment by margox** [comment]
现在插入代码块等内容之后，会重新让编辑器获得焦点
