### ISSUE TITLE
怎么判断是否包含可见内容？

### ISSUE THREAD

**Issue by wangzhipeng404** [margox/braft-editor#101]
当我删除全部内容时，最后会打印出一个空的段落标签<p></p>，有没有判断编辑器内容是否为空的方法，就像kindeditor的isEmpty()那样的

**Comment by margox** [comment]
额，暂时没有直接的办法，下一版本我加上这个方法吧

**Comment by margox** [comment]
新增了isEmpty() 方法，不过这个方法的本质还是判断编辑器的内容是否为一对空的p标签。

**Comment by wangzhipeng404** [comment]
我去看了一下kindeditord的源码，把它的isEmpty()拿了出来,大概就是下面这样
`
function trimString(str) {
  return str.replace(/(?:^[ \t\n\r]+)|(?:[ \t\n\r]+$)/g, '');
}
function htmlText(html) {
  return trimString(html.replace(/<(?!img|embed).*?>/ig, '').replace(/&nbsp;/ig, ' '));
}
function htmlIsEmpty(html) {
  return trimString(htmlText(html).replace(/\r\n|\n|\r/, '')) === '';
}
`

**Comment by margox** [comment]
他这个是把所有的空行都过滤掉了吧？ 如果你的需求也是这样的话，你可以自己先获取一下HTML然后按照这样的逻辑来判断一下，如果去除掉所有的空行和空格之后，只剩下<p></p>的话，就认为是empty了
