### ISSUE TITLE
下划线和删除线不能正确显示

### ISSUE THREAD

**Issue by heiyanshooter** [margox/braft-editor#104]
我对一串字符添加下划线和删除线时，编辑器没有显示出效果，但是样式确实是添加了

![image](https://user-images.githubusercontent.com/22254129/37697056-90d27d8e-2d15-11e8-8fb5-3f3e50762dad.png)
![image](https://user-images.githubusercontent.com/22254129/37697064-9a2b9aaa-2d15-11e8-9969-52a8aa550c7e.png)

而且我把获得的html添加到同一个页面预览，也可正常显示，说明全局样式应该没有影响
![image](https://user-images.githubusercontent.com/22254129/37697115-e5ead898-2d15-11e8-97f2-bfa5c6f3281b.png)

**Comment by margox** [comment]
http://margox.github.io/braft-editor/ 我在这个demo里面看是有效果的，你试试通过开发者工具右边的Styles标签页看看当前是哪个样式在生效。

**Comment by heiyanshooter** [comment]
已解决，项目的问题，有个全局样式把span设置成inline-block了
