### ISSUE TITLE
调用getHTMLContent报错

### ISSUE THREAD

**Issue by GoFighting** [margox/braft-editor#105]
![image](https://user-images.githubusercontent.com/13616686/37706691-5a1062a4-2d3b-11e8-941e-a3c3b44f033c.png)

**Comment by margox** [comment]
contentFormat属性设置为'html'试试

**Comment by margox** [comment]
@GoFighting 是采用了最新版的draft-js么？ 昨天晚上另外一个用户发现使用draft-js v0.10.4会有这个问题，降到v0.10.3之后就行了
