### ISSUE TITLE
图片设置工具弹窗问题

### ISSUE THREAD

**Issue by Imhemers** [margox/braft-editor#106]
首先感谢楼主提供这么棒的 编辑器 
我调试过至少4个这种用于react编辑器，
楼主这个算目前最适用且漂亮清新的,  

刚调试demo  发现个不算太大问题, 看楼主好不好解决

就是当图片插入之后设置尺寸变小之后   , 工具弹窗被遮盖

![image](https://user-images.githubusercontent.com/18650947/37748533-24b17d94-2dbf-11e8-9850-6a48afaf8609.png)

**Comment by margox** [comment]
这个工具栏的定位默认是参照body来的，你设置一下编辑器的viewWrapper属性就行了：
```jsx
<div className="editor-wrapper">
  <BraftEditor viewWrapper=".editor-wrapper"/>
</div>
```
https://github.com/margox/braft-editor#viewwrapper-string
