### ISSUE TITLE
Can't resolve 'react-dom/server'   ./node_modules/draft-convert/lib/util/getElementHTML.js

### ISSUE THREAD

**Issue by Nokecy** [margox/braft-editor#107]
React v16.2.0

**Comment by margox** [comment]
react-dom安装了么？ 是什么版本

**Comment by Nokecy** [comment]
react-dom v16.2.0

**Comment by margox** [comment]
看下node_modules/react-dom/下面有没有server.js，若有的话，你得看看是不是webpack什么地方有问题导致没有正确地import这个模块

**Comment by jsonboo** [comment]
./node_modules/draft-convert/lib/convertToHTML.js
Module not found: Error: Can't resolve 'react-dom/server' in 'D:\work\code\cms-manage-portal\node_modules\draft-convert\lib'

**Comment by talktohebe** [comment]
遇到了同样的问题，看到了这个解决办法，https://github.com/RubyLouvre/anu/issues/640

**Comment by talktohebe** [comment]
遇到了一样的问题，打包的时候一直报错，Can't resolve 'react-dom/server' ./node_modules/draft-convert/lib/util/getElementHTML.js，在别的地方看到了两个方法，第一个是删除alias中的配置[url](https://github.com/zeit/next.js/issues/3711)，另一个是添加一个'react-dom/server'的别名配置，第一个不是好方法，第二个不起作用，抓狂

**Comment by SmileLxy** [comment]
> 'react-dom/server': resolve('node_modules/react-dom/umd/react-dom-server.browser.production.min.js'),
> 'react-dom': resolve('node_modules/react-dom/umd/react-dom.production.min.js'),

按照你的第二个方法做了还是不行，会是什么别的原因嘛
