### ISSUE TITLE
如何自定义一个mediaType

### ISSUE THREAD

**Issue by SpencerZ** [margox/braft-editor#109]
如何自定义一个mediaType，并且能够自定义在editor中显示的样式？

**Comment by margox** [comment]
这你得fork项目再二次开发了

**Comment by SpencerZ** [comment]
那你知道我应该是用到draft.js哪些方法吗？

**Comment by margox** [comment]
media type 是我这个项目里面的概念，对应到draft里面，就是一个atomic block类型。
要实现另外的mediaType的话，你需要在3个地方下手：
1. 插入操作，你可以看看编辑器的[insertMedias](https://github.com/margox/braft-editor/blob/master/src/controller/index.js#L231)方法,目前每一个插入的媒体项目可以包含{ url, name, type, meta }这几个属性，其中type其实可以是任意值。如果这几个属性能满足你的需求，那么此处就不需要再做改动了。
2. atomic block在编辑器内部的展示处理，以最简单的video为例，可以参考[src/renderers/atomic/Video/index.jsx](https://github.com/margox/braft-editor/blob/master/src/renderers/atomic/Video/index.jsx) ，这个文件里面定义了atomic block如何在编辑器内部展示。你需要自己在src/renderers/atomic目录下面新建你自己的media type文件并编写对应的组件，然后在src/renderers/index.js里引入并做相应的改动。
3. atomic block如何与HTML相互转换，这里你需要参考[src/configs/convert.js](https://github.com/margox/braft-editor/blob/master/src/configs/convert.js),里面的convertAtomicBlock函数定义了如果把一个atomic block转换为HTML, htmlToBlock函数则定义了如果将HTML里面的媒体标签转换为atomic block。

**Comment by SpencerZ** [comment]
非常感谢

**Comment by SpencerZ** [comment]
那我如果修改你的源代码，要再次在我的项目里面使用，是不是要重新打包成一个新的npm包？

**Comment by margox** [comment]
可以自己发一个npm包，也可以直接引用未打包的项目，反正最终也是要打包的

**Comment by SpencerZ** [comment]
行，那我之后有问题还可以来问你吗🙏

**Comment by margox** [comment]
可以的 加QQ群 725634541 吧，交流方便一些

**Comment by SpencerZ** [comment]
好的
