### ISSUE TITLE
视频功能

### ISSUE THREAD

**Issue by TigEg** [margox/braft-editor#11]
你好，能否增加视频上传功能， 像上传图片一样？ 这样更加完美！！！

**Comment by TigEg** [comment]
@margox

**Comment by margox** [comment]
你好，视频和音频文件现在都是支持的，
- 1 需要在属性里面开启插入音视频功能即可，参考[编辑器的多媒体配置](https://github.com/margox/braft-editor#media-object)
- 2 指定上传函数，参考[uploadFn](https://github.com/margox/braft-editor#mediauploadfn-function)
- 3 上传多媒体文件需要提供服务端支持，你可能需要自己写一个服务端上传接口，参考[简单上传接口示例](https://github.com/margox/braft-editor/blob/master/example/server/index.js)
-----
另外 视频只支持mp4格式，音频只支持mp3格式

**Comment by margox** [comment]
完整的实例，可以看看 [Braft Example](https://github.com/margox/braft-editor/blob/master/example/index.jsx)

**Comment by TigEg** [comment]
@margox 问题解决了，非常感谢，项目很棒！

**Comment by margox** [comment]
@TigEg 感谢支持

**Comment by lavender21** [comment]
你好， 简单上传接口的示例打开404了，可以更新一下地址吗？
