### ISSUE TITLE
ctrl+x 剪切后会跳到顶部

### ISSUE THREAD

**Issue by SadCreeper** [margox/braft-editor#112]
编辑器中内容比较长时，出现滚动后，在中部或底部等地方按 ctrl+x 剪切后滚动条会跳到最顶部

**Comment by margox** [comment]
http://margox.github.io/braft-editor/ 我在这个demo里面试了一下，貌似没这个问题额

**Comment by YikuanLu** [comment]
我也碰到同样的问题，求解

**Comment by CRONWMMM** [comment]
这个问题在代码块的样式里就能复现
