### ISSUE TITLE
点击清除内容报Uncaught Error: Unknown DraftEntity key: null

### ISSUE THREAD

**Issue by socketjs** [margox/braft-editor#114]
很多人也遇到相同问题[https://github.com/jpuri/react-draft-wysiwyg/issues/609](https://github.com/jpuri/react-draft-wysiwyg/issues/609) 看起来好像是draftjs的问题，这边因为项目很紧急，先去掉了clear按钮，重新自定义了一个clear按钮来解决了

**Comment by margox** [comment]
貌似draft-js v0.10.4会有一些问题

**Comment by margox** [comment]
升级到1.8.9试试？
