### ISSUE TITLE
图片问题

### ISSUE THREAD

**Issue by zhangyx007** [margox/braft-editor#116]
富文本编辑器插入图片会报Uncaught TypeError: Cannot set property 'getCurrentStack' of undefined错误，请问是什么原因呀

**Comment by margox** [comment]
你看一下是不是使用了webpack dll之类的构建优化策略，导致项目用到的react是已经被压缩的版本（production版本）。因为这个项目中用到了react-dom/server这个模块，在开发环境需要依赖开发版本的react才有的一些功能，出现这种情况是开发版本的react-dom/server与生产版本的react不兼容导致的，将react-dom/server也加入到现有的构建优化策略里面去就行了
