### ISSUE TITLE
braft-editor空格不能显示

### ISSUE THREAD

**Issue by gaoyajuan** [margox/braft-editor#118]
braft-editor富文本框输入空格，去掉标签回显内容时空格没了

**Comment by margox** [comment]
“去掉标签回显内容”是指过滤掉html标签只取text内容？ 编辑器暂时没有对空格做特殊处理，所以在编辑器内连续输入的空格在展示页面只会显示成1个空格，但是可以使用css `white-space:pre-wrap;`来让连续空格正常显示，如果你取到的text也是包含了多个连续的空格但是显示的时候只有1个空格，也可以试试这个方法

**Comment by gaoyajuan** [comment]
非常感谢！解决了，，谢谢！


顺祝商祺！
高亚娟

技术中心 |山东鼎信网络科技有限公司
E-mail：gaoyj@decent.cn
地址：山东省烟台市莱山区飞龙天润大厦14层

********保密通知********

    在这封电子邮件中包含的信息可能是机密。此邮件旨在审查并用于和山东鼎信网络科技有限公司有明确关系的个人或组织。如果您不是收件人或收件人的授权代表，特此通知您，禁止进行任何传播或复印本电子邮件相关内容的行为。如果您错误地收到了这封电子邮件请立即返回电子邮件来通知发件人，并从您的系统中删除此电子邮件。
 
发件人： 超能刚哥
发送时间： 2018-04-12 08:36
收件人： margox/braft-editor
抄送： gaoyajuan; Author
主题： Re: [margox/braft-editor] braft-editor空格不能显示 (#118)
“去掉标签回显内容”是指过滤掉html标签只取text内容？ 编辑器暂时没有对空格做特殊处理，所以在编辑器内连续输入的空格在展示页面只会显示成1个空格，但是可以使用css white-space:pre-wrap;来让连续空格正常显示，如果你取到的text也是包含了多个连续的空格但是显示的时候只有1个空格，也可以试试这个方法
