### ISSUE TITLE
随机出现：unknow prop 'isbrafttag' on <braftspan> tag

### ISSUE THREAD

**Issue by zhoudeyou945** [margox/braft-editor#119]
react使用的时候偶尔会出现Warning:Unknown prop `isbrafttag` on <braftspan> tag. Remove this prop from the element.For details, see https://fb.me/react-unknown-prop in braftspan
出现频率：随机
具体影响暂时还没深入观察，有什么解决办法

**Comment by margox** [comment]
用的是什么版本的编辑器？ 最新版本里面已经去除了isbrafttag相关的逻辑，你升级下试试看

**Comment by zhoudeyou945** [comment]
好的，谢谢，用的是1.8.3的，个人觉得非常好用的富文本编辑器^_^
