### ISSUE TITLE
插入图片报错: block is not a BlockNode

### ISSUE THREAD

**Issue by ShuBuShao** [margox/braft-editor#122]
首先感谢作者开发的这个编辑器, 真的很好!

我遇到的问题是 插入图片的时候(没有使用 react-quill) 会报错,报错信息如下截图
![2018-04-19 2 26 21](https://user-images.githubusercontent.com/25656460/38974718-bc19a916-43dd-11e8-9c93-c6240c9ec3e1.png)
![2018-04-19 2 26 49](https://user-images.githubusercontent.com/25656460/38974724-c01d8dd4-43dd-11e8-96a8-5113eb1ee847.png)

我是在antd pro 中使用的
<img width="454" alt="2018-04-19 2 30 31" src="https://user-images.githubusercontent.com/25656460/38974910-62366bf4-43de-11e8-8cde-e377d7e2bb8f.png">
<img width="552" alt="2018-04-19 2 30 53" src="https://user-images.githubusercontent.com/25656460/38974915-65b50c72-43de-11e8-9dad-98a462d76654.png">
<img width="459" alt="2018-04-19 2 31 26" src="https://user-images.githubusercontent.com/25656460/38974918-6831071c-43de-11e8-9e6e-0d4a0a3123bd.png">

我的配置和代码如下
<img width="822" alt="2018-04-19 2 32 44" src="https://user-images.githubusercontent.com/25656460/38974986-ac57379a-43de-11e8-887d-6db7afff7e62.png">
<img width="873" alt="2018-04-19 2 33 58" src="https://user-images.githubusercontent.com/25656460/38974998-b983129a-43de-11e8-9f04-28232864d041.png">
<img width="616" alt="2018-04-19 2 34 52" src="https://user-images.githubusercontent.com/25656460/38975039-db179ef8-43de-11e8-9d72-baffbb8775b7.png">
上传图片是成功的, 上传成功后, 插入到文档中, 就会出现上面的报错; 把uploadFn配置为 null 也是一样报错

我试了很多次, 也查了很多, 看了之前的 issues, 没有出现同样情况的, 希望作者解答一下

**Comment by margox** [comment]
依赖中没有看到draft-js的版本，你试试安装一下0.10.3的draft-js

**Comment by xiaonanhaier** [comment]
问下
TypeError: param.progress is not a function
是怎么回事儿？

**Comment by shenqihui** [comment]
@margox  果然是。谢谢。
