### ISSUE TITLE
插入图片后点击图片右侧的空白区域，按回车报错

### ISSUE THREAD

**Issue by dpshen** [margox/braft-editor#123]
![c](https://hcrm.oss-cn-shanghai.aliyuncs.com/image/873f460c9b55baf8815227d5ac9eb276)

**Comment by margox** [comment]
bug已确认，我会尽快修复，今天或者明天发一个版本

**Comment by xiaonanhaier** [comment]
这个问题修复了吗？

**Comment by xiaonanhaier** [comment]
可以了，非常感谢

**Comment by margox** [comment]
height属性是传什么？ 必须是不带单位的哟
