### ISSUE TITLE
编辑器只有图片时, 不显示光标

### ISSUE THREAD

**Issue by ShuBuShao** [margox/braft-editor#128]
情景: 
编辑某个商品详情的时候,  在编辑器装插入10张图片(只有图片),  保存的时候把 htmlContent传给后端, 
后端把空的<p>标签去掉了,  再次编辑这个商品的详情的时候,  
initialContent使用后端传过来的内容(去掉空的<p>标签之后的), 
这时编辑器没有光标, 点击也没有反应, 光标始终不出现, 再次插入图片, 会把某一张图片替换掉(一般是最后一张)

想要的效果: 可以找到光标, 或者接着插入图片, 而不是替换掉某一张,

请问有什么提示或解决方案吗

**Comment by margox** [comment]
因为图片在编辑器内部属于一个不可编辑的对象， 所以需要在前后带一对空标签，就是为了光标可以有地方放的。后端最好不要把空的P标签去掉，如果实在需要去除空标签的话，那建议保存一份raw格式的数据到后端以便于编辑，html随意处理都不会有问题了。
