### ISSUE TITLE
上传视频问题?

### ISSUE THREAD

**Issue by melissaloves** [margox/braft-editor#13]
当我上传了一个视频，回到编辑器，鼠标点击刚上传的视频（意思是将光标移到刚上传的视频），然后再点击媒体选择一个视频，按下确定控制台报“Uncaught TypeError: Cannot read property 'getKey' of undefined at t.a.selectNextBlock ”错误。
  音频和视频有这种问题。如果编辑器只有图片，就不会报错， 图片会自动向下插入一张图片。音频和视频需要将光标移到空白处才能插入， 麻烦帮看一下！

**Comment by melissaloves** [comment]
@margox 帮看下

**Comment by margox** [comment]
好的，我看看

**Comment by margox** [comment]
@melissaloves  已经解决，1.1.7版已更新到npm，升级一下试试

**Comment by melissaloves** [comment]
@margox 好的 谢谢
