### ISSUE TITLE
组件卸载处理和多实例共存

### ISSUE THREAD

**Issue by jsCONFIG** [margox/braft-editor#14]
使用过程中感觉这个编辑器还可以做得更加精细点，主要有下面几个点：

1. 组件卸载时的销毁处理(添加到Body上的class移除、事件绑定的移除、数据清理等)；
2. 多个实例共存时是否能正常运行(使用中发现内容串扰的问题)；
3. 组件更新时的内容覆写问题(期望能覆写)；

**Comment by margox** [comment]
恩，非常感谢提出建议，下一版本会加以改进 👍👍👍

**Comment by margox** [comment]
@jsCONFIG 你好，我在抽空对你提出的问题进行处理，需要了解一下，多个实例共存的时候内容串扰的问题具体是指？ 能麻烦贴一下你的代码么?
