### ISSUE TITLE
表格插入通过提供的扩展组件api能实现吗

### ISSUE THREAD

**Issue by wrfighting** [margox/braft-editor#140]
是否有考虑加入能插入表格的特性的计划，通过目前提供的api，自己扩展组件能实现表格插入吗

**Comment by margox** [comment]
你好，因为draft-js本身不支持表格内容，而且本编辑器目前也没有实现表格功能，所以你的需求目前还没办法达到哦，另外最近我这边没有太多时间来对本项目进行大的功能的开发，所以还确定不了什么时候能完成表格功能，不过一旦有进展，我会通知你的，非常感谢关注

**Comment by zhangzewei** [comment]
我也比较关注表格的插入 因为一般的文档编辑器 少了表格 就少了一个使用的理由了

**Comment by margox** [comment]
恩，在功能性方面，还是传统的富文本编辑器比如UEditor和KindEditor这些更有竞争力，根据需求选择合适的才行
