### ISSUE TITLE
兼容性问题，IE10下无法选择颜色

### ISSUE THREAD

**Issue by nanjixiong218** [margox/braft-editor#144]
能说明下兼容性的支持么？

**Comment by margox** [comment]
因为我这边开发环境都是非windows环境的，所以对IE系列的浏览器也没用做过太多的兼容性处理，能麻烦说明一下这个问题的具体表现么？是颜色选择器无法弹出，还是选择了颜色之后没有生效？控制台有没有出现错误？ IE11和IE Edge有没有问题？

**Comment by nanjixiong218** [comment]
![image](https://user-images.githubusercontent.com/5085933/40265891-8b272d3a-5b73-11e8-9d1d-6c96459e477b.png)

颜色选择器无法弹出，控制台脚本报上诉错误

**Comment by nanjixiong218** [comment]
IE11和Edge没问题

**Comment by nanjixiong218** [comment]
应该是dataset 不兼容IE10

**Comment by nanjixiong218** [comment]
我提了一个MR解决这个问题，如果你看没什么问题的话，希望能尽快处理下，我的项目急着上线，否则我就要自己发个包了，感谢！

**Comment by margox** [comment]
@nanjixiong218 我中午之前发一个braft-polyfills的单独包吧，因为polyfill的内容不大适合放在独立组件项目里面，因为可能不止我这一个项目需要兼容dataset，也可能相当一部分人不需要这个polyfill，做成按需使用最合适。 现在你可以先在你自己的项目里polyfill一下。

**Comment by margox** [comment]
因为周末这两天在搬家，所以没时间上github

**Comment by nanjixiong218** [comment]
好吧，不过我还是建议内置在组件里，这样起码可以对外称兼容IE10及以上，而不是提供方案把兼容性问题的解决抛给项目使用方。

**Comment by margox** [comment]
@nanjixiong218 
现在可以` yarn add braft-polyfill`试试了，然后直接`import 'braft-polyfill'`就行，polyfill操作已经在这个包里面自动执行了。

另外，以后可能会有更多的内容添加到polyfill里面，所以作为一个独立的包方便维护一些。

**Comment by margox** [comment]
https://github.com/margox/braft-polyfill/invitations

**Comment by nanjixiong218** [comment]
ok
