### ISSUE TITLE
initialContent 传入可编译的html内容无法显示

### ISSUE THREAD

**Issue by rainbowMorelhahahah** [margox/braft-editor#147]
![image](https://user-images.githubusercontent.com/11493796/40300805-e42c5342-5d1c-11e8-97ff-391dea40d7bb.png)
![image](https://user-images.githubusercontent.com/11493796/40300817-ebd74f5c-5d1c-11e8-9df7-41cec1216c92.png)
![image](https://user-images.githubusercontent.com/11493796/40300876-1670c748-5d1d-11e8-8627-6f1589bd7140.png)

**Comment by margox** [comment]
initialContent字面意思即为初始化内容，如果在组件已经渲染完成之后再设置这个属性，默认是不会生效的，可以配合contentId一起使用：
```jsx
<BraftEditor initialContent={this.state.Content} contentId={this.state.Content ? 'test-id' : null}/>
```
或者调用编辑器的实例方法来设置内容：
```javascript
this.editorInstance.setContent('xxxx', 'html')
```

**Comment by rainbowMorelhahahah** [comment]
明白了
