### ISSUE TITLE
在使用extendControls 的时候增加一个按钮onClick，并没有event 这个对象？

### ISSUE THREAD

**Issue by jeremyChenMing** [margox/braft-editor#151]
例如下面这个
`extendControls: [
        {
          type: 'split'
        },
        {
          type: 'button',
          text: '预览',
          html: '<span >预览</span>',
          hoverTitle: '预览',
          className: 'preview-button',
          // onClick: this.click,
          onClick: (e) => {console.log(e)} //e => undefined
        }
      ]`

如果是循环增加标签BraftEditor，
那如何知道我点击的是哪一个BraftEditor？？
总共两个问题怎么解决啊？

**Comment by jeremyChenMing** [comment]
好的！谢谢

**Comment by margox** [comment]
@jeremyChenMing 不好意思忙忘记了，已经发布了1.9.6，解决了你第一个问题，第二个问题，你加一下QQ群725634541 一起交流一下。

**Comment by jeremyChenMing** [comment]
@margox 群以加，等待同意中
