### ISSUE TITLE
1.9.6版本，弹开链接无法输入链接地址

### ISSUE THREAD

**Issue by kingyu** [margox/braft-editor#155]
![image](https://user-images.githubusercontent.com/5800811/40704597-1d80f7b0-641b-11e8-901d-a46c5392725a.png)

**Comment by margox** [comment]
用了antd表单的getFieldDecorator么？ 这个会更改被其包裹的表单对象的行为，这个链接输入框受到了影响，试试不要用getFieldDecorator，用编辑器的setContent方法和onChange来设置和获取内容

**Comment by kingyu** [comment]
@margox 果然，antd这个这么坑，谢谢，这个富文本轮子做得不错

**Comment by kingyu** [comment]
用组件在包一层，就可以使用antd表单的getFieldDecorator
![image](https://user-images.githubusercontent.com/5800811/40708746-cc61a80a-6426-11e8-820e-0ad6a2411120.png)

**Comment by margox** [comment]
赞一个，大佬欢迎加QQ群（725634541）交流

**Comment by kingyu** [comment]
@margox 你才是大佬，我在群里 (#^.^#)
