### ISSUE TITLE
关于转换成html的问题

### ISSUE THREAD

**Issue by LiHaoGit** [margox/braft-editor#156]
在编辑器里
![image](https://user-images.githubusercontent.com/7036191/40787635-ad02fa68-6520-11e8-8252-7fac4542c52f.png)
在编辑器里渲染的标签如下
![image](https://user-images.githubusercontent.com/7036191/40787672-be9aa064-6520-11e8-9ddb-fc018a5c1c92.png)
在`onHTMLChange`转换成`html`渲染的标签如下
![image](https://user-images.githubusercontent.com/7036191/40787694-d2d675a8-6520-11e8-8a0f-59241c6984dd.png)

当我拿到raw格式的内容的时候，如果把这个raw也转换成个在编辑器里渲染的内容一样。  
因为标签不一致，导致的在样式上会有少许的差别

**Comment by margox** [comment]
你好，这个编辑器并不是传统意义上的所见即所得，通过审查元素看到的编辑器内容其实只是draft-js对DraftContentState的一个转换，这些内容是不适用于纯展示的，通过getHTMLContent或者onHTMLChange取到的HTML内容是简化提纯了之后的内容。
编辑器内部对代码块、引语块和列表项进行了少许美化展示，你也可以在你的展示页面通过css对pre、ol、li等标签进行适当的美化以达到和编辑时相似的效果。
