### ISSUE TITLE
可以在文件信息里面包含文件的本地路径吗？

### ISSUE THREAD

**Issue by NRD90M** [margox/braft-editor#158]
可以在文件信息里面包含文件的本地路径吗？

**Comment by margox** [comment]
啊？ 虽然不太懂你的需求是什么意思，但是在现代浏览器里面，是没办法获取到所选文件的完整本地路径的。

**Comment by NRD90M** [comment]
那我怎么可以调用百度云的bos上传图片呢，
![tim 20180607165232](https://user-images.githubusercontent.com/30235128/41088897-3830abba-6a73-11e8-989e-bbe75e791278.png)

**Comment by margox** [comment]
![image](https://user-images.githubusercontent.com/7866354/41089192-d3c4ed7a-6a73-11e8-9b55-40fc128d847f.png)
这个不是node端的写法么? 在浏览器端你需要另外的写法，参考一下[JavaScript-SDK](https://cloud.baidu.com/doc/BOS/JavaScript-SDK.html#.8F.CB.19.D3.C3.FF.C9.2D.7E.18.0C.01.86.22.05.11)，这里面有个client.putObjectFromBlob:
```javascript
client.putObjectFromBlob(bucket, object, <blob对象>)
  .then(done)
  .catch(fail);
```
编辑器的uploadFn的param.file就是一个blob对象

**Comment by NRD90M** [comment]
傻傻分不清node环境和浏览器环境，以为自己电脑装了node.js就是node环境了，param.file是不是就是Blob形式的对象，好像还是不太行啊
