### ISSUE TITLE
For some reason only one font style shows up

### ISSUE THREAD

**Issue by fameoflight** [margox/braft-editor#159]
![screenshot 2018-06-09 02 25 39](https://user-images.githubusercontent.com/6227080/41190046-79b5cdda-6b8c-11e8-968d-ae7209a6a5e4.png)

See screenshot, for some reason only one font style appear.

**Comment by margox** [comment]
Hi, you can check if there are other external styles that affect the style of the FontFamily list by using the Browser Developer Tools, and check the content of the FontFamily DropDown is correct or not.
![image](https://user-images.githubusercontent.com/7866354/41190851-77983268-6c18-11e8-866b-c7d2b42ff2fe.png)

**Comment by fameoflight** [comment]
there was something wrong with my styles
