### ISSUE TITLE
建议：希望可以支持代码块语法高亮

### ISSUE THREAD

**Issue by weihomechen** [margox/braft-editor#163]
hi, 我在尝试使用诸如 [prismjs](https://prismjs.com/) 等语法高亮插件时，按照文档使用后得不到高亮的效果，

![image](https://user-images.githubusercontent.com/16172317/41267593-95a0cb68-6e2e-11e8-812a-d9ab01ba9245.png)

想请问作者大大是否有支持语法高亮的打算？谢谢🙏

**Comment by margox** [comment]
目前在准备开发2.0的大版本，功能和架构上都会进行大的调整，之后会调研一下语法高亮的可行性。

**Comment by weihomechen** [comment]
@margox  作者大大辛苦了，期待2.0😊

**Comment by margox** [comment]
@weihomechen 忘记通知你啦，最新版本可以支持代码高亮了 https://braft.margox.cn/demos/code-highlighter

**Comment by weihomechen** [comment]
厉害了哈哈哈
