### ISSUE TITLE
空格与换行无效

### ISSUE THREAD

**Issue by wennjie** [margox/braft-editor#164]
空格与换行无效

**Comment by margox** [comment]
1.目前编辑器的空格输入就是普通的空格而非&nbsp; 而连续的空格在html默认是只展示1个的，后面的版本会优化这个点儿。
2.在编辑器里面插入空行实际上是插入一会空的p标签，如果没有给p标签设定最小高度，那么多个p标签也是看不到效果的，可以通过shift+回车来插入br换行符

**Comment by cmforjava** [comment]
换行已经加了强制换行了,空格我是手动替换成&nbsp;了

**Comment by xailocker** [comment]
同问，预览时空格和换行失效

**Comment by smartcong007** [comment]
空格无效可咋办

**Comment by margox** [comment]
#185

**Comment by margox** [comment]
#

**Comment by zxq08** [comment]
> 1.目前编辑器的空格输入就是普通的空格而非&nbsp; 而连续的空格在html默认是只展示1个的，后面的版本会优化这个点儿。 2.在编辑器里面插入空行实际上是插入一会空的p标签，如果没有给p标签设定最小高度，那么多个p标签也是看不到效果的，可以通过shift+回车来插入br换行符

针对第一个问题，请问作者大大有新的解决办法了吗。。我使用css的解决办法会影响其他样式，所以使用了replaceAll & nbsp; 。。但是这样会导致拿到的dom中的空格也被替换。。目前没有更好的解决办法
