### ISSUE TITLE
过滤 span标签及自定义属性问题

### ISSUE THREAD

**Issue by hackxu** [margox/braft-editor#165]
设置content 为 <p><span value="xxxxx">xxxx</span></p>,最终呈现结果为<p>xxxx</p>

**Comment by margox** [comment]
由于draft-js的框架特性限制，html字符串没办法完全转换成draft-js内部的数据类型，这个是与传统富文本编辑器相比最坑的地方，本编辑器目前也只支持对很少量的属性进行转换，比如color,font-size之类的。

**Comment by hackxu** [comment]
请问有好的方法去设定插入的标签特殊化吗,

**Comment by margox** [comment]
目前还没有办法做到，现在正在准备开发2.0的版本，会有比较大的变动，之后会增加插入自定义标签之类的功能

**Comment by hackxu** [comment]
好的 多谢
