### ISSUE TITLE
Uncaught Error: block is not a BlockNode

### ISSUE THREAD

**Issue by liuyuhong** [margox/braft-editor#168]
`bundle.js:133 Uncaught Error: block is not a BlockNode
    at invariant (bundle.js:133)
    at insertRawBlock (bundle.js:39142)
    at bundle.js:39187
    at base.dll.js:12796
    at List.__iterate (base.dll.js:12303)
    at OrderedMap.__iterate (base.dll.js:12795)
    at OrderedMap.forEach (base.dll.js:14483)
    at encodeRawBlocks (bundle.js:39166)
    at convertFromDraftStateToRaw (bundle.js:39226)
    at BraftEditor.getContent (bundle.js:32178)`

![image](https://user-images.githubusercontent.com/13620871/42084557-936bf012-7bc0-11e8-83b4-93a1f6b34cee.png)

`

import React, { PropTypes, Component } from 'react';
import BraftEditor from 'braft-editor';
import 'braft-editor/dist/braft.css';

export default class Description extends Component {
  constructor(props) {
    super(props);
  }

  handleChange = (content) => {
    console.log(content)
  }

  handleRawChange = (rawContent) => {
    console.log(rawContent)
  }

render() {

    const editorProps = {
      height: 300,
      contentFormat: 'html',
      initialContent: this.props.descpt,
      onChange: this.handleChange,
      onRawChange: this.handleRawChange
    }

    return (
      <div className="description">
        <BraftEditor {...editorProps} ref={instance => this.editorInstance = instance} />
      </div>
    )
  }`

初始化内容后，编辑框获取焦点和每次按键就会报这个错。

**Comment by liuyuhong** [comment]
多谢回复🙏
删掉之前的draft-js和相关包问题解决了。

**Comment by MorningBells** [comment]
🙏🙏
