### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onUnmountComponent' of null

### ISSUE THREAD

**Issue by liuyuhong** [margox/braft-editor#169]
你好，我又遇到一个问题：本地开发的功能没问题，上线后发现只要在编辑器中插入图片就会报错，以下是追踪到的一些代码：

![2018-07-04 2 59 14](https://user-images.githubusercontent.com/13620871/42261441-e5bfc39c-7f9a-11e8-8ec0-4a29c5245368.png)
![image](https://user-images.githubusercontent.com/13620871/42261504-0ea95a3e-7f9b-11e8-885f-958fe4aead62.png)
![image](https://user-images.githubusercontent.com/13620871/42261546-27add76c-7f9b-11e8-840f-27578f39b16c.png)
![image](https://user-images.githubusercontent.com/13620871/42261774-d7e28b50-7f9b-11e8-8151-14a4772b3b3a.png)

编辑文字内容没问题，就是插入图片就会报错，图片上传成功了，但是编辑器里的内容无法保存；

**Comment by margox** [comment]
试试升级一下react和react-dom试试？

**Comment by margox** [comment]
貌似是因为虽然是在生产环境，但是调用到了开发环境的react-dom的一些API，检查一下打包参数看看，我看到你那边使用了dll策略，试试把react-dom/server也加入到dll的规则里面去

**Comment by liuyuhong** [comment]
把react-dom/server加到了webpack配置中问题解决了，非常感谢🙏

**Comment by liuyuhong** [comment]
为什么在生产环境就会在服务端渲染react-dom呢？是插件的配置吗？

**Comment by margox** [comment]
感觉应该是配置的问题，之前也有同学遇到类似的问题，只不过刚好跟你的相反，只在开发环境报错，打生产包出来没问题

**Comment by liuyuhong** [comment]
好的，回头仔细研究一下，再次感谢！
