### ISSUE TITLE
上传图片，后台接口提示找不到 ‘file’ 字段

### ISSUE THREAD

**Issue by JustYJQ** [margox/braft-editor#171]
**基于antd-pro 开发**
` uploadFn=(param)=>{
    
    const serverURL = '/api/file/upload' 
    const xhr = new XMLHttpRequest
    const fd = new FormData()
    // libraryId可用于通过mediaLibrary示例来操作对应的媒体内容
    //console.log(param.libraryId)
    const successFn = (response) => {
    // 假设服务端直接返回文件上传后的地址
    // 上传成功后调用param.success并传入上传后的文件地址
    param.success({
      url: xhr.responseText,
      meta: {
        id: 'xxx',
        title: 'xxx',
        alt: 'xxx',
        loop: true, // 指定音视频是否循环播放
        autoPlay: true, // 指定音视频是否自动播放
        controls: true, // 指定音视频是否显示控制栏
        poster: 'http://xxx/xx.png', // 指定视频播放器的封面
        }
      })
    }
    const progressFn = (event) => {
     // 上传进度发生变化时调用param.progress
      param.progress(event.loaded / event.total * 100)
    }

    const errorFn = (response) => {
      // 上传发生错误时调用param.error
      param.error({
      msg: 'unable to upload.'
     })
    }

  xhr.upload.addEventListener("progress", progressFn, false)
  xhr.addEventListener("load", successFn, false)
  xhr.addEventListener("error", errorFn, false)
  xhr.addEventListener("abort", errorFn, false)
  console.log(param.file)
  fd.append('file', param.file)
  xhr.open('POST', serverURL, true)
  
  xhr.send(fd)
  }`
测试代码，上传没问题 <form method="POST" action="http://localhost:8080/api/file/upload" enctype="multipart/form-data"> <input type="file" name="file"/><br/><br/><input type="submit" value="Submit"/>

**Comment by margox** [comment]
可以通过浏览器开发者工具查看一下上传的请求，检查一下里面是否包含了文件，在后端打印一下接收到的请求的全部内容看看

**Comment by JustYJQ** [comment]
@margox 

Request URL:http://localhost:8000/api/file/upload
Referrer Policy:no-referrer-when-downgrade
Request Headers
Provisional headers are shown
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryVxPHe7AkkFgIB76y
Origin:http://localhost:8000
Referer:http://localhost:8000/
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Request Payload
------WebKitFormBoundaryVxPHe7AkkFgIB76y
Content-Disposition: form-data; name="file"; filename="git.png"
Content-Type: image/png


------WebKitFormBoundaryVxPHe7AkkFgIB76y--

**Comment by JustYJQ** [comment]
@margox 
<!DOCTYPE html>
<html>
<body>
<form method="POST" action="http://localhost:8080/api/file/upload" enctype="multipart/form-data">
    <input type="file" name="file"/><br/><br/>
    <input type="submit" value="Submit"/>
</form>
</body>
</html>
这样可以

**Comment by margox** [comment]
这里说明前端是已经把文件发送到后端了的，可以排除是前端的问题，检查一下后端的代码吧
