### ISSUE TITLE
建议增加一些样式自定义配置

### ISSUE THREAD

**Issue by liujian10** [margox/braft-editor#176]
建议增加一些样式自定义配置
例如给容器，工具栏，内容框分别开放一个自定义类名的入口，类似react-draft-wysiwyg 中的 toolbarClassName，wrapperClassName，editorClassName
![image](https://user-images.githubusercontent.com/17332112/42557399-0b9031b6-8521-11e8-88fb-b3fb012afa58.png)

建议去掉一些写死的样式
![image](https://user-images.githubusercontent.com/17332112/42557453-2c6a5ce0-8521-11e8-8734-0eee0a118e4d.png)
![image](https://user-images.githubusercontent.com/17332112/42557467-39822e62-8521-11e8-8b37-26b462534b0e.png)

**Comment by margox** [comment]
新版本已经支持这些属性了吼 https://www.yuque.com/margox/be/gz44tn
