### ISSUE TITLE
复制粘贴的时候，格式没有正确的被复制

### ISSUE THREAD

**Issue by Saul-Mirone** [margox/braft-editor#18]
![image](https://user-images.githubusercontent.com/10047788/34863928-d56ff1b8-f7ac-11e7-9e35-17b72e6b5ed6.png)
如图

**Comment by margox** [comment]
想知道复制源实际的HTML代码是什么样子的?

**Comment by margox** [comment]
如果那个大号的QAQ是fontSize设置的而且fontSize值不在编辑器的可用字号里面，那目前还不支持直接复制过来
