### ISSUE TITLE
纯文本模式问题

### ISSUE THREAD

**Issue by xiaobo1234** [margox/braft-editor#181]
设置纯文本模式后，直接粘贴从网页复制的内容，会出现样式。
如果将从网页复制的内容先粘贴到文本编辑器（如：Atom），再从纯文本编辑器复制，粘贴出来的又变成了纯文本。

复制的内容截图：
![image](https://user-images.githubusercontent.com/9973589/43132318-ff8cf1f4-8f6d-11e8-8db9-5781ed95d3fb.png)

纯文本模式直接粘贴内容的截图：
![image](https://user-images.githubusercontent.com/9973589/43132473-7d91b026-8f6e-11e8-95b1-ed1653edc7dc.png)

内容直接粘贴到文本编辑器 Atom 的截图：
![image](https://user-images.githubusercontent.com/9973589/43132517-a849f12a-8f6e-11e8-861a-853d237fc1be.png)

从文本编辑器 Atom 复制后，重新粘贴的内容截图：
![image](https://user-images.githubusercontent.com/9973589/43132583-dbecc750-8f6e-11e8-8b89-85fc3a7a5830.png)

**Comment by margox** [comment]
已确认，在新版中会修复

**Comment by xiaobo1234** [comment]
期待新版本
