### ISSUE TITLE
自适应高度后，焦点有问题

### ISSUE THREAD

**Issue by xiaobo1234** [margox/braft-editor#184]
```
.BraftEditor-content {
  height: auto !important;
  min-height: 200px;
  max-height: 500px;
}
```

1. 默认高度的设置直接使用了内联样式，导致外部样式表只能使用 `!important` 才使自适应高度生效。

2. 设置自适应高度后，点击编辑框的空白处，无法获取到焦点。

**Comment by margox** [comment]
因为子元素的高度没办法自动100%，所以还需要使用CSS hack一下让实际编辑区域也有高度才行，新版本会解决掉这个问题

**Comment by xiaobo1234** [comment]
👌
