### ISSUE TITLE
工具栏的按钮都没有type="button" 怎么解决？

### ISSUE THREAD

**Issue by f85797** [margox/braft-editor#186]

**Comment by margox** [comment]
你用的是什么版本的？？

**Comment by f85797** [comment]
移除重装会不会好呢？ 用npm的 什么命令重新装呢？

**Comment by f85797** [comment]
这里确实也是显示1.9.8
不知道是哪里设置的问题

**Comment by margox** [comment]
先npm uninstall braft-editor再npm install --save braft-editor

**Comment by f85797** [comment]
重新装也是老样子，还是没有Type=button属性

**Comment by margox** [comment]
我看看哈

**Comment by margox** [comment]
我这边可以确认1.9.8是没这个问题的，你确认你引用到的braft-editor是你node_modules下面的么？ 看看是不是引入到了不正确的包

**Comment by f85797** [comment]
![tim 20180731154631](https://user-images.githubusercontent.com/41942745/43445447-ef32967c-94d8-11e8-9bda-281d806ad049.png)

**Comment by margox** [comment]
试试执行下 `npm uninstall braft-editor -g` 排除一下有全局安装了braft-editor的情况

**Comment by f85797** [comment]
执行之后，还是一样缺少type=button

**Comment by margox** [comment]
把node_modules目录删掉，再重新npm install试试吧

**Comment by f85797** [comment]
重启nodeJs之后发现神奇的有了type=button，好神奇！ 感谢大牛的指导！
