### ISSUE TITLE
删除内容的问题

### ISSUE THREAD

**Issue by xiaobo1234** [margox/braft-editor#187]
使用鼠标选中编辑的内容后，点击键盘 delete 键删除，居然不是删除选中的所有内容，而是删除了选择前光标位置的前一个字符，出现频率非常高。如果选中后，等一下再点击 delete，则会删除选中的内容。

**Comment by yzllee** [comment]
复现+1 希望能够修复。

**Comment by margox** [comment]
这个似乎是系统级别的问题，比如在Mac上用触控板选择文字，需要等一会之后，选区状态才会真正的更新，但是用鼠标则没有这个问题，不知道你们是哪个平台？

**Comment by xiaobo1234** [comment]
是 Mac 上发现的问题

**Comment by marialovesbeans** [comment]
为什么issue close了？这是个非常严重的问题，我们公司使用这个插件，现在无法正常工作。google doc，原生`<textarea>`都没这个问题。。。。。想问现在有解决方案么？

**Comment by margox** [comment]
@marialovesbeans 额，我用Mac在QQ啊微信上都有这个问题啊，用触摸板选择文字之后要过个1秒，内存中的选区信息才会更新，这个时候复制才有效。用鼠标的话没这个问题

**Comment by xiaobo1234** [comment]
@marialovesbeans 暂时没有解决。之前也到 draft-js 上找过解决方案，然而并没有结果。理论上来说，正常使用并不会有什么影响，也就没有再进一步处理。
分享个简单的想法：拦截 delete 的事件，判断当前选中区域与光标位置是否一致。如果不一致，加个 1 秒延迟再继续执行；如果一致，就让它自动执行。
