### ISSUE TITLE
每个按钮点击时，都会submit 整个form， 怎么办？

### ISSUE THREAD

**Issue by yuedefeng** [margox/braft-editor#19]
<Form
                onSubmit={this.handleSubmit}
                style={{ marginTop: 8 }}
              >
                <FormItem
                  {...formItemLayout}
                  label="标题"
                >
                  {getFieldDecorator('title', {
                    rules: [{
                      required: true, message: '请输入标题',
                    }],
                  })(
                    <Input placeholder="请输入标题" />
                  )}
                </FormItem>
               
                <FormItem
                  {...formItemLayout}
                  label="正文"
                >
                  {getFieldDecorator('content', {
                    rules: [{
                      required: true, message: '请输入正文',
                    }],
                  })(
                    <BraftEditor {...editorProps} />
                  )}
                </FormItem>
</Form>

**Comment by margox** [comment]
应该是你这个FormItem组件对内部的每个Button都做了事件监听，FormItem是来自于antd或者什么其他框架么？

**Comment by yuedefeng** [comment]
FormItem 是用的 ant-design 组件库的， 整体框架是ant-design pro.

**Comment by margox** [comment]
看了一下，感觉FormItem里面应该不支持放这种复杂的子组件，你试试不要放在FormItem里面，通过编辑器的onChange或者onHTMLChange来取到输入的内容

**Comment by yuedefeng** [comment]
好的，放在form外面是可以的，但是排版布局就不方便了，没法和其它控件放在一起。

**Comment by margox** [comment]
我抽空自己拿到antd里面试试

**Comment by liushunqiu** [comment]
去掉<Form>标签里面的submit事件，然后自己标注Button触发就可以解决的。
