### ISSUE TITLE
添加的图片默认没有宽高样式

### ISSUE THREAD

**Issue by splsylp** [margox/braft-editor#193]
添加的图片如果不手动设置宽高的话，默认不会自动设置宽高样式，导致在react-native的htmlView中无法显示图片。并且图片宽高比例不定，在rn中也不好指定默认宽高。这个功能什么时候能添加更新下吗？

**Comment by margox** [comment]
你好，之前忘了这个点，试试更新一下braft-editor,braft-utils,braft-convert到最新版本，现在param.success里面可以传入width和height了

**Comment by splsylp** [comment]
编辑器的图片展示什么都不设置也没问题，我说的不是在web中显示的，而是app的。场景是通过web的编辑器编辑好后，app通过htmlView来加载显示，app应用是使用的react-native

**Comment by margox** [comment]
那你在uploadFn里，获取到图片的物理尺寸，然后调用param.success的时候把这个尺寸传进去就行了

**Comment by splsylp** [comment]
现在最新的版本可以在param.success里面可以传入width和height了哈，那就可以这么实现了。但是最初的想法是想着你能给它自动设置上，我就省去这一步了，哈哈~ 这样也挺好了，谢谢~
