### ISSUE TITLE
文字无法居中

### ISSUE THREAD

**Issue by RickIsCoder** [margox/braft-editor#20]
1.1.9版本，只是简单的引入了尝试后发现点击居中 居左都无效

**Comment by margox** [comment]
请问可以提供一下调用的源码么？另外可以用开发者工具看一下选中的文字的样子是否被别的CSS覆盖掉了？

**Comment by margox** [comment]
在safari里面复现了此问题，我找下原因

**Comment by margox** [comment]
找到原因了，我先去吃饭，吃完饭发个版

**Comment by margox** [comment]
发了新版，再试试看
