### ISSUE TITLE
建议能自己定义上传图片格式

### ISSUE THREAD

**Issue by wxc520** [margox/braft-editor#206]
![image](https://user-images.githubusercontent.com/29634142/45022827-c0f1eb00-b067-11e8-9dcd-7c6972527756.png)

**Comment by li-z** [comment]
@margox 请问现在支持限制格式了吗，我发现 http://margox.github.io/braft-editor/ 官方的demo是可以限制了

**Comment by margox** [comment]
@li-z 还没有，最近公司的事情太多，还没有足够的空余时间来开发新的版本，当前版本只能控制是否可以上传图片和音视频，可以参考文档里面media属性的说明，对于图片的MIME类型还不支持自定义

**Comment by margox** [comment]
已经发布v2.0.6，新增了media.accepts属性，https://www.yuque.com/margox/be/gz44tn#p48dit
