### ISSUE TITLE
请教一下 粘贴问题

### ISSUE THREAD

**Issue by zjdschnappi** [margox/braft-editor#207]
你好，我是仿照你的代码写了一波编辑器，，其中对粘贴这块有点搞不清， 通过imagepicker插入到编辑器里的图片，选中后 复制粘贴 ， 会变成文件名。。我如何过滤掉这种

复制
![image](https://user-images.githubusercontent.com/15072751/45069644-22fe2f00-b100-11e8-800a-6cfae06faac8.png)

粘贴
![image](https://user-images.githubusercontent.com/15072751/45069703-6bb5e800-b100-11e8-876f-37ad659c11a4.png)

**Comment by margox** [comment]
https://github.com/margox/braft-editor/blob/master/src/editor/index.jsx 参考一下这文件里面的handlePastedFiles

**Comment by margox** [comment]
如果需要突破不可拖选，加个css属性试试:
```css
.image{
  user-select: none;
}
```

**Comment by zjdschnappi** [comment]
是的。我只能用这方法禁止选中了
