### ISSUE TITLE
请教如何实现插入和编辑表格的功能

### ISSUE THREAD

**Issue by FourEyebrowXiake** [margox/braft-editor#208]
是按照编辑图片的思路来实现吗？在dratfjs之外编辑表格数据，draftjs只负责展示数据？

**Comment by margox** [comment]
如果要简单的实现，就跟图片一样用Atomic Block就行了，但是还需要要求表格单元格内的文字也可以添加富文本样式，这个就是比较麻烦的点，目前还没深入研究过表格的实现，计划在版本2.3里面去尝试实现一下这个功能
