### ISSUE TITLE
请教下,能够指定焦点的位置吗?

### ISSUE THREAD

**Issue by yyxie** [margox/braft-editor#209]
比如我鼠标随意移动,焦点能跟着我的鼠标移动?希望能回答,感谢

**Comment by margox** [comment]
暂时还没有这个功能哦

**Comment by yyxie** [comment]
其实我是想实现拖拽文字到鼠标在编辑器中停留的位置,不知道有什么可以实现的方案可以提供下?

**Comment by margox** [comment]
如果是文字的话，直接拖拽进去就行了呀
