### ISSUE TITLE
转换成代码格式的时候，在代码尾部敲回车键无效，无法换行

### ISSUE THREAD

**Issue by Downsview** [margox/braft-editor#21]
转换成代码的时候，在代码尾部回车键无效，无法换行，也无法从代码块中切换出来继续在下面输入，在代码块下面点击无效

**Comment by margox** [comment]
囧，发现脚本错误。。我看看

**Comment by margox** [comment]
找到原因了，我6点发个版本吧

**Comment by margox** [comment]
发了新版，再试试看

**Comment by margox** [comment]
对了，要退出代码模式，也可以先按一下Enter，再按Shift|Ctrl + Enter

**Comment by Downsview** [comment]
github上的这个demo更新了吗？我试了下，貌似还是有我说的这个问题

**Comment by Downsview** [comment]
还发现了个问题，就是切换成代码块儿的话，是有个背景颜色的，然后预览的时候就没有任何背景了，就是单纯的<code></code>包装，那我如果将写的内容保存到后台然后前端显示的话，是不是也没有这个背景了？

**Comment by margox** [comment]
嗯，编辑器里面我自己做了样式美化的，但是输出的HTML，我不会做太多干预，毕竟样式各有各的喜好，我会抽空把我采用的样式提供出来作为参考
