### ISSUE TITLE
出来用户自己点清楚按钮时候能清楚，是否有API来调用呢

### ISSUE THREAD

**Issue by xyy7260** [margox/braft-editor#217]
是需要自己改模板来清楚吗还是有，api来调用

**Comment by margox** [comment]
可以的，需要用受控组件的形式使用编辑器。
先引入内容工具包：
```javascript
import { ContentUtils } from 'braft-utils'
```
然后在你的组件或者页面中增加下面的方法:
```javascript
clearContent () {
  this.setState({
    editorState: ContentUtils.clear(this.state.editorState)
  })
}
```
在你想要清除内容的时候，调用this.clearContent()就行了

**Comment by margox** [comment]
ContentUtils里面的源码可以看看： https://github.com/margox/braft-utils/blob/master/src/content.js
后面会完善文档介绍。

**Comment by xyy7260** [comment]
@margox  好的我等下看看
