### ISSUE TITLE
@types are not updated

### ISSUE THREAD

**Issue by nikola1970** [margox/braft-editor#219]
Your example says:

> import BraftEditor, { EditorState } from 'braft-editor';

but TypeScript is complaining:

> has no exported member 'EditorState'.`

And there is no updated types for new version 2.0.5

**Comment by petitspois** [comment]
typescript :  import * as BraftEditor from 'braft-editor'

**Comment by nikola1970** [comment]
It does not help because:

> TS2339: Property 'EditorState' does not exist on type 'typeof BraftEditor'

so because of that, this is not working:

> BraftEditor.EditorState.createFrom(htmlContent)

**Comment by margox** [comment]
I don't know much about TypeSrcipt, I haven't used it basically, the old version of @types/braft-editor file is done by one of my friends(@petitspois ), the new version of Braft Editor is not compatible with it, so if you use the new version, please do not install @types/braft-editor.
I will also get to know TypeScript as soon as possible and provide a usable @types/braft-editor as fast as I can.
