### ISSUE TITLE
初始化完会有横向滚动条，导致字体、字号不能用

### ISSUE THREAD

**Issue by yueyunyue** [margox/braft-editor#22]
![qq 20180119171812](https://user-images.githubusercontent.com/3349723/35143637-22b884b8-fd3d-11e7-893f-16f7c9535453.png)

![qq 20180119171957](https://user-images.githubusercontent.com/3349723/35143753-6bba5e34-fd3d-11e7-9111-35a050d3ef6d.png)

**Comment by margox** [comment]
请问你那边可以看一下是那一块的内容撑大了导致的滚动条么？

**Comment by margox** [comment]
另外，要保证下拉组件的位置显示正常，需要设置viewWrapper属性值

**Comment by margox** [comment]
肯能还是需要麻烦您看一下是哪个元素导致的滚动条，我这个项目实践应用太少了，好多问题我自己都么见过😭😭😭

**Comment by yueyunyue** [comment]
![image](https://user-images.githubusercontent.com/3349723/35203244-4e924822-ff62-11e7-83ef-7e63a32c90b4.png)

感觉滚动条是BraftEditor-container 产生的

**Comment by yueyunyue** [comment]
![image](https://user-images.githubusercontent.com/3349723/35203690-724687ae-ff64-11e7-8df8-f40dd918d8b7.png)
![image](https://user-images.githubusercontent.com/3349723/35203705-82fc50ec-ff64-11e7-9f13-31fd643b0e68.png)
去掉就好了

**Comment by yueyunyue** [comment]
![image](https://user-images.githubusercontent.com/3349723/35203840-39217ec4-ff65-11e7-9a56-cd8a34c05262.png)


覆盖掉overflow以后 弹窗又跑偏了

**Comment by margox** [comment]
overflow 选项只是控制是否显示滚动条，真正造成滚动条的，是子元素，感觉可能是有什么DOM元素的样式被干扰了。

**Comment by yueyunyue** [comment]
你能看出来是什么导致的吗

**Comment by margox** [comment]
你的项目是开源的么？ 如果方便的话可以，我这边不亲自跑一下，不太好定位问题😭

**Comment by yueyunyue** [comment]
不是开源的；就是antd集成的    https://github.com/ant-design/ant-design-pro 可以用这个项目试试

**Comment by liushunqiu** [comment]
这个确实是，我页面刚开始进去的时候也没事，然后在当前页面刷新的时候，也会出现滚动条，然后就没办法选择字体大小了。~ @margox 希望能解决~

**Comment by margox** [comment]
@liushunqiu 都是在antd里面用会出现这个问题么？

**Comment by liushunqiu** [comment]
是的。用的ant.design.pro @margox

**Comment by margox** [comment]
能看一下你们这个页面的完整结构么？ 我这边直接用貌似是正常的

**Comment by yueyunyue** [comment]
import React from 'react'
import ReactDOM from 'react-dom'
import {Row, Col} from 'antd'
import BraftEditor from 'braft-editor'
import 'braft-editor/dist/braft.css'

export default class DraftjsView extends React.Component {

render () {

    const editorProps = {
        height: 500,
        initialContent: null,
        viewWrapper: '.demo',
        media:{
            image: true, // 开启图片插入功能
            video: false, // 开启视频插入功能
            audio: false, // 开启音频插入功能
            validateFn: null, // 指定本地校验函数，说明见下文
            uploadFn: null // 指定上传函数，说明见下文
        },
        onChange: this.handleChange,
        onHTMLChange: this.handleHTMLChange
    }

    return (
        <Row>
            <Col span={12} className={"demo"}>
                <BraftEditor {...editorProps}/>
            </Col>
        </Row>
    )

}

handleChange = (content) => {
    console.log(content)
}

handleHTMLChange = (html) => {
    console.log(html)
}
}

你试试用这个间一个页面，我这边是一开始有滚动条 ，如果浏览器窗口改变以后，那个滚动条就没了

**Comment by margox** [comment]
我这边还是没出现这个问题，不过我修改了一下可能会导致这个问题的地方，现在已发1.1.12，升级一下试试？ @yueyunyue @liushunqiu

**Comment by liushunqiu** [comment]
已经升级，发现就算出现滚动条也不会导致字体下拉框移动的问题了。

**Comment by margox** [comment]
@liushunqiu 能方便定位一下滚动条是哪个元素产生的么？看一下哪个元素的宽度异常， 我直接用上面提供的页面源码是无法复现的，应该是外部样式干扰到了

**Comment by margox** [comment]
找到原因了，又发了一版，不知道会不会有副作用，害怕哈哈
