### ISSUE TITLE
能否直接调用，而不是在 react 中使用？

### ISSUE THREAD

**Issue by yunuo-tech** [margox/braft-editor#222]
能不能跟网上其他的html 编辑器那样，直接在 html 里调用？

**Comment by margox** [comment]
不能，这个编辑器的核心就是React,所以只能在React项目中使用哦

**Comment by robert7git** [comment]
那如何 直接使用 转化后的 保存在数据库中的 content（html 标签）.
现在 输出出来没有 style. 我该引用哪个style 文件呢
