### ISSUE TITLE
Can't use style without selecting text /不选择文本就无法使用样式/

### ISSUE THREAD

**Issue by ariunbatb** [margox/braft-editor#225]
Only way to use style like font size, bold etc is select some text before set style. 
只有使用字体大小，粗体等样式的方法是在设置样式之前选择一些文本。

**Comment by ariunbatb** [comment]
i want to select style and then type

**Comment by margox** [comment]
Sorry, due to the framework features of DraftJS, there is currently no way to do this.

**Comment by ariunbatb** [comment]
other editors based on DraftJs working fine. But i want use this one

**Comment by margox** [comment]
ok, please tell me which editors can do this, I will get ideas from them .

**Comment by ariunbatb** [comment]
https://github.com/nikgraf/awesome-draft-js here is the list of editors

**Comment by margox** [comment]
I get it, I will do some try in next version.

**Comment by margox** [comment]
Hi, I just published the new version (2.0.6), and now you can use the inline style buttons without text selected.
and you must also upgrade braft-utils.
