### ISSUE TITLE
使用value属性受控组件，选中两行直接输入汉字报错

### ISSUE THREAD

**Issue by sbyps** [margox/braft-editor#226]
version：2.0.5及1.9.7

handleEditorChange = (editorState) => {
    this.setState({ editorState })
  }
render () {
const editorProps = {
      value: editorState,
      onChange: this.handleEditorChange,
      style: { border: '1px solid #ddd' },
      contentStyle: { height: 200 },
      controls: ['undo', 'redo', 'split', 'font-size', 'font-family', 'line-height',
        'text-color', 'bold', 'italic', 'underline', 'strike-through', 'text-align', 'split', 'headings', 'list_ul',
        'list_ol', 'blockquote', 'code', 'split', 'link', 'split', 'hr', 'split', 'clear'],
      pasteMode: 'text',
    }
    return (
      <BraftEditor {...editorProps} />
    )
}

![20180913204410437](https://user-images.githubusercontent.com/3881956/45489226-55f69180-b796-11e8-99a8-7af690734d74.jpg)

**Comment by margox** [comment]
已确认，感谢反馈，会尽快尝试修复

**Comment by sbyps** [comment]
@margox 有时间安排修复这个吗

**Comment by margox** [comment]
最近公司的工作特别多抽不出身来，今天下班之后我看看吧

**Comment by margox** [comment]
查了一下，这似乎是draft-js的一个bug，几个月前就已经有人提了pr来解决这个问题，但是现在似乎还没有合并， https://github.com/facebook/draft-js/pull/1760
