### ISSUE TITLE
创建editorState的时候报Object is not function错误

### ISSUE THREAD

**Issue by wangzhipeng404** [margox/braft-editor#227]
从1.9.8更新至2.0.5按照文档demo的写法调用EditorState.createFrom(htmlContent)报错
Object inf not a function
暂时回退到1.9.8了，请问怎么解决这个问题？

**Comment by margox** [comment]
贴下你的代码，包括import那里

**Comment by wangzhipeng404** [comment]
代码已经被我回退了，在antd pro的项目里面，大概是这样子的
```
import React from 'react'
import BraftEditor, { EditorState } from 'braft-editor'
import 'braft-editor/dist/index.css'

class Editor extends React.Component {
    .......
    render () {
          const  editorState = EditorState.createFrom(''); //这里就报错了
   .......
    }
}
```

**Comment by margox** [comment]
你在这个页面里面打印一下EditorState对象，看看它里面有没有createFrom这个方法

**Comment by wangzhipeng404** [comment]
之前打印过是有的，这个错是createfrom解析字符串的时候报的，我记得是try JSON.parse() 失败之后会在catch 里面调用
Object(...),所以才会报Object is not a
function，google了一下貌似是rxjs的版本问题，我下周一想办法复现一下再把具体报错发给您吧

超能刚哥 <notifications@github.com>于2018年9月14日 周五20:17写道：

**Comment by margox** [comment]
那你试试EditorState.createFrom()或者EditorState.createFrom(null)
