### ISSUE TITLE
用服务器上现有的媒体初始化媒体库

### ISSUE THREAD

**Issue by Acgsior** [margox/braft-editor#228]
现需要用服务器上已有的媒体资源去初始化编辑器弹出的上传附件的媒体库。

看了下braft-editor和braft-finder的代码应该并不支持，请问下作者有解决方案吗？

**Comment by margox** [comment]
可以试试下面的方法：
```javascript
this.editorInstance.braftFinder.setItems([
  {
    id: 'xxx',
    type: 'IMAGE',
    url: 'https://xxx/xxx.jpg'
  },
  // ...
])
```
关于BraftFinder暂时还没有整理出文档，可以先看看源码：
https://github.com/margox/braft-finder/blob/master/src/controller.js

**Comment by Acgsior** [comment]
谢谢 回头我会试试.
