### ISSUE TITLE
如何在焦点处插入HTML

### ISSUE THREAD

**Issue by NewmanGo** [margox/braft-editor#229]
你好,用以下
const oldHTML = this.editorInstance.getHTMLContent()
const newHTML = <p>Hello World!</p>
this.editorInstance.setContent(oldHTML + newHTML, 'html')
这种方式来更改内容只能在末尾或者开头加,我怎么才能在焦点处插入自定义的html呢

**Comment by margox** [comment]
旧版的话，有一个insertHTML方法的
```javascript
this.editorInstance.insertHTML(`<p>Hello World!</p>`)
```

**Comment by NewmanGo** [comment]
> 旧版的话，有一个insertHTML方法的
> 
> ```js
> this.editorInstance.insertHTML(`<p>Hello World!</p>`)
> ```

2.0的有这个方法吗

**Comment by margox** [comment]
2.0的这些功能，独立到了braft-utils里，需要按下面的方式来用:
```js
import { ContentUtils } from 'braft-utils'
```
```js
insertHTML (html) {
  this.setState({
    editorState: ContentUtils.insertHTML(this.state.editorState, html)
  })
}
```

**Comment by z5829984520** [comment]
> 2.0的这些功能，独立到了braft-utils里，需要按下面的方式来用:
> 
> ```js
> import { ContentUtils } from 'braft-utils'
> ```
> 
> ```js
> insertHTML (html) {
>   this.setState({
>     editorState: ContentUtils.insertHTML(this.state.editorState, html)
>   })
> }
> ```
你好，我想添加一个input的片段input添加属性不生效呢

**Comment by KarenQiao** [comment]
> 2.0的这些功能，独立到了braft-utils里，需要按下面的方式来用:
> 
> ```js
> import { ContentUtils } from 'braft-utils'
> ```
> 
> ```js
> insertHTML (html) {
>   this.setState({
>     editorState: ContentUtils.insertHTML(this.state.editorState, html)
>   })
> }
> ```
可以插入到指定位置吗？现在这个方法只能插入内容的最前面
