### ISSUE TITLE
很好用而且很漂亮的一款富文本编辑器

### ISSUE THREAD

**Issue by IveChen** [margox/braft-editor#23]
我有一个需求是需要将所有的粘贴进来的内容都处理成纯文本(或者说移除原来所有的格式),想问下有哪个api能够处理类似的需求么(比如监听粘贴事件，或者onHtmlBeforeChange之类的)？

**Comment by IveChen** [comment]
搞定了，不过还是建议能提供一些事件或者接口来处理
`<BraftEditor {...editorProps} ref={(instance) => { this.changeEditorConstructor(instance) }} />`
`changeEditorConstructor (editor) {
      if (editor && !this.state.hasChanged) {
        this.state.hasChanged = true
        editor.oldHandlePastedText = editor.handlePastedText
        editor.handlePastedText = function (txt, html) {
          html = html.replace(/<(style|script|iframe)[^>]*?>[\s\S]+?<\/\1\s*>/gi, '').replace(/<[^>]+?>/g, '').replace(/\s+/g, ' ').replace(/ /g, ' ').replace(/>/g, ' ')
          if (!html) {
            return false
          }
          return editor.oldHandlePastedText(txt, html)
        }
      }
    }`

**Comment by margox** [comment]
感谢使用，这个建议很好，后续会考虑加入进来

**Comment by margox** [comment]
@IveChen 已发布1.1.14,新增编辑器属性pasteMode，设置为'text'就可以以纯文本模式粘贴了
