### ISSUE TITLE
添加视频网络资源报错

### ISSUE THREAD

**Issue by shenck215** [margox/braft-editor#230]
![image](https://user-images.githubusercontent.com/20554664/45674726-46919280-bb60-11e8-8981-ca37d422b63f.png)

![image](https://user-images.githubusercontent.com/20554664/45674706-3b3e6700-bb60-11e8-83d1-792e22833a0d.png)

添加网络资源->插入视频，报错。

**Comment by margox** [comment]
已确认，今晚会发一个修复版本

**Comment by margox** [comment]
已发v2.0.6
