### ISSUE TITLE
支持按需引入或自定义打包吗

### ISSUE THREAD

**Issue by jsCONFIG** [margox/braft-editor#231]
RT，只需要用到几个简单功能，这块能不能弄成插件化的形式，按需打包插件

**Comment by margox** [comment]
这个开发量太大，最起码2.x版本的架构还不支持这样做，如果需要的功能很简单，你可以试试自己去用draftjs封装一个

**Comment by jsCONFIG** [comment]
我看draft-js是支持按需加载，你这个包里面是不是可以先把draft-js的引用方式改成按需加载

**Comment by margox** [comment]
如果你这一块有比较深的研究，欢迎提pr哦

**Comment by LuoQaxa** [comment]
![image](https://user-images.githubusercontent.com/19726459/61680990-3af19800-ad3e-11e9-91f9-2c13739cd614.png)
希望能考虑优化一下包的大小，braft-editor在生产模式打包后有700kb左右，看了一下依赖很多包，能有好的办法优化吗？
