### ISSUE TITLE
三克油

### ISSUE THREAD

**Issue by bh5858** [margox/braft-editor#233]
网上找了好久的编辑器，就决定用你这个了，希望一次性成功，给你一颗星哈哈，文档和demo都很用心哈

**Comment by bh5858** [comment]
提一个bug,在初始化页面时，从服务器获取一张图片 EditorState.createFrom(`<img src='xxx'/>`)
并没有其他多余的文本和标签，此时文本编辑器无法获取焦点，也就是写不上文字
比如EditorState.createFrom(`<img src='xxx'/><p>123456</p>`) 测试这种情况下就可以获取焦点

**Comment by margox** [comment]
恩，这个问题是已知的，后面的版本会尝试进行优化

**Comment by bh5858** [comment]
今天用webpack打包的时候，报错了./~/braft-editor/dist/index.css，说是需要一个加载器来处理此文件类型，这个怎么解决啊

**Comment by margox** [comment]
你的webpack里面没有配置cssloader？还是说cssloader 把node_modules目录排除掉了？ 检查一下看看

**Comment by bh5858** [comment]
![image](https://user-images.githubusercontent.com/24493500/46054555-65a0ad80-c17a-11e8-849d-c0eec3125e43.png)

![image](https://user-images.githubusercontent.com/24493500/46054580-7bae6e00-c17a-11e8-807d-85055704a392.png)

你看一下，这样的配置没问题吧

**Comment by margox** [comment]
把你的报错信息贴一下，应该不是css loader的问题，而是eot文件的loader，你升级一下编辑器版本试试

**Comment by bh5858** [comment]
![image](https://user-images.githubusercontent.com/24493500/46054902-edd38280-c17b-11e8-8325-74e137d82f75.png)

![image](https://user-images.githubusercontent.com/24493500/46054911-fb890800-c17b-11e8-9099-25a3b3877057.png)

**Comment by margox** [comment]
额，看来你已经是最新版了
![image](https://user-images.githubusercontent.com/7866354/46054957-3a1ec280-c17c-11e8-9772-6b84a7595f98.png)
把这里面的post-loader去掉试试

**Comment by bh5858** [comment]
我用的是vscode最新版本的

![image](https://user-images.githubusercontent.com/24493500/46054993-6cc8bb00-c17c-11e8-9e77-65121e804f00.png)

**Comment by bh5858** [comment]
![image](https://user-images.githubusercontent.com/24493500/46055106-f8424c00-c17c-11e8-8cab-37a09c12b0ca.png)
注释掉之后，还是 报之前的那个错

**Comment by margox** [comment]
直接改成这样试试
```js
{
  test: /\.css$/,
  include: path.resolve(__dirname, '../node_modules'),
  use: [
    'style-loader',
    'css-loader',
  ]
}
```

**Comment by margox** [comment]
哦，也就是说开发环境没有报错，但是build生存包的时候报错了？ 那看看打生产包的webpack配置文件怎么写的

**Comment by bh5858** [comment]
![image](https://user-images.githubusercontent.com/24493500/46055716-deeecf00-c17f-11e8-91e1-b0f13fe7e9ef.png)

你好，我只是想打包之后发布到测试环境的，这个和生产环境的设置有关系吗，上图是生产环境的

**Comment by margox** [comment]
你打包发到测试环境，执行的是npm run build之类的命令吧，这样子用的就是生产打包的配置文件，实际上打包之后发到哪个环境就是另外一回事了，跟怎么打包是没关系的，
你这个配置里也跟开发环境一样用include和exclude区分一下吧，对于node_modules里面的css，用我上面发的那个loader配置试试

**Comment by bh5858** [comment]
虽然配置不一样，但是开发环境和生产环境报同样的错，是不是braft-editor插件有问题啊

**Comment by margox** [comment]
现在你的开发环境也有问题了？ 那你试试不引入那个css文件看看还会不会报错。
你这个css无法引入问题，还是第一次见到

**Comment by bh5858** [comment]
不引入css的话,打包是没问题的，但是样式全没了，这也不行啊。你还有啥办法呀，

**Comment by margox** [comment]
你试试找到那个css文件，把里面的内容都删掉，然后随便加几个有效的css进去，例如:
```css
/* braft-editor/dist/index.css */
.foo{
  color: #fff;
}
```
然后再引入这个css，看看报错没有，借此来排除是不是css文件的内容有错误导致的报错

**Comment by margox** [comment]
如果引入上面那个简单的css文件依然报错，那就可以确定是webpack的配置有问题了
