### ISSUE TITLE
清除样式功能无效

### ISSUE THREAD

**Issue by MangGoDio** [margox/braft-editor#235]
测试了一段从其他页面拷过来的文字，本地环境下remove-styles这个功能不起效，而demo上是可行的，翻阅了文档也没有看见相关配置，请问是哪里有问题呢

主要是为了解决拷贝过来的文字格式不统一需要初始化的问题

**Comment by MangGoDio** [comment]
多尝试了几次貌似部分文字格式可行部分文字又不可行，有些量大的文本无法清除格式，但是框选小段又能清除掉，请问有没有能将拷贝进编辑器的文字格式清除掉的方法

**Comment by margox** [comment]
这个清除功能目前也不是很完善，如果一段文字包含的样式太多，就会无效，后期会改进这个问题。

**Comment by margox** [comment]
如果用的1.x的话，可以指定pasteMode属性为text，如果使用的2.x的话，设置一下stripPastedStyles={true}就行了

**Comment by MangGoDio** [comment]
好的，我更新下版本，非常感谢
