### ISSUE TITLE
如何设置段落间距

### ISSUE THREAD

**Issue by ChardXu** [margox/braft-editor#236]
遇到的紧急问题如下：
1、如何设置段落间距，里面只有设置行间距和字间距，但是没有段落间距设置啊；
2、还有首行缩进，貌似也没有；
解决途径：
1、我找了一圈，也没有找到配置，请问是否有这个配置？我试着用换行作段落间距，但是生成的确是“<p></p>”，由于p标签没有内容，所有你看到编辑状态是有空格的，但是实际展示效果是没有效果；我是否可以自己给p标签设置最小高度。

**Comment by MinJieLiu** [comment]
自己定义样式，更自由。这种事情不应该编辑器来完成

**Comment by margox** [comment]
@ChardXu 段落间距确实需要通过给p设置最小高度，因为编辑器已经生成了对应的p标签了，不应该再干预布局方面的样式，所以需要自行控制。 
至于缩进，不生效实际上是因为连续的空格只展示为1个空格了，这个可以通过给展示页的p标签设置white-space:pre-wrap;来解决，或者不要在编辑器里面按空格来缩进，直接在展示页设置p标签的text-indent: 2em;来实现，编辑器后面也会考虑空格这方面的优化。

**Comment by cpu220** [comment]
我在想，是否需要编辑器支持段落距离上下的margin选择，来达到对段落间距的支持。
