### ISSUE TITLE
IE9是否兼容

### ISSUE THREAD

**Issue by ZzrBoy** [margox/braft-editor#237]

**Comment by margox** [comment]
IE9基本上用不了，而且IE9的使用率已经很低了，你们的业务可以考虑不用兼容它了

**Comment by ZzrBoy** [comment]
> IE9基本上用不了，而且IE9的使用率已经很低了，你们的业务可以考虑不用兼容它了

客户是银行  --

**Comment by margox** [comment]
额，这样的话，编辑器这块用传统的非React的应该会比较合适吧，UEditor或者kindeditor之类的
