### ISSUE TITLE
一些细节上的建议

### ISSUE THREAD

**Issue by MinJieLiu** [margox/braft-editor#240]
1. 鼠标放在图片上的时候，编辑器会失去焦点，光标位置丢失。建议图片不要在 hover 上显示额外菜单，也应像文字一样有个选中效果，选中后支持 backspace 删除。

2. 编辑器默认是有高度的，在文本超过编辑器高度的时候，文字紧贴底部。感觉像被裁掉一样，应当留一点额外的 padding

3. 撤销重做图标，在没有历史记录的时候撤销图标应为不可点状态。重做图标也应如此

**Comment by margox** [comment]
感谢反馈，在即将发布的2.1中，这些地方都做了相应的优化

**Comment by macc6579** [comment]
> 感谢反馈，在即将发布的2.1中，这些地方都做了相应的优化

想再加一条细节优化建议：
图片编辑的控件，在选中 居左or居右 文字环绕后； 
图片的居左/居右控件的功能  在逻辑层 应该已经失效了，
但鼠标悬浮在图标，UI还是会高亮，会让用户产生误解~
如图
![image](https://user-images.githubusercontent.com/11343720/63164338-bbb06500-c05a-11e9-9f2c-431377433dc9.png)

再次感谢刚哥写出了这么优秀的编辑器~~✿✿ヽ(°▽°)ノ✿
