### ISSUE TITLE
draft.js 版本问题？

### ISSUE THREAD

**Issue by countingSta** [margox/braft-editor#243]
DraftEditorContents.react.js:112 Uncaught TypeError: _block.getKey is not a function

    "immutable": "^4.0.0-rc.9",
        "braft-editor": "^2.0.10",

**Comment by margox** [comment]
怎么才能重现这个报错？

**Comment by countingSta** [comment]
"immutable": "^4.0.0-rc.9" 以上报错，我降到3.8.1就不报错了。4.0 内部api有删改，但没有向后兼容。

**Comment by margox** [comment]
恩，我看了一下，draftjs本身是要求3.x版本的immutable，可能是别的模块依赖了4.x版本的immutable，我得在本项目的package.json里面指定下要用3.x版本的immutable才行

**Comment by countingSta** [comment]
好的，在线等喔

**Comment by countingSta** [comment]
如果项目中引入的immutable版本是4.0.0+，仅仅在peerDependencies限制immutable版本，好像还是无法解决报错问题，请问能否把immutable的版本限制放在dependencies中。

**Comment by margox** [comment]
@countingSta 可以的，在下一个小版本里我改一下

**Comment by countingSta** [comment]
好的，谢谢。
