### ISSUE TITLE
复制的图片在编辑器中丢失样式

### ISSUE THREAD

**Issue by evolu6** [margox/braft-editor#249]
![image](https://user-images.githubusercontent.com/38899097/46899696-0efcd880-cec9-11e8-8766-c806538ebb4e.png)

外部复制的图片会在img外嵌套一层div  导致原来其父元素的p标签所带的样式在img中失效

**Comment by margox** [comment]
因为这个编辑器本身不是基于html进行编辑的，而是基于draftjs内建的editorState，在将外部复制的html转换成editorState的时候，实际上是用的近似穷举转换的办法，所以不能完全保留外部样式，基本上以目前的转换器的功能，只能保留例如文字颜色、字号等简单的样式
