### ISSUE TITLE
type is invalid

### ISSUE THREAD

**Issue by chuanshuogod** [margox/braft-editor#254]
> type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `TextAlign`.

**Comment by margox** [comment]
请掌握科学的提问方式，比如你用的什么版本，使用的代码是怎样的，是做什么操作的时候出现的这个问题？ 不然的话我还要主动向你询问具体情况，大家的时间都是宝贵的，对吧
