### ISSUE TITLE
希望增加个首行缩进功能

### ISSUE THREAD

**Issue by FxSunshine** [margox/braft-editor#257]
文章的排版的话，需要首行缩进，所以。。。emmmm ，希望有一个吧

**Comment by margox** [comment]
你用的什么版本？ 现在新版本已经加入了段落缩进功能了的。

**Comment by FxSunshine** [comment]
1.9.8 版本呢

**Comment by margox** [comment]
😯，1.x已经是旧版本了，已经停止维护了，现在的版本是2.1.x，功能更多，但是用法和1.x有很大的差别
新版文档：https://www.yuque.com/margox/be/lzwpnr
新版演示：https://braft.margox.cn/demos/basic

**Comment by FxSunshine** [comment]
好的 谢谢啦




| |
xresponsibility
邮箱：xresponsibility@126.com
|

Signature is customized by Netease Mail Master

在2018年10月18日 14:35，超能刚哥 写道：

😯，1.x已经是旧版本了，已经停止维护了，现在的版本是2.1.x，功能更多，但是用法和1.x有很大的差别
新版文档：https://www.yuque.com/margox/be/lzwpnr
新版演示：https://braft.margox.cn/demos/basic
