### ISSUE TITLE
无法粘贴表格

### ISSUE THREAD

**Issue by powerProgrammerMa** [margox/braft-editor#258]
表格粘贴进来后没有格子

**Comment by margox** [comment]
编辑器暂时还不支持表格功能

**Comment by powerProgrammerMa** [comment]
后续会考虑加入此功能吗？   比较富文本主要体现在富字

**Comment by powerProgrammerMa** [comment]
不过这个是目前我觉得结合react使用最好的例子了 哈哈 感谢作者 ！  如果能支持表格就好了。

**Comment by margox** [comment]
恩，表格功能会是2.2版本的核心计划，因为draft-js底层的原因，实现表格功能工作量会比较大，所以也不能确定具体的上线时间
