### ISSUE TITLE
react 15.x中报错

### ISSUE THREAD

**Issue by jimshute** [margox/braft-editor#259]
https://reactjs.org/docs/error-decoder.html/?invariant=109&args[]=TextAlign

**Comment by margox** [comment]
已确认，因为在某些组件中使用了React16独有的特性，比如在render中返回了一个Component数组，导致的此问题，会在下一个小版本中回退处理一下。

**Comment by margox** [comment]
你升级到2.1.17试试

**Comment by jimshute** [comment]
好的，真是灰常感谢呀！

**Comment by margox** [comment]
@jimshute 升级之后问题能正常使用了咩？

**Comment by jimshute** [comment]
可以了可以了，太给力了！
