### ISSUE TITLE
定义onHTMLChange钩子函数，输入文本时会报Uncaught Error: block is not a BlockNode

### ISSUE THREAD

**Issue by dovakinlink** [margox/braft-editor#26]
从在线demo拷贝的代码 http://margox.github.io/braft-editor/
本地运行时，在文本区域输入文本会报错：
Uncaught Error: block is not a BlockNode

![image](https://user-images.githubusercontent.com/7587459/35193142-a1f2fdce-fed9-11e7-9c7c-3f0cc48d37d0.png)

不知道是不是我改什么东西导致的，有人遇到类似的情况吗

`import React from 'react'
import { connect } from 'dva'
import { routerRedux } from 'dva/router'
import BraftEditor from 'braft-editor'
import 'braft-editor/dist/braft.css'

class Editortest extends React.Component {

  state = {
    htmlContent: ''
  }

  render() {

    const editorProps = {
      placeholder: 'Hello World!',
      initialContent: '',
      onHTMLChange: this.handleHTMLChange,
      viewWrapper: '.demo',
      // 增加自定义预览按钮
      extendControls: [
        {
          type: 'split',
        },
        {
          type: 'button',
          text: '预览',
          className: 'preview-button',
          onClick: () => {
            window.open().document.write(this.state.htmlContent)
          }
        }, {
          type: 'dropdown',
          text: <span>下拉菜单</span>,
          component: <h1 style={{width: 200, color: '#ffffff', padding: 10, margin: 0}}>Hello World!</h1>
        }, {
          type: 'modal',
          text: <span style={{paddingRight: 10,paddingLeft: 10}}>弹窗</span>,
          className: 'modal-button',
          modal: {
            title: '这是一个弹窗',
            showClose: true,
            showCancel: true,
            showConfirm: true,
            confirmable: true,
            onConfirm: () => console.log(1),
            onCancel: () => console.log(2),
            onClose: () => console.log(3),
            children: (
              <div style={{width: 480, height: 320, padding: 30}}>
                <span>Hello World！</span>
              </div>
            )
          }
        }
      ]
    }

    return (
      <div className="demo">
        <BraftEditor {...editorProps} />
      </div>
    )

  }

  handleHTMLChange = (htmlContent) => {
    this.setState({ htmlContent })
  }

}
   
export default connect(({ editortest }) => ({ editortest }))(Editortest)`

**Comment by margox** [comment]
我这边没有碰到过这个问题，麻烦告知下你用的是哪个浏览器呢？ 以及package.json的内容贴一下，我看一下版本号

**Comment by dovakinlink** [comment]
Chrome浏览器 版本 63.0.3239.132

package.json如下： 

`{
  "name": "dovakin",
  "version": "0.0.1",
  "description": "Base on React.js、Ant Design、dva.js、roadhog",
  "dependencies": {
    "antd": "2.12.2",
    "axios": "^0.16.2",
    "backdraft-js": "0.0.1",
    "braft-editor": "^1.1.10",
    "classnames": "^2.2.5",
    "draft-js": "^0.10.4",
    "draft-js-export-html": "^1.2.0",
    "dva": "^1.2.1",
    "dva-loading": "^0.2.1",
    "echarts-for-react": "^1.4.4",
    "google-map-react": "^0.24.0",
    "hommilyeditor": "^3.2.3",
    "js-cookie": "^2.2.0",
    "jsonp": "^0.2.1",
    "lodash": "^4.17.4",
    "marked": "^0.3.9",
    "moment": "^2.18.1",
    "nprogress": "^0.2.0",
    "object-to-formdata": "^1.0.13",
    "react": "^15.6.1",
    "react-cookie": "^2.0.8",
    "react-countup": "^2.1.1",
    "react-dom": "^15.6.1",
    "react-quill": "^1.0.0",
    "react-router": "^4.1.2"
  },
  "devDependencies": {
    "atool-build": "^1.0.0",
    "babel-eslint": "^7.2.3",
    "babel-plugin-dva-hmr": "^0.3.2",
    "babel-plugin-import": "^1.2.1",
    "babel-plugin-module-resolver": "^2.7.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.23.0",
    "babel-register": "^6.24.1",
    "babel-runtime": "^6.23.0",
    "eslint": "^3.9.0",
    "eslint-config-airbnb": "^12.0.0",
    "eslint-plugin-import": "^2.0.1",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.4.1",
    "less-vars-to-js": "^1.1.2",
    "mockjs": "^1.0.1-beta3",
    "npm-run-all": "^4.0.2",
    "redbox-react": "^1.4.3",
    "roadhog": "^0.6.0",
    "sweetalert2": "^6.6.6"
  },
  "scripts": {
    "start": "roadhog server",
    "lint": "standard src/**/*.js",
    "build": "roadhog build"
  }
}
`

**Comment by margox** [comment]
不知道是不是和react-quill有冲突了，能麻烦通过开发者工具定位一下具体的出错位置么？ 这个调试和定位问题的过程可能会比较复杂

**Comment by dovakinlink** [comment]
我uninstall了react-quill，已经可以了，果然是冲突问题，谢谢！

**Comment by margox** [comment]
哈哈，解决就好，多谢支持
