### ISSUE TITLE
这个编辑器考虑支持markdown吗?

### ISSUE THREAD

**Issue by mr-ant** [margox/braft-editor#263]
这个编辑器会考虑支持markdown吗?毕竟现在越来越多的人开始接受markdown了!

**Comment by xoptimal** [comment]
十分期待支持 markdown~

**Comment by margox** [comment]
> 十分期待支持 markdown~

试试这个：[Markdown语法支持模块](https://github.com/margox/braft-extensions#markdown%E8%AF%AD%E6%B3%95%E6%94%AF%E6%8C%81%E6%A8%A1%E5%9D%97)
