### ISSUE TITLE
第一行文字挂url直接获取Html没有内容

### ISSUE THREAD

**Issue by cycle07** [margox/braft-editor#265]
如标题，如果当前页面只有一行文字并且添加url，不换行的情况下输出的Html没有内容。

**Comment by margox** [comment]
用的是什么版本？ 控制台有没有出现报错或者警告信息呢？ https://braft.margox.cn/demos/basic 我在这个演示里面尝试了一下好像没有出现这个问题

**Comment by cycle07** [comment]
2.1.3的版本，需要当前没有任何内容只有一行p标签文本，挂载链接点击确定的那一次onChange拿到的editorState，通过toHTML()拿不到任何内容。

**Comment by margox** [comment]
升级一下试试，另外看看控制台有没有出现警告信息什么的

**Comment by cycle07** [comment]
这里尝试了2.1.25的版本问题依旧存在，触发问题时会有一个`Cannot read property 'getCurrentStack' of undefined`的warn。

**Comment by margox** [comment]
这个问题的原因，应该是你使用了webpack的dll插件，并且react和react-dom加入到了dll的名单里面，你试试把react-dom/server也加进去，或者在webpack里面加入下面的alias配置：
```js
{
  'react-dom/server': path.join(__dirname, 'node_modules', 'react-dom/dist/react-dom-server.js')
}
```

**Comment by margox** [comment]
加入到了dll配置名单里面的npm包，在引入的时候实际上是引入的压缩(production)版本，本项目用到了react-dom/server里面的一个方法，开发版本的react-dom/server依赖了开发版本的react的一些功能用于debug，所以在开发版本的react-dom/server + 压缩版本的react一起用，就会有问题，解决办法就是上面说的，要么把react-dom/server也加入到dll的策略里面，要么直接通过alias来强制引用dist版本的react-dom/server

**Comment by cycle07** [comment]
补充一下描述：页面初始化后输入内容后第一次使用涉及到Selection的控件必定会触发这个warn，之后有改变Selection位置的操作会正常输出。

**Comment by margox** [comment]
https://braft.margox.cn/demos/basic 你看一下在官网的演示中能不能重现？

**Comment by cycle07** [comment]
是这里编译环境的问题，我们默认全局是cdn引入react-dom的production版本，本地又一次安装了module造成了开发版本和production版本混用的情况，后续这里再想办法吧，多谢大佬帮忙XD

**Comment by margox** [comment]
好的👌
