### ISSUE TITLE
自动清除空格字符&nbsp

### ISSUE THREAD

**Issue by skycsky** [margox/braft-editor#266]
html如下：
`<span style="mso-spacerun:'yes';font-family:微软雅黑;color:rgb(0,0,0);letter-spacing:0.0000pt;text-transform:none;font-style:normal;font-size:14.0000pt;mso-font-kerning:0.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);">
<font face="微软雅黑">住所地</font>/住址：
</span>
<u>
<span style="mso-spacerun:'yes';font-family:微软雅黑;color:rgb(0,0,0);letter-spacing:0.0000pt;text-transform:none;text-decoration:underline;text-underline:single;font-style:normal;font-size:14.0000pt;mso-font-kerning:0.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>
</u>`

EditorState.createFrom生成后：
![image](https://user-images.githubusercontent.com/23150957/47293279-3f1c4800-d63c-11e8-8415-511b78df4ae3.png)

主要问题是，我这个是为了显示下划线，现在下划线没有了

**Comment by margox** [comment]
这个问题实际上是由于draft-convert里面的某个trim过滤导致的，连续的空格会被合并导致无效，具体参见： https://github.com/HubSpot/draft-convert/blob/master/src/convertFromHTML.js#L305
在我这边暂时还没办法处理

**Comment by margox** [comment]
因为这个编辑器并不是基于html进行编辑的，实际上是基于draftjs的editorState，外部html传入编辑器的时候都需要进行转换，而这个转换过程类似于穷举，就是把所有可能符合规则的标签、样式名之类的进行分类再生成对应的editorState，所以转换率实际上是很低的，望理解
