### ISSUE TITLE
选中文字后点击其他地方无法取消选中

### ISSUE THREAD

**Issue by ktlshy** [margox/braft-editor#269]
![test](https://user-images.githubusercontent.com/22963407/47402047-52cbc980-d776-11e8-920b-154afcde2231.gif)

选中文字后  点击其他地方 选中的文字 没有取消选中   ，不知是否是其他地方的样式或者事件干扰了

**Comment by ktlshy** [comment]
2.1.18

**Comment by margox** [comment]
https://braft.margox.cn/ 官网貌似没有重现这个问题，你先检查一下有么有别的地方干扰了事件哈

**Comment by ktlshy** [comment]
确实是有地方的事件干扰了哈   具体还在排查  这个内部具体 是用什么事件实现的呢

**Comment by margox** [comment]
这个就跟一个input标签一样的，选中一段文字，再点击别的地方，释放选区，这是浏览器的基本行为，但是如果有地方在mousedown里面preventDefault或者做了其他类似的处理的话，就会导致这个行为失效

**Comment by ktlshy** [comment]
万分感谢！ 是引用的一个库 在mouseup 中使用了  preventDefault   💔
