### ISSUE TITLE
发现了个段落首行缩进的问题

### ISSUE THREAD

**Issue by Downsview** [margox/braft-editor#27]
不知道算不算是问题哦，我想段落缩进，然后在每个段落首行敲了两个字符的空格，但预览的时候没有缩进效果

**Comment by margox** [comment]
首行缩进可以使用CSS去控制，例如text-indent: 2em; 编辑器里面输入的实际上是普通的空格字符，在HTML里面连续的空格在显示的时候默认只会显示一个
