### ISSUE TITLE
希望能加入“限制输入文本字符个数”的功能，如：maxLength 属性

### ISSUE THREAD

**Issue by gh-xiaoxiao** [margox/braft-editor#273]
希望能加入“限制输入文本字符个数”的功能，如：maxLength 属性，可在右下角或右上角等提示“还可输入多少个字符”。

**Comment by margox** [comment]
编辑器自身不支持maxLength属性，因为处理起来比较繁琐而且会对性能有一定影响，因此将这个功能放到了braft-extensions中实现，按需选用即可，请查看[[输入字数限制模块]](https://github.com/margox/braft-extensions#%E8%BE%93%E5%85%A5%E5%AD%97%E6%95%B0%E9%99%90%E5%88%B6%E6%A8%A1%E5%9D%97)。
