### ISSUE TITLE
粘贴的图片不支持转换为base64吗？

### ISSUE THREAD

**Issue by udoless** [margox/braft-editor#274]
![image](https://user-images.githubusercontent.com/7005788/47514976-3a61c900-d8b4-11e8-9a9c-52a09330952f.png)
 现在看粘贴的图片是这种地址，请问如何配置？

**Comment by margox** [comment]
braft-finder强制更新到0.0.14试试，之前的版本，小于1280*800的图片都是直接生成的blob对象，现在统一都生成base64了。另外最好配置一下uploadFn让图片传到服务器，不然文章里面嵌入base64会给数据库很大压力，展示的时候前端加载也会非常慢

**Comment by udoless** [comment]
恩恩，感谢，内部系统使用，不打算做这么麻烦了，所以就采用base64方式了
