### ISSUE TITLE
编辑器的高度无法设置

### ISSUE THREAD

**Issue by gh-xiaoxiao** [margox/braft-editor#275]
编辑器的高度无法设置，如果通过 style 来强行设置，或者在 组件的 外围包一层 div，再设置 div 的高度，那么样式将出现错误，超出的内容将溢出到编辑器下边的外面去。

**Comment by LamTech** [comment]
> 用contentStyle来设置即可

兄弟你倒是说一下怎么设置喂，官网已经直接跳过这里了。在线等，挺急的！
