### ISSUE TITLE
关于 imageControls 的bug

### ISSUE THREAD

**Issue by wingsico** [margox/braft-editor#277]
图片控制工具栏上的图标全部变成了方块，无法显示。

版本 2.0.10

**Comment by margox** [comment]
当前版本最新版本已经到了2.1.21,不妨升级一下试试

**Comment by wingsico** [comment]
> 当前版本最新版本已经到了2.1.21,不妨升级一下试试

升级了是一样的

**Comment by margox** [comment]
确认升级之后的是什么版本？ 到node_modules/braft-editor/package.json里面看下版本号，另外确认升级之后有没有重启
wepback-dev-server之类的

**Comment by margox** [comment]
https://braft.margox.cn/demos/basic 你可以看看在线演示里面有没有这个问题

**Comment by Vincent1993** [comment]
renderers/Image/index.jsx
``` javascript
let { url, link, link_target, width, height, meta } = mediaData
```

实际图片上获取的meta属性是src 你这获取的是 url所以图显示就挂了
![image](https://user-images.githubusercontent.com/7663934/47636559-b2214380-db93-11e8-92d2-1b165feaf8d0.png)

**Comment by margox** [comment]
最近统一都改成了url，把braft-utils，braft-convert都升级到最新版就没问题，但是这个地方的代码和图标显示成方块没有关系的

**Comment by margox** [comment]
不过上面的问题，如果之前存到老数据库里面的是raw格式的数据，大概就会有问题，可能raw里面就是存的src而不是url

**Comment by margox** [comment]
@wingsico  https://github.com/margox/braft-editor/issues/281#issuecomment-434204568 你看看图片工具栏的图片不显示的问题，这样能不能解决

**Comment by wingsico** [comment]
> @wingsico [#281 (comment)](https://github.com/margox/braft-editor/issues/281#issuecomment-434204568) 你看看图片工具栏的图片不显示的问题，这样能不能解决

好的，我试一试

**Comment by wingsico** [comment]
> @wingsico [#281 (comment)](https://github.com/margox/braft-editor/issues/281#issuecomment-434204568) 你看看图片工具栏的图片不显示的问题，这样能不能解决

解决了，我出现的问题和 #281 一样，全局设置了 

```less
* {
  font-family: 'xxx';
}
```

使用以下方式解决：

```less
*:not(.bf-container .bf-media-toolbar a){
  font-family: 'xxx';
}
```
