### ISSUE TITLE
editorState.toHTML()会造成部分信息丢失

### ISSUE THREAD

**Issue by weihomechen** [margox/braft-editor#278]
hi，我遇到一个问题，请帮忙看看，🙏

保存成html或raw格式，获取时使用

```js
// content为保存的内容
const editorState = EditorState.createFrom(content);
const contentHtml = editorState.toHTML();
```

发现经过`toHTML()`转换后，得到的contentHtml会造成部分信息丢失，比如`data-lang`这些，不知道是不是我使用姿势有问题？

![image](https://user-images.githubusercontent.com/16172317/47626700-69ec2c00-db67-11e8-8261-68501bb63a28.png)

![image](https://user-images.githubusercontent.com/16172317/47626788-d0714a00-db67-11e8-8452-8d8414610741.png)

**Comment by margox** [comment]
你是使用了代码高亮扩展模块么？

**Comment by weihomechen** [comment]
嗯，是的

**Comment by weihomechen** [comment]
保存到数据库，再获取时这些信息还在，是经过toHTML后发现丢失了

**Comment by margox** [comment]
我知道了，editorState属性在传入到编辑器组件内部后，编辑器会对这个editorState进行一次setConvertOptions操作，来保证扩展模块里面的转换规则对这个editorState生效，如果editorState不是通过编辑器的onChange获得的话，那转换规则就不会对其生效，这似乎是一个很严重的问题，我尽快解决一下

**Comment by weihomechen** [comment]
@margox  辛苦了，经过`toHTML()`信息不会丢失了。 我想请教一下，得到html后，怎样展示在页面中比较好？ 我使用`react`的`dangerouslySetInnerHTML`发现 `code` 内的 `<br/>` 会被过滤掉，无法实现换行的效果。
比如 
```js
 const editorState = EditorState.createFrom(content);
 const contentHtml = editorState.toHTML();
// contentHtml: <pre data-lang="javascript" class="lang-javascript"><code class="lang-javascript">const a = 1;<br/>const b = 2;</code></pre>
```
在jsx中使用：
```jsx
 <div className={styles.contentContainer} dangerouslySetInnerHTML={{ __html: contentHtml }} />
```

目前效果：
![image](https://user-images.githubusercontent.com/16172317/47634625-23a9c380-db8d-11e8-9f6b-16002804f823.png)

如果手动编辑html，插入<br>，则是期望的效果：

![image](https://user-images.githubusercontent.com/16172317/47634810-bba7ad00-db8d-11e8-8b2b-d28710bb516d.png)

如果您有相关的建议，还望赐教，谢谢

**Comment by weihomechen** [comment]
我就关闭这个issue啦😊
