### ISSUE TITLE
EditorState 这个类怎么引出来，文档中没见介绍。

### ISSUE THREAD

**Issue by gh-xiaoxiao** [margox/braft-editor#279]
想做这样的操作：
在给 BraftEditor 组件赋值前，先用 instanceof 判断值是否属于 EditorState 类，如果不是就通过 BraftEditor.createEditorState(htmlContent) 创建。
但是文档中没见写有怎么导入 EditorState 类，请问该怎么做呢？

**Comment by margox** [comment]
可以按照上面的方式引入，一些文档没有标出来的功能，可以查看源码来了解，而且容易理解其作用

**Comment by gh-xiaoxiao** [comment]
请把这个写到文档介绍里吧，估计挺多人会用到的，谢谢！

**Comment by margox** [comment]
可以
