### ISSUE TITLE
一些图表样式显示不出来！！！

### ISSUE THREAD

**Issue by ningzhenyi** [margox/braft-editor#281]
![image](https://user-images.githubusercontent.com/26025135/47702603-6c7a7e80-dc58-11e8-8356-80c907a61c2c.png)

![image](https://user-images.githubusercontent.com/26025135/47702616-7b613100-dc58-11e8-845d-9efd6c7ab1c5.png)
这是什么原因呢？

**Comment by margox** [comment]
什么版本，什么浏览器，控制台有报错没有？ 审查元素看看是不是被别的样式干扰了

**Comment by ningzhenyi** [comment]
2.1.18  
谷歌浏览器   
控制台没有错误

**Comment by margox** [comment]
审查元素看一下那个颜色按钮，看看样式是不是这样子的：
![image](https://user-images.githubusercontent.com/7866354/47703209-7c935d80-dc5a-11e8-8731-6c3ba33089b6.png)
在我这边么有出现这个问题

**Comment by ningzhenyi** [comment]
和你标红的地方是一样的

**Comment by ningzhenyi** [comment]
![image](https://user-images.githubusercontent.com/26025135/47703398-22df6300-dc5b-11e8-9f9f-1abd461ce802.png)

**Comment by margox** [comment]
额，是windows系统么？ 这个问题是不是必现的？

**Comment by ningzhenyi** [comment]
![image](https://user-images.githubusercontent.com/26025135/47703658-ed874500-dc5b-11e8-8194-fd8674d744f8.png)
这是鼠标悬浮在图片上显示的按钮

**Comment by ningzhenyi** [comment]
我是win10

**Comment by margox** [comment]
图片工具栏上的按钮，貌似是因为font-family被覆盖了，你试试通过下面的css处理一下:
```css
.bf-container .bf-media-toolbar a{
  font-family: braft-icons !important;
}
```
那个颜色图标显示异常的，我晚上回家用windows电脑看看

**Comment by ningzhenyi** [comment]
谢谢

**Comment by ningzhenyi** [comment]
@margox 
我刚才在苹果电脑上试了一下
![image](https://user-images.githubusercontent.com/26025135/47705269-faf2fe00-dc60-11e8-94e4-a1b5c71776ff.png)

**Comment by margox** [comment]
可能是因为引入了别的字体库，然后font-family和编辑器本身的冲突了

**Comment by ningzhenyi** [comment]
*{
  font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Helvetica,PingFang SC,Hiragino Sans GB,Microsoft YaHei,SimSun,sans-serif;
}

因为我的样式有这个css  ，我去掉就好啦。谢谢您花费时间解决这个问题！
