### ISSUE TITLE
增加默认值富文本标签

### ISSUE THREAD

**Issue by qingtaoliu** [margox/braft-editor#283]

**Comment by margox** [comment]
啊？

**Comment by qingtaoliu** [comment]
nextjs 引入如何设置默认的值呀

**Comment by qingtaoliu** [comment]
![image](https://user-images.githubusercontent.com/19529083/47774712-b9c62100-dd28-11e8-9b38-bd4e8462945a.png)
这句话老是报错

**Comment by margox** [comment]
？报什么错

**Comment by qingtaoliu** [comment]
BraftEditor.createEditorState is not a function

**Comment by margox** [comment]
你用的什么版本呐？ createEditorState是2.0.8才增加的方法

**Comment by qingtaoliu** [comment]
不是一个对象，是一个函数

**Comment by qingtaoliu** [comment]
![image](https://user-images.githubusercontent.com/19529083/47775337-55a45c80-dd2a-11e8-8141-856a599d52c0.png)

**Comment by margox** [comment]
那你去google一下dynamic的用法吧，nextjs我也没用过的说

**Comment by yuemenglong** [comment]
老哥解决了没

**Comment by mason-meng** [comment]
我搞定了  https://blog.csdn.net/mengdasheng/article/details/113726981
