### ISSUE TITLE
antd打包报堆栈溢出

### ISSUE THREAD

**Issue by fangkyi03** [margox/braft-editor#284]
"@antv/data-set": "^0.9.4",
    "@antv/g2": "^3.2.7",
    "@antv/g2-plugin-slider": "^2.0.4",
    "antd": "3.10.1",
    "axios": "^0.18.0",
    "babel-plugin-import": "^1.7.0",
    "braft-editor": "^2.1.24",
    "crypto-js": "^3.1.9-1",
    "dva": "^2.3.0",
    "dvajs": "^0.1.8",
    "find-up": "^3.0.0",
    "html2canvas": "^1.0.0-alpha.12",
    "lodash.debounce": "^4.0.8",
    "markdown-it": "^8.4.2",
    "mockjs": "^1.0.1-beta3",
    "moment": "^2.22.2",
    "react": "^16.2.0",
    "react-cookies": "^0.1.0",
    "react-dom": "^16.2.0",
    "react-zmage": "^0.4.0",
    "simditor": "^2.3.21",
    "source-map-support": "^0.5.9",
    "stompjs": "^2.3.3",
    "swiper": "^4.4.1"
  },
  "devDependencies": {
    "babel-plugin-dva-hmr": "^0.3.2",
    "debug": "^4.1.0",
    "eslint": "^4.14.0",
    "eslint-config-umi": "^0.1.1",
    "eslint-plugin-flowtype": "^2.34.1",
    "eslint-plugin-import": "^2.6.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0",
    "gulp": "^3.9.1",
    "gulp-sftp": "^0.1.5",
    "husky": "^0.12.0",
    "qrcode.react": "^0.8.0",
    "redbox-react": "^1.4.3",
    "roadhog": "^2.4.5"
  }
![image](https://user-images.githubusercontent.com/30390014/47838587-cf9c1a80-ddea-11e8-9e59-57b74e38f05e.png)

**Comment by fangkyi03** [comment]
因为加了你这个以后 打包直接从2分钟变成了1小时 然后还一直报这个错误过不去 现在我只要引入了你这个富文本以后就无法打包 去掉就打包正常了

**Comment by margox** [comment]
不用braft-editor就不报错？

**Comment by margox** [comment]
这种问题，还是第一次遇到，你先google一下相关报错看看

**Comment by fangkyi03** [comment]
嗯 把braft-editor去掉打包就只要2分钟 不去掉就半小时到1小时 而且最后还有很大几率报堆栈溢出

**Comment by margox** [comment]
你引入braft editor那部分的代码看看？

**Comment by fangkyi03** [comment]
import BraftEditor from "braft-editor";
import "braft-editor/dist/index.css";
            <BraftEditor
              //className="my-editor"
              controls={controls}
              placeholder="请输入正文内容"
              style={{ border: "1px solid #d9d9d9", height: "200px" }}
            />

**Comment by fangkyi03** [comment]
出问题大概就在import那一行

**Comment by margox** [comment]
先试试不import css 文件，用一下排除法，我这个包也才100多k也不大

**Comment by fangkyi03** [comment]
我用的是官方的roadhog来打包的 我看很多文章有说用dll什么的方式来优化 也不知道写在哪

**Comment by fangkyi03** [comment]
我把css去掉了 发现依旧如此 打包很慢很慢

**Comment by margox** [comment]
roadhog是阿里他们自己的轮子，我没用过，我这边用webpack打包也是很快的，[编辑器官网项目](https://github.com/margox/braft-intro)就是用的webpack，也从没出现过打包方面的问题，你可以去roadhog或者dva官网提个issue看看，最主要是现在也不清楚到底是什么原因阻塞了打包进程

**Comment by fangkyi03** [comment]
换了你那个文件以后 提示index.jsx 找不到 但是因为我用了dva的关系 所以我入口文件不是index.jsx是index.js所以不能直接用 这个要这么解决的

**Comment by margox** [comment]
webpack配置里面你要自己改的，当然不能原封拿来用，但是关于webpack的配置，如果之前没接触过的话，一下子很难搞懂，只能通过查看webpack的[文档](https://webpack.js.org/concepts/)然后配合google一点点摸索才行

**Comment by fangkyi03** [comment]
改成使用script的方式来移植了 放弃npm的方式了 也从roadhog直接迁移到了webpack 原来index.js打包以后有将近6M现在只有600k 速度快了很多 而且我还发现用roadhog 如果你required了一个很大的json 他貌似会当做一个js去解析 导致内存溢出 在roadhog里面提了issue也没人理 我也随便了

**Comment by margox** [comment]
换成webpack的话，可以折腾的点就很多了，很灵活，而且有问题的话google一般也能搜索到解决方法，因为生态圈要比roadhog大很多，另外用了webpack，再用npm应该就没有那么多坑了吧

**Comment by chjiyun** [comment]
@fangkyi03   可以分享下你的webpack配置吗，我也有同样的问题，生产服务器 直接打崩了，3G内存都不管用。

**Comment by chjiyun** [comment]
@fangkyi03   只有600多K有点不可思议啊，我们项目光插件就10M，整体压缩后6M，gzip后1.7M。

**Comment by fangkyi03** [comment]
![image](https://user-images.githubusercontent.com/30390014/53384701-ca289880-39b6-11e9-8bf6-64ca2c4399a5.png)
关注的应该是这个main文件 其他都是按需加载的
