### ISSUE TITLE
插入图片后回车会报错，还有往媒体库中插入初始化图片没有缩略图这个怎么解决

### ISSUE THREAD

**Issue by DavidTina** [margox/braft-editor#29]

**Comment by margox** [comment]
能贴一下报错信息以及你调用的代码么？ 另外你用的是哪个版本？

**Comment by DavidTina** [comment]
![default](https://user-images.githubusercontent.com/9649392/35257547-e74d0ad4-0034-11e8-8892-593787b7802e.png)
![default](https://user-images.githubusercontent.com/9649392/35257548-e782a694-0034-11e8-8ab7-3a8175ac0cf8.png)
 "braft-editor": "^1.1.11",

**Comment by margox** [comment]
你的draft-js是什么版本？ 贴一下package.json看看？

**Comment by DavidTina** [comment]
"devDependencies": {
    "babel-plugin-import": "^1.6.2",
    "husky": "^0.14.3",
    "lint-staged": "^4.3.0",
    "node-sass-chokidar": "^0.0.3",
    "npm-run-all": "^4.1.1",
    "prettier": "^1.7.4",
    "react-app-rewire-less": "^2.0.7",
    "react-app-rewired": "^1.3.3",
    "react-scripts": "1.0.14"
  },
  "dependencies": {
    "antd": "^3.0.0",
    "antd-mobile": "^2.1.3",
    "axios": "^0.17.0",
    "braft-editor": "^1.1.11",
    "draft-js": "^0.10.5",
    "polyfill": "^0.1.0",
    "prop-types": "^15.6.0",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-loadable": "^5.3.1",
    "react-redux": "^5.0.6",
    "react-router-dom": "^4.2.2",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-promise-middleware": "^5.0.0",
    "redux-thunk": "^2.2.0"
  },

**Comment by margox** [comment]
好奇怪，我安装和你一样的依赖版本也没这个问题，能看一下你是怎么调用编辑器的么？ 还有是如何插入图片到媒体库的？

**Comment by margox** [comment]
另外问一下，你用的是哪个浏览器？

**Comment by margox** [comment]
插入图片到媒体库，是我的锅，文档里面没写全，应该这样插入：
```
mediaLibrary.addItem({
  id: libraryId,
  type: 'IMAGE',
  name: 'Foo',
  url: 'http://path/to/image',
  thumbnail: 'http://path/to/thumbnail'
})

```

**Comment by DavidTina** [comment]
嗯，是这样的。就是从媒体库插入图片到内容输入区然后在图片的后面按下回车键会报错。mediaLibrary.addItem({
  id: libraryId,
  type: 'IMAGE',
  name: 'Foo',
  url: 'http://path/to/image',
  thumbnail: 'http://path/to/thumbnail'
})
thumbnail是图片缩略图地址吗？我发现这个好像是base64编码的图片

**Comment by margox** [comment]
发布了1.2.0，thumbnail现在应该不是必传的了。报错的问题，你那边是必现的么？ 我这边刚才也出现过一次，后面很难出现了，我明天再争取复现然后解决掉吧
