### ISSUE TITLE
链接功能中的“移除链接”样式问题

### ISSUE THREAD

**Issue by BlackHole1** [margox/braft-editor#291]
移除链接的样式和其他按钮的差别有点过大。如图：
![image](https://user-images.githubusercontent.com/8198408/48392568-df9aef00-e746-11e8-9ccb-311d77489409.png)

**Comment by margox** [comment]
额，这个pr不用做的那么麻烦，去掉边框就行了，你这里应该是外部样式影响到了，默认情况下这个按钮是没有边框的

**Comment by BlackHole1** [comment]
PR以close。issue暂时不关了，留着你这边根据其他样式问题
