### ISSUE TITLE
2.1.27 chrome react + antd 使用braft-editor，图片悬浮工具栏全部无法正常点击

### ISSUE THREAD

**Issue by Pride049** [margox/braft-editor#293]
v 2.1.27 
浏览器  chrome 
react + antd 使用braft-editor

插入图片，鼠标点击或悬浮出现的工具栏里的按钮全部无法正常点击，似乎点击判定有高度偏差，所以点击按钮直接工具栏关闭，无法使用

**Comment by margox** [comment]
升级v2.1.28试试

**Comment by Pride049** [comment]
感谢作者，v 2.1.27的regression已经修好
