### ISSUE TITLE
antd中接入报错 defaultEditorState.setConvertOptions is not a function

### ISSUE THREAD

**Issue by tourze** [margox/braft-editor#294]
![image](https://user-images.githubusercontent.com/13899502/48421242-0f71e300-e797-11e8-96e3-a073ac8124b8.png)
![image](https://user-images.githubusercontent.com/13899502/48421253-14369700-e797-11e8-8ccc-8dd5d0dcee37.png)
![image](https://user-images.githubusercontent.com/13899502/48421273-1d276880-e797-11e8-8036-3311fa7b4df5.png)

**Comment by margox** [comment]
@tourze 来，加群 725634541 一起调试一下

**Comment by sbyps** [comment]
我也出了这个问题

**Comment by margox** [comment]
@sbyps 使用的cnpm还是npm？如果是用的cnpm，那就先remove了再换成npm装一下，如果还不行试试删除node_modules然后全部重装

**Comment by sbyps** [comment]
@sbyps cnpm，yarn也试了

**Comment by margox** [comment]
@sbyps 加群 725634541 一起调试一下

**Comment by tourze** [comment]
参考下：我最初是用cnpm来更新依赖的，最终我删了node_modules重新用npm install更新依赖后解决了这个问题。

**Comment by MessageBoy** [comment]
我用nap install更新依赖后还是一样的报错。很难受

**Comment by margox** [comment]
@MessageBoy 删除node_modules之后完全重装试试

**Comment by margox** [comment]
升级到最新版试试
