### ISSUE TITLE
选中多行数据，输入中文，页面报错

### ISSUE THREAD

**Issue by vonxq** [margox/braft-editor#295]
https://braft.margox.cn  复现步骤：
1. 输入多行数据
2. 选中多行(不要全选，至少留一行)
3. 输入中文
此时页面白屏，控制台报错如下:
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by margox** [comment]
这是一个draftjs的bug，我会在后续的版本中尝试能否解决掉

**Comment by margox** [comment]
@vonxq 刚才发布了v2.1.29,更新一下,另外更新braft-utils到v3.0.6
