### ISSUE TITLE
insertHTML无法按预期工作

### ISSUE THREAD

**Issue by ilanus** [margox/braft-editor#301]
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9ow1p5wqzo)

在执行insertEmoji之后，dom为空
```
insertEmoji = () => {
  this.setState({
    editorState: ContentUtils.insertHTML(
      this.state.editorState,
      '<span class="emoji-mart-emoji"><span style="width:16px;height:16px;display:inline-block;background-image:url(https://unpkg.com/emoji-datasource-apple@4.0.4/img/apple/sheets-256/64.png);background-size:5200% 5200%;background-position:58.8235294117647% 47.05882352941176%"></span></span>'
    )
  });
}
```

**Comment by margox** [comment]
因为这个编辑器是基于draftjs框架的，这个框架内建了一个新的数据类型EditorState，外部HTML转换成editorState时候只能保留少部分的格式，例如字号颜色加粗斜体等，而你代码中的class和background-image、display之类的都不能被保留，除非你自己实现一个自定义的转换器，参考：https://braft.margox.cn/demos/entity

**Comment by ilanus** [comment]
我可以做到: https://codesandbox.io/s/8yzy0r6y9j, 现在的问题是表情符号的复制和粘贴是不可能的。有什么解决方案吗？谢谢

**Comment by margox** [comment]
自定义entity在编辑器内的复制粘贴，之前也尝试过，还没还找到好的解决办法

**Comment by ilanus** [comment]
也许是剪贴板事件，比如Quill编辑器？ 不太确定draft-js，看起来他们试图在粘贴中解决它：https：//github.com/facebook/draft-js/pull/1784

**Comment by margox** [comment]
恩，拦截并修改从编辑器内复制的内容，这是一个可以突破的点，我后面有空的时候可以研究一下，最近的的空余时间太少了

**Comment by ilanus** [comment]
另一个问题，我如何将重点放在textarea上 在insertHTML之后?

**Comment by margox** [comment]
就是说你执行insertHTML之后，想让光标回到编辑器是吧？可以调用编辑器实例的requestFocus方法：
```jsx
// 获取编辑器实例
<BraftEditor ref={instance => this.editorInstance = instance}/>
```
```js
// 在需要的时机调用实例方法
this.editorInstance.requestFocus()
```

**Comment by ilanus** [comment]
谢谢，如果光标在编辑器中并且我正在执行insertHTML，我认为它应该留在那里，顺便说一你打算添加TypeScript吗出口?

**Comment by margox** [comment]
@ilanus ts的事情，同样也要等我空闲下来才行，当然更欢迎大家贡献pr
另外你更新一下2.1.32版本，尝试优化了一下编辑器内粘贴复制的问题，现在可以复制粘贴表情了，不过有个draftjs自身的设计问题，导致必须至少选中2个表情或者1个表情加若干文字，才能正常粘贴
