### ISSUE TITLE
怎么自定义一个本地图像压缩func?

### ISSUE THREAD

**Issue by tent42** [margox/braft-editor#308]
首先非常感谢up主能开源一个如此良心的reac富文本.再次先行谢过.
因无身旁闲银买酒钱,只能妄逞口舌来鼓励.

我的想法是,一来为了减缓服务器io压力,二来对服务器静态文件的布置不是很顺手,所以对img不做上传而转为base64放在数据库中这种方法觉得非常棒.

但是出了一个问题....
我目前的系统 deepin linux   node version 10.9.0 react 16.6.x

我将一张`jpg`或者`png`的文件上传.

字节数大小总是要比原始图像要大...

我昨天在macos上,貌似是要比原始图像要小...

姑且不管系统的问题,我想的需求是,当一张图片开始被上传时,我自己写个函数,获取到图片,然后进行一些压缩算法.然后做其他处理...

我看咱们的官方文档里关于uploadfn的写法,还是通过xrh的回调,如果我独自调用success的话,返回一个{}并不能通过,只会卡在进度条上,即使我独自调用process return一个100.

这个应该如何改写?

**Comment by margox** [comment]
图片压缩完成之后，也有一个地址的吧，不管是dataurl还是啥，你把这个地址传给uploadFn的param.success就行，braft-finder提供了一个压缩图片的方法，可以这样用：
```js
import { ImageUtils } from 'braft-finder'
```
在uploadFn中：
```js
ImageUtils.compressImage(URL.createObjectURL(param.file), 400, 400).then(result => {
  param.success({
    url: result.url,
    width: result.width,
    height: result.height
  })
}).catch(error => {
  param.error()
})
```
compressImage的源码在这里：https://github.com/margox/braft-finder/blob/master/src/utils/image.js

**Comment by tent42** [comment]
非常感谢  :)
