### ISSUE TITLE
紧急问题：行高转换问题，急~

### ISSUE THREAD

**Issue by suanmei** [margox/braft-editor#309]
![dsfs](http://ykimg.alicdn.com/develop/image/2018-12-05/70236f70a5fdd4a9704c7c121f7e740d.png)
这是我的配置，设置了 px 转 rem，发现转换过程中行高转换 rem 有问题。
![dfsf](http://ykimg.alicdn.com/develop/image/2018-12-05/cde79b539de1d5b225a9e2f2d5736a86.png)

能否把 line-height 添加到 p 上，因为 p 有默认的line-height，我想自己写样式覆盖，但是无法预知 p 下面的span 的line-height。而且 line-height 转换也有点问题，line-height: 2 竟然转换成了那么小的 rem

**Comment by margox** [comment]
把行高加到p上面这个有点难做，因为现在的行高用的是draftjs的inlinstyle这个特性，如果要加到p上，就得用blockStyle，这个会对整个段落有影响。
至于转换的问题，你可以在转换函数中判断一下:
```js
const unitExportFn = (value, type) => {
    // 不对纯数字的行高做转换
    if (type === 'line-height' && !isNaN(value)) {
        return value
    }
}
```

**Comment by suanmei** [comment]
不让行高做转换确实可以让 span 的行高正常，但是 p 标签的行高还是有问题。

因为我的诉求是这样的，我在页面中加了类似 flexible.js 的逻辑，使得页面根元素的font-size 根据不同屏幕会有不同的值，比如375的屏幕就是 37.5px，通过你的 unitExportFn 来做 rem 的转换，想实现h5的适配。

比如现在根目录是 37.5 px，你是给 span 添加了 line-height ；但是最外层的 p 元素的line-height默认为1，所以 p 元素的每一行高度最少是 37.5px ，span 每一行的高度影响不了 p 元素每一行的高度（当然，span line-height 足够大超过 p 的行高的话，会把 p 高度撑大）。

而且如果 line-height 是在 外围的话，设置 line-height 的 span 本身行高也是有问题的

![image](https://user-images.githubusercontent.com/19517557/49529814-d807d980-f8f1-11e8-90b2-7f6affad17b3.png)


我现在的方案是 span 全部 display: block

**Comment by suanmei** [comment]
@margox 还有个问题，转 rem 的时候 p 标签的 text-indent 能否改为 rem ，rem 和 em 混在一起样式有点乱
