### ISSUE TITLE
保存数据转换成html上传到服务器，再取回来转换成raw后图片消失了

### ISSUE THREAD

**Issue by weihomechen** [margox/braft-editor#31]
保存成html上传，取回来时将其转换成raw后，赋值给editorProps的initialContent，但是里面的图片消失了；
这个是保存成功后取回的数据
![image](https://user-images.githubusercontent.com/16172317/35257195-d1e8fbb4-0032-11e8-803a-769e3e9152ad.png)

```
// 转换成raw
initEditorState = () => {
    // content是html字符串
    const { content } = this.props;
    const blockHTML = convertFromHTML(content);
    const contentState = ContentState.createFromBlockArray(blockHTML.contentBlocks, blockHTML.entityMap);
    return convertToRaw(contentState);
  }

// 编辑器的配置
    const initialContent = this.initEditorState();
    const editorProps = {
      initialContent，
}

```

初始化后的编辑器，应该是要有图片的（取回的数据是有图片的）：
![image](https://user-images.githubusercontent.com/16172317/35257258-3306b648-0033-11e8-8d7e-cd5fe7d14598.png)

还请帮忙看下，谢谢

**Comment by petitspois** [comment]
@margox

**Comment by margox** [comment]
convertFromHTML还有另外一个调用的方式
```
convertFromHTML(convertConfig)(content)
```
编辑器内部是通过这种方式转的：
```
convertedContent = convertFromHTML(getFromHTMLConfig())(content)
```
你可以看一下[getFromHTMLConfig](https://github.com/margox/braft-editor/blob/master/src/configs/convert.js)这个函数的定义，如果有需要，我后面把这个函数开放出来吧，你这边先试试直接用contentFormat="html"，不用自己转成raw再塞给编辑器，应该是没问题的

**Comment by weihomechen** [comment]
@margox 谢谢哈，我保存的时候用raw保存了，取回来能正常显示。我想问这个编辑器能否隐藏工具栏和设置为不可写（read only），因为我想用它来显示内容（就是显示文章详情，不可编辑）。

**Comment by margox** [comment]
工具栏你可以直接用CSS来隐藏掉，readOnly可以通过editorInstance.setEditorProp('readOnly', true)来实现

**Comment by margox** [comment]
不过这样显示文章详情，成本很高啊，尤其是面向用户的时候，直接展示HTML会有什么别的问题么？

**Comment by weihomechen** [comment]
目前是写一个博客系统给内部用的，可以确保每篇文章都是raw保存的，如果以后接外部文章了再迭代吧，😂😂这个编辑器很赞的说，谢谢🙏

**Comment by margox** [comment]
非常感谢支持，自从几天前我把这个编辑器推荐到antd的社区精选组件之后，issue一个接一个，暴露的问题太多，都快忙不过来了，哈哈

**Comment by margox** [comment]
我比较推荐的做法是数据库里面raw和html各存一份，raw用来保证可编辑下，html用来保证对外友好🤣😜

**Comment by weihomechen** [comment]
@margox  贪心的问一下，能否兼容markdown语法，比如输入`#` 后自动变成一级标题，个人建议而已，文本编辑器本来就是个深坑😄😄，现在已经很棒了！

**Comment by margox** [comment]
后面有精力应该会做，或者别的形式的兼容，毕竟markdown还是很常用的

**Comment by weihomechen** [comment]
@margox  哈哈哈👍可以的

**Comment by margox** [comment]
@weihomechen 前几天发了一个用于转换编辑器内容的独立npm包，你应该能用到
```bash
yarn add braft-convert
```
然后
```javascript
import { convertRawToHTML, convertHTMLToRaw } from 'braft-convert'
```

**Comment by weihomechen** [comment]
@margox 已经get√ thinks😊
