### ISSUE TITLE
文档不全

### ISSUE THREAD

**Issue by 951565664** [margox/braft-editor#310]
我发现这个编译器的功能很强大，整体api设计的很好，尤其是和ant-design的对接，但是我发现了一些文档的是不全的，例如 controls 中应该有个‘’code‘’的key，代表了是否使用代码功能。没有加入文档。

**Comment by MMMzq** [comment]
[这里有全部的controls 的key](https://www.yuque.com/braft-editor/be/gz44tn)

**Comment by youyeke** [comment]
文档更新不可避免的会滞后，可以先直接看代码：
[支持的 controls](https://github.com/margox/braft-editor/blob/d1fc3a857407b9f05de05c632a241e8bd2ec8e08/src/configs/props.js#L4-L12)
[对应的翻译](https://github.com/margox/braft-editor/blob/d1fc3a857407b9f05de05c632a241e8bd2ec8e08/src/languages/zh.js#L10-L54)
