### ISSUE TITLE
切换内联样式时，没有正确清除子元素的同名样式

### ISSUE THREAD

**Issue by Vincent1993** [margox/braft-editor#313]
![image](https://user-images.githubusercontent.com/7663934/49711406-18f94880-fc7a-11e8-87b3-13a1fb1b86af.png)

同一行文本中设置了两个文本的字号大小，然后选中两个同时设置了字号大小

![image](https://user-images.githubusercontent.com/7663934/49711435-34645380-fc7a-11e8-8ec1-4e3abb7451c4.png)

最后转换出来的结果是

``` javascript
[
 {offset: 0, length: 51, style: "FONTSIZE-40"}
 {offset: 39, length: 12, style: "FONTSIZE-20"}
]
```
期望得到的是

``` javascript
[
 {offset: 0, length: 51, style: "FONTSIZE-40"}
 {offset: 39, length: 12, style: "FONTSIZE-40"}
]
```

**Comment by margox** [comment]
是用的哪个版本？

**Comment by margox** [comment]
这个问题已经修复了哈
