### ISSUE TITLE
当包含多个字体大小不一的段落，如果框住全部文本，选择新的字号，中间新段落使用toHtml()生成的html中，新的fontSize样式写在了父元素上，会被子元素的覆盖

### ISSUE THREAD

**Issue by jiayuanfan** [margox/braft-editor#314]
![image](https://user-images.githubusercontent.com/42952978/49789129-2f7cce00-fd66-11e8-83e7-94049dcc5967.png)
![image](https://user-images.githubusercontent.com/42952978/49789175-4ae7d900-fd66-11e8-8028-73e91ec7ad49.png)
![image](https://user-images.githubusercontent.com/42952978/49789205-63f08a00-fd66-11e8-9cb9-e7393f40d436.png)

**Comment by margox** [comment]
升级braft-utils试试
