### ISSUE TITLE
text-indent 希望支持 自定义单位转换

### ISSUE THREAD

**Issue by suanmei** [margox/braft-editor#315]
blockToHTML  目前是写死的 em，但是目前遇到问题 rem 和 em 混用有问题，希望这里能够放开自定义单位转换

**Comment by margox** [comment]
可以试试扩展blockToHTML这个函数:
```jsx
<BraftEditor converts={{blockExportFn: myBlockExportFn}}/>
```
myBlockExportFn会在转换的时候调用，https://github.com/margox/braft-convert/blob/master/src/configs.js#L333，参考下面的textIndent规则

**Comment by suanmei** [comment]
直接用这个函数有点太大了吧，要写的东西太多了，而且很多默认逻辑中用到的方法和变量都没有传进去

**Comment by margox** [comment]
这一块确实可以再完善一下，但是我现在实在是太太太太忙了，所以你这边暂时先按上面的办法搞吧，等我后面有空了把这里再整一下

**Comment by suanmei** [comment]
上面的目前没法用，比如 blocks 变量引用不到，我提交一下 PR，你帮忙发个小版本，可以吗

**Comment by suanmei** [comment]
按理来说，所有的涉及到单位的属性应该都支持自定义转换

**Comment by margox** [comment]
恩，你提交pr，我下班回家了看看
