### ISSUE TITLE
显示编辑器的HTML源代码

### ISSUE THREAD

**Issue by mostearly** [margox/braft-editor#317]
怎么查看编辑好的HTML源码？就像其他编辑器那样有个查看源代码的功能。
或者toHTML能输出带格式的HTML吗？还是得自行处理？

**Comment by margox** [comment]
toHTML拿到的就是带内联格式的HTML源码啊，不然的话编辑器的意义在哪里呢？ 不过因为这个编辑器是基于draftjs的，与传统的富文本编辑器在底层实现上完全不一样，所以基本上没有完美的办法实HTML编辑模式

**Comment by margox** [comment]
这么说吧，draftjs他内部自己实现了一个数据类型EditorState，编辑的时候实际上都是操作的一个EditorState对象，EditorState对象和HTML相互转换，是通过一系列函数来进行转换的，在HTML转换成EditorState的时候，只有这些函数里面声明了的规则才能被转换，但是HTML里面的标签啊内联样式什么的太丰富了，现在只有少部分规则才能转换成功，所以使用HTML编辑模式的话，效果肯定会很差的。

**Comment by margox** [comment]
如果你对这个功能有很强的需求，还是建议采用传统的基于HTML的富文本编辑器

**Comment by mostearly** [comment]
只是预防某些时候编辑或者样式存在某些问题才想把HTML暴露出来

**Comment by margox** [comment]
那你可以试试用一个文本框显示html，在编辑好之后，使用BraftEditor.createEditorState将html转换成EditorState然后回传给编辑器，但是要注意的是BraftEditor.createEditorState生成的是一个全新的EditorState，而编辑器的光标和选区状态都是存储在EditorState里面的，所以将一个全新的EditorState传给编辑器之后，编辑器的光标会回到第一行第一个字符之前的位置。

**Comment by mostearly** [comment]
好的，谢谢你的解答
