### ISSUE TITLE
怎么限制编辑框字符

### ISSUE THREAD

**Issue by mmmaming** [margox/braft-editor#318]

**Comment by margox** [comment]
试试[[字符限制扩展模块]](https://github.com/margox/braft-extensions#%E8%BE%93%E5%85%A5%E5%AD%97%E6%95%B0%E9%99%90%E5%88%B6%E6%A8%A1%E5%9D%97)，不过这个模块也没有考虑到所有的输入情况，所以有些操作导致的文本输入可能不会被限制。
