### ISSUE TITLE
如何禁止粘贴图片标签

### ISSUE THREAD

**Issue by liusaint** [margox/braft-editor#320]
忽略粘贴内容中的图片
从其他页面复制过来的内容，除了包含文字还可能包含图片，这些图片一般都是外域的（可能会有盗链）。此时如果想要忽略图片，即只粘贴文字不粘贴图片。

这个功能怎么实现呢。   img标签是可以粘贴的。  我设置了
```
 media:{		
       pasteImage: false,
		externals: {
			image: false,
			embed: false,
		},

}
```
不能实现忽略图片。  主要是那种从其他网页复制过来的图片标签。特别是带有文字内容一起复制过来的情况

**Comment by margox** [comment]
```jsx
// 定义一个粘贴处理函数
const pastedTextHandler = (text, html, editorState, editor) => {

  if (html) {
    // 如果粘贴内容中有html，那么则过滤掉其中的外部img标签
    // 注意stripExternalImages方法需要你们自行实现
    const htmlWithoutExternalImages = stripExternalImages(html)
    // 将处理好的html内容插入到编辑器
    editor.setValue(ContentUtils.insertHTML(editorState, htmlWithoutExternalImages, 'paste'))
    // return一个'handled'字符串来表示此次粘贴行为已经处理好了，否则编辑器会按它自己的逻辑去处理
    return 'handled'
  }

}

// 将粘贴处理函数传给编辑器
<BraftEditor handlePastedText={pastedTextHandler} />
```

**Comment by liusaint** [comment]
> ```js-jsx
> // 定义一个粘贴处理函数
> const pastedTextHandler = (text, html, editorState, editor) => {
> 
>   if (html) {
>     // 如果粘贴内容中有html，那么则过滤掉其中的外部img标签
>     // 注意stripExternalImages方法需要你们自行实现
>     const htmlWithoutExternalImages = stripExternalImages(html)
>     // 将处理好的html内容插入到编辑器
>     editor.setValue(ContentUtils.insertHTML(editorState, htmlWithoutExternalImages, 'paste'))
>     // return一个'handled'字符串来表示此次粘贴行为已经处理好了，否则编辑器会按它自己的逻辑去处理
>     return 'handled'
>   }
> 
> }
> 
> // 将粘贴处理函数传给编辑器
> <BraftEditor handlePastedText={pastedTextHandler} />
> ```

非常感谢！
