### ISSUE TITLE
怎么移除编辑器里自带的表情，不让webpack打包

### ISSUE THREAD

**Issue by airfisher** [margox/braft-editor#323]
![default](https://user-images.githubusercontent.com/22497287/50213165-c75a6780-03b7-11e9-8ed1-898984a958fa.png)
麻烦请教一下，我的前端代码需要打包上传到后端的mysql里，但是mysql不支持存储这种表情！！
有没有办法在使用webpakc构建的时候直接忽略掉这些表情？
请问这种情况能解吗？
如果有解答 非常感谢

**Comment by margox** [comment]
额，你们数据库的字符编码改成utf8就行了吧，如果不好改，那你就先fork一下这个项目，然后把源码里面的这个emojis数组改成空的就行，再不然你就直接把braft-editor/dist/index.js里面的这个数组清空也行
