### ISSUE TITLE
图片不显示

### ISSUE THREAD

**Issue by ibmsoft** [margox/braft-editor#325]
![image](https://user-images.githubusercontent.com/26042/50219905-9dab3b80-03cb-11e9-9bc4-3ee199c63dd5.png)

把本插件集成到 ant design pro 中，参考列子显示已经上传的图片，如图，显示不出来

**Comment by margox** [comment]
1:审查元素看看这个图片列表里面的图片的src是什么
2:看看setItems里面传入的数据的url是不是有效值
