### ISSUE TITLE
初始化问题

### ISSUE THREAD

**Issue by Invincible-Keen** [margox/braft-editor#33]
请问怎么设置初值，我看到content是个对象
{
    blocks: [],
    entityMap: {}
}

但是有没有提供一个吧html转换成这种content的方法用以初始化呢?

**Comment by margox** [comment]
额，contentFormat设置为'html',就可以直接把html字符串传给initialContent属性了：
```javascript
const editorProps = {
  initialContent: '<p>hello world!</p>',
  contentFormat: 'html',
  onHTMLChange: this.handleChange,
}
```

**Comment by Invincible-Keen** [comment]
哦 我看说明开始就强烈建议raw格式  如果用html格式 会有什么影响呢?

**Comment by margox** [comment]
目前来说没有什么影响，下一版本我看能不能加一个自动适配，不用强制指定contentFormat
