### ISSUE TITLE
如何添加附件？

### ISSUE THREAD

**Issue by Dogtiti** [margox/braft-editor#330]
请问一下，如何添加word、excel到编辑器中？
目前支持吗

**Comment by margox** [comment]
编辑器自带的媒体库暂时不支持这些文件，但是你可以集成第三方的上传组件，在上传完之后插入一个超链接到编辑器就行了，可以参考[[集成Ant Design上传组件](https://braft.margox.cn/demos/antd-upload)]，在上传完之后，调用Content.insertHTML来插入内容

**Comment by Dogtiti** [comment]
@margox  好的谢谢
