### ISSUE TITLE
insertHTML的class或者样式丢失

### ISSUE THREAD

**Issue by jsososo** [margox/braft-editor#334]
想问下在insertHTML的时候有什么办法能保留class或者样式嘛

**Comment by margox** [comment]
没有直接的办法，但是可以在braft-convert里面做改动，HTMLToBlock的时候把div上的所有属性都拿出来放到block data里面，然后blockToHTML的时候再将block data里面的数据拿出来附加到div标签上

**Comment by astudentat** [comment]
这个改动是没有更新到最新版吗，木有用捏
