### ISSUE TITLE
使用 extendAtomics 功能, 自定义组件插入 iframe, 鼠标焦点变换,会导致 iframe 重新加载

### ISSUE THREAD

**Issue by Mrwaite** [margox/braft-editor#337]
使用 extendAtomics 功能, 自定义组件插入 iframe, 编辑器插入成功后, 焦点点击非 iframe 区域, ifrmae 会重新 reload, 导致 iframe 闪烁.

具体情况是, 会导致下面一整级的 div 重新加载
![image](https://user-images.githubusercontent.com/13547402/50532747-d9c36680-0b58-11e9-8e80-bb9fa110e71d.png)

**Comment by margox** [comment]
你在你这个自定义组件里面做一下showComponentUpdate控制试试

**Comment by Mrwaite** [comment]
> 你在你这个自定义组件里面做一下showComponentUpdate控制试试

已经在 showComponentUpdate 里面尝试过打断点,但是问题不是组件内部的 props 更新导致组件 rerender, 而是渲染了一个新组件

**Comment by margox** [comment]
就算是编辑器内部的音视频组件，也会有这个问题，因为每次点击编辑器的内容，或者编辑器获得/失去焦点的时候，都会改变editorState，触发onChange。
有个一个可行的方案，你把你的组件独立出来放到一个modal里面，那样它就不属于编辑器的子组件，就不会受到onChange的影响了

**Comment by Mrwaite** [comment]
目前 extendControls 里面的属性,好像只是一个弹窗的功能, 貌似不能实现一个独立组件在编辑器内渲染的功能. 有什么理解上的问题, 请指教
![image](https://user-images.githubusercontent.com/13547402/50532919-56574480-0b5b-11e9-9c37-6ebb8c40f7f0.png)

**Comment by Mrwaite** [comment]
看之前的 issue 里面有个童鞋,实现了单独嵌入 iframe 的功能, 用于腾讯视频的嵌入. 不知道他的那个方案,可行性怎么样,会有上面的资源 reload 闪烁的问题吗?

**Comment by margox** [comment]
children属性可以是你自己的自定义组件，但是编辑器自带的这个modal还是有很多问题，如果你用了antd的话，加个扩展按钮触发显示antd的modal会更舒服

**Comment by Mrwaite** [comment]
@margox 我突然想到, 这个编辑器里面的默认媒体内容插入, 编辑器上只会展示一个占位的媒体资源,只有点击播放按钮的时候才会弹出一个 modal 来播放视频. 
不知道当初你这样设计的时候, 是不是也是对可能多次重新渲染的一个考量.
因为只是一个占位符的话, 重新渲染的影响也不会太大.

**Comment by margox** [comment]
没错，就是因为多次渲染会导致音视频播放器进度归零无法持续播放，所以采用的modal

**Comment by Mrwaite** [comment]
那还有一个问题, 不知道你那边是怎么对 编辑器内的媒体播放方式 和 onChange 输出的真实 html 之间做一个转化呢? 

比如目前编辑器里面插入外部视频会显示下图, 但是 onChange 事件里面转出的是 video 标签.
![image](https://user-images.githubusercontent.com/13547402/50534351-59136300-0b76-11e9-9f43-383fb6504723.png)

非常感谢.

**Comment by margox** [comment]
一个媒体内容对于在编辑器内就是一个block，通过blockRendererFn或者blockRenderMap可以指定block在编辑器内部如何渲染，这都是draftjs自己的一套机制，在输出成html的时候，用到又是另外一个包draft-convert，同样也需要告诉他某个block应该转换成怎样的html

**Comment by Mrwaite** [comment]
哈哈,在看 braft-editor 源码的时候,本来是想新增一个 Iframe 的新 mediaType, 但是发现直接使用 Embed 这个 mediaType 就可以解决 iframe 的问题, 我看 Embed 代码里面就是直接 `<div dangerouslySetInnerHTML={{__html: url}}/>` , 非常符合 iframe 的需求.

还是非常感谢作者的指导!
