### ISSUE TITLE
Uncaught TypeError: Cannot read property 'uploadImage' of null

### ISSUE THREAD

**Issue by zhangfu-git** [margox/braft-editor#344]
从world文档中复制一张图片进去，出现如标题所示的错误。

**Comment by zhangfu-git** [comment]
升级为"^2.2.1"，复制图片到编辑器不报错了，但图片没有复制到编辑器中。请问需要一些而外的配置吗？图片是本地图片非外链

**Comment by margox** [comment]
需要在启用media控件才行，如果你没有在controls属性中启用media的话，粘贴本地图片（包括从word或网页中单独复制的图片）也是没有效果的

**Comment by zhangfu-git** [comment]
非常感谢，可以了

**Comment by wfk007** [comment]
> 需要在启用media控件才行，如果你没有在controls属性中启用media的话，粘贴本地图片（包括从word或网页中单独复制的图片）也是没有效果的

建议在文档中标注一下，我在controls属性中没有启用media，图片死活粘贴不上去！
