### ISSUE TITLE
删除图片的事件回调

### ISSUE THREAD

**Issue by guihouchang** [margox/braft-editor#346]
上传图片后，我现在想在编辑器中删除图片，并且通知后台将资源删除。 请问如何才能监听到删除图片的事件呢？

**Comment by guihouchang** [comment]
找到HookFunc 可以回调， 但是传递过来的是参数是{href: undefined, target: undefined}

**Comment by margox** [comment]
hooks里面的，也只能监听到从媒体库删除图片这个事件，从编辑器内容中删除带图片的内容，没有直接的办法来感知到的。
一个可行的方案是你比较两次onChange中拿到的editorState，从editorState中拿到atomic类型的block，来判断是不是删除了图片。但是这样做的话，撤销和重做功能也没法用了，那还要做别的处理来禁用掉。
另外一个方案是图片传cdn，cdn值钱的是流量，存储量是不要花多少钱的。。。

**Comment by guihouchang** [comment]
> hooks里面的，也只能监听到从媒体库删除图片这个事件，从编辑器内容中删除带图片的内容，没有直接的办法来感知到的。
> 一个可行的方案是你比较两次onChange中拿到的editorState，从editorState中拿到atomic类型的block，来判断是不是删除了图片。但是这样做的话，撤销和重做功能也没法用了，那还要做别的处理来禁用掉。
> 另外一个方案是图片传cdn，cdn值钱的是流量，存储量是不要花多少钱的。。。

👌

**Comment by kenzheng2020** [comment]
从媒体库里删除图片，调用服务器接口删除服务器上文件，到底怎么实现。。。
