### ISSUE TITLE
请问新版编辑器为什么放弃在 modal 中播放 video

### ISSUE THREAD

**Issue by Mrwaite** [margox/braft-editor#348]
我看在 old-master 中 renderers/atomic/video 中 video 是以 modal 方式播放的.
但是在新版编辑器中, video 是直接在编辑器内部播放的,这样做的话,只要修改编辑器内容,就会触发 onChange 事件, video 进度条会一直重置,体验不太好.

请教一下这样做的原因.

**Comment by Mrwaite** [comment]
请问有什么方法可以修改 video block 的渲染吗

**Comment by margox** [comment]
莫慌，我明天发一个版本改成modal播放的

**Comment by Mrwaite** [comment]
> 莫慌，我明天发一个版本改成modal播放的
 Embed 的 Media ,我看老版本也是 modal 方式弹出的, 希望也能同步一下. 感谢

**Comment by margox** [comment]
@Mrwaite 更新一下braft-editor到2.2.2哈，braft-fiinder也更新到0.0.17,音视频和嵌入式媒体，都改成在modal中播放了

**Comment by margox** [comment]
![image](https://user-images.githubusercontent.com/7866354/51035601-766c1680-15e5-11e9-87c4-4d588ca2bc4b.png)

![image](https://user-images.githubusercontent.com/7866354/51035621-871c8c80-15e5-11e9-9570-9d170de1d443.png)

**Comment by Mrwaite** [comment]
使用 ContentUtils.insertMedias 不正常插入 EMBED 媒体了, 不知道是不是修改了 media 的插入方式引起的.
![image](https://user-images.githubusercontent.com/13547402/51073657-720c3000-16af-11e9-80c9-01536e3f1d6e.png)

**Comment by margox** [comment]
你检查一下是不是有多个braft-utils和draft-js被安装了？导致braft-utils里面引用到的EditorState和braft-editor用到的EditorState不是同一个包里面的，导致braft-editor里面对EditorState的一些扩展失效了。

**Comment by Mrwaite** [comment]
> 你检查一下是不是有多个braft-utils和draft-js被安装了？导致braft-utils里面引用到的EditorState和braft-editor用到的EditorState不是同一个包里面的，导致braft-editor里面对EditorState的一些扩展失效了。

感谢,已经找到原因了,是自己的问题, 只设置了 defaultValue ,没有设置 value 的问题.....
