### ISSUE TITLE
图片的toolbar是否可以开放api，用于自定义

### ISSUE THREAD

**Issue by jane900618** [margox/braft-editor#35]
1、图片的toolbar是否可以开放api，用于自定义（例如显示或隐藏某功能，自定义样式）
2、是否考虑图片拖拽功能
3、`media: {
                image: true, // 开启图片插入功能
                video: false, // 开启视频插入功能
                audio: false, // 开启音频插入功能
                uploadFn: this.uploadFn,
                validateFn: this.validateFn,
            },`
在配置中已取消视频和音频的插入功能，但是 图片－添加网络资源 的弹窗仍会有视频和音频，这里是否也可以开放api，用于自定义？
![image](https://user-images.githubusercontent.com/11664758/35452077-60d7d7d0-0300-11e8-90ae-83d35db7e876.png)

**Comment by margox** [comment]
1：图片的toolbar功能自定义可以开放的，这个也很容易实现，后续会加入，感谢建议
2：图片的拖拽具体是指？允许直接拖拽图片到编辑器以插入，还是允许在编辑器中拖拽图片来设置图片位置？前者应该是可以实现的，如果是后者，要考虑的因素实在太多，可能难以实现。
3：网络资源的可用类型的自定义也可以开放的，后续会加入，感谢建议

**Comment by jane900618** [comment]
1和3谢谢回复哈，期待后续
2:没说清楚，不好意思，指的是编辑器内的拖拽，期待可以实现😄

**Comment by margox** [comment]
@jane900618 已发布1.2.0，新增了imageControls属性用来配置图片的工具栏按钮，新增了media.externalMedias属性用来配置可插入的外部媒体类型，具体看README吧
