### ISSUE TITLE
给">>点击此处<<" 设置超链接 toHTML() 后内容不对!

### ISSUE THREAD

**Issue by Zane0816** [margox/braft-editor#353]
应该输出:
`<p><a href="www.baidu,com" target="">&gt;&gt;点击此处&lt;&lt;</a> </p>`
实际输出:
`<p><a href="www.baidu,com" target="">&amp;gt;&amp;gt;点击此处&amp;lt;&amp;lt;</a> </p>`

**Comment by margox** [comment]
感谢反馈，刚刚发布了`braft-convert@2.1.12`版本，你升级下`braft-convert`看看问题还有没有
