### ISSUE TITLE
引入字体文件后，图片编辑的一系列图标全部变成了矩形的“口”

### ISSUE THREAD

**Issue by 52FTT** [margox/braft-editor#357]
看了一下自己定义的字体，并没有把那一块的font-family覆盖掉，这个要怎么解决？

**Comment by margox** [comment]
我这边看是没问题的，你再看看有没有别的原因

**Comment by 52FTT** [comment]
> 我这边看是没问题的，你再看看有没有别的原因

![image](https://user-images.githubusercontent.com/39822342/51289367-d118ce80-1a3a-11e9-8871-3d6065e21d5e.png)

**Comment by 52FTT** [comment]
审查元素是这样的

**Comment by margox** [comment]
https://braft.margox.cn/ 你那边访问一下官网的Demo看看有没有这个问题

**Comment by 52FTT** [comment]
> 审查元素查看样式的时候，样式面板里面还有一个computed标签页，你在那里看一下

问题找到了，a标签里面的span的字体原本是inherit，但是被我不小心定义成了引入的字体，麻烦大神了
