### ISSUE TITLE
上传图片的时候，语言为英文的时候，title为中文‘未选择任何文件’，截图如下

### ISSUE THREAD

**Issue by 52FTT** [margox/braft-editor#358]
![image](https://user-images.githubusercontent.com/39822342/51290287-5f428400-1a3e-11e9-8f84-c3a5882a9edf.png)

**Comment by margox** [comment]
这个title是一个隐藏的input[type="file"]的title，这个文字是浏览器设置的，显示的语言也是根据浏览器设置的语言来的，如果你是给老外做的项目，就不用担心这个问题，这个地方会跟随他们自己浏览器的语言来显示对应提示
