### ISSUE TITLE
toggleSelectionBlockType的疑问？？

### ISSUE THREAD

**Issue by IveChen** [margox/braft-editor#36]
尝试了很多次，toggleSelectionBlockType这个方法好像是改变光标所在区块的区块类型，而不是选中内容的区块类型。。。

有什么方法能做到让选中的内容独立一行么？

**Comment by margox** [comment]
toggleSelectionBlockType其实就是改变光标所在行的区块类型，这个不知道是不是在draft本身就被限制了，抽空我看一下。
现在只能先手动让所需内容独立成一行，再改变区块类型。😅😅😅
