### ISSUE TITLE
wanted  希望作者能点击一次表情 或者点击表情框以外的地方 就能关闭表情包框！！谢谢

### ISSUE THREAD

**Issue by noobzzzz** [margox/braft-editor#360]

**Comment by margox** [comment]
新版本的braft-extensions已经实现了这个功能：https://github.com/margox/braft-extensions#%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8-4
![image](https://user-images.githubusercontent.com/7866354/51309201-d6980800-1a7e-11e9-9610-71d8ecede2e1.png)
