### ISSUE TITLE
使用 ContentUtils 无法完成对应的命令或者其他的任务？

### ISSUE THREAD

**Issue by ChaoshengZhang** [margox/braft-editor#361]
//加粗
ContentUtils.handleKeyCommand(this.state.editorState,'bold')
//改变背景色
ContentUtils.toggleSelectionBackgroundColor(this.state.editorState,'#666666')
//改变字体颜色
ContentUtils.toggleSelectionColor(this.state.editorState,'#47bcc1')       
【使用过程中没有报错】
使用上述方法不能完成对应的命令操作，是我使用方法不对么？
希望作者抽空指正一下。

**Comment by margox** [comment]
ContentUtils是独立于编辑器的模块，它下面的方法大部分都是接受一个editorState，返回一个更新后的editorState，你需要这个返回值重新应用到你的组件的state里去才行，不然不会有任何效果。

**Comment by margox** [comment]
```js
// 需要这样使用才行
this.setState({
  editorState: ContentUtils.toggleSelectionColor(this.state.editorState, '#47bcc1')
})
// 加粗的可以这样用:
this.setState({
  editorState: ContentUtils.toggleSelectionInlineStyle(this.state.editorState, 'BOLD')
})
```
