### ISSUE TITLE
必现问题 enter发送消息之后，再在富文本输入框输入内容按空格，光标 会到第一个字符前

### ISSUE THREAD

**Issue by noobzzzz** [margox/braft-editor#375]
在使用enter发送消息之后，
![image](https://user-images.githubusercontent.com/29473782/51667439-0e60fb80-1ffb-11e9-8eca-ce9f236ab89a.png)
再在输入框输入消息，空格
![image](https://user-images.githubusercontent.com/29473782/51667485-36505f00-1ffb-11e9-85ef-c5a526c4143c.png)
![image](https://user-images.githubusercontent.com/29473782/51667504-410af400-1ffb-11e9-9e90-06fbf3a5a688.png)
会到第一个字符钱 100%重现

**Comment by kirincc** [comment]
@noobzzzz 请问解决了吗？是如何解决的？

**Comment by zhaoqi-nb** [comment]
解决了嘛
