### ISSUE TITLE
鼠标hover到编辑器中的图片，文本内容的编辑焦点消失，在一些历史浏览器中，backspace键会引发网页回退误操作。

### ISSUE THREAD

**Issue by zhaocz2015** [margox/braft-editor#379]
Q:鼠标hover到编辑器中的图片，文本内容的编辑焦点消失，在一些历史浏览器中，backspace键会引发网页回退误操作。

**Comment by margox** [comment]
现代浏览器都没有这个交互了吧？旧版本的浏览器，我这个项目根本就不支持呀

**Comment by zhaocz2015** [comment]
> 现代浏览器都没有这个交互了吧？旧版本的浏览器，我这个项目根本就不支持呀

感谢回复，目前项目 主要使用的是 chrome47 版本，还有按下backspace键位， 网页历史回退功能
> 下面是chrome 52+版本之后，移除了这个功能
> 腾讯科技讯 据多家外媒报道，谷歌(微博)日前对Chrome浏览器进行了升级，结果去掉了一个网民常用的功能，即通过退格键（Backspace）返回到之前浏览的页面。
> 谷歌将浏览器升级到了Chrome 52版本，该版本中已经禁止使用键盘上的退格键。传统上，一些用户利用这一按键退回到刚才浏览的网页。
