### ISSUE TITLE
能否将toHTML相关代码独立出来

### ISSUE THREAD

**Issue by zjy01** [margox/braft-editor#381]
很多情况下，是某个页面或者网站使用富文本编辑，另一个页面或者网站展示对应的富文本美容。
**也就是说 toHTML有独立使用的场景**，不需要带着富文本编辑相关的代码。

希望看能不能独立成一部分模块或者是包。

**Comment by margox** [comment]
editorState.toHTML实际上依赖于braft-convert这个包来实现的，你也可以直接使用这个包，参考：https://github.com/margox/braft-convert/blob/master/src/index.js#L9

**Comment by zjy01** [comment]
> editorState.toHTML实际上依赖于braft-convert这个包来实现的，你也可以直接使用这个包，参考：https://github.com/margox/braft-convert/blob/master/src/index.js#L9

这可能并不是好的办法，相关的options在braft-editor内部，即使将官方的options拷贝一份出来，也可能会因为之后的更新而造成不同步

**Comment by margox** [comment]
就是说你现在存储在后端的是RAW格式的数据，然后在某个页面只需要把这个RAW数据渲染成HTML来展示么？
如果使用了braft-extensions里面的扩展，直接使用braft-convert确实会丢失掉一些内容，除非是把braft-extensions里面的一些规则也传入到braft-convert的方法里面，当然这样做确实是会很麻烦。实际上，在braft-extensions诞生之前是推荐这样做的，但是现在braft-convert还没有对braft-extensions进行友好支持，这个后面有时间会实现一下。
另外一个方案就是后端同时存储RAW格式和HTML格式，一个用于编辑，一个用于展示。

**Comment by margox** [comment]
> 这可能并不是好的办法，相关的options在braft-editor内部，即使将官方的options拷贝一份出来，也可能会因为之后的更新而造成不同步
如果没有使用braft-extensions，这个options实际上就是空的，而如果使用了styleExportFn\unitExportFn\entityExportFn等自定义的转换规则，这些规则也是同样可以传给braft-convert的options参数。

**Comment by zjy01** [comment]
> 就是说你现在存储在后端的是RAW格式的数据，然后在某个页面只需要把这个RAW数据渲染成HTML来展示么？
> 如果使用了braft-extensions里面的扩展，直接使用braft-convert确实会丢失掉一些内容，除非是把braft-extensions里面的一些规则也传入到braft-convert的方法里面，当然这样做确实是会很麻烦。实际上，在braft-extensions诞生之前是推荐这样做的，但是现在braft-convert还没有对braft-extensions进行友好支持，这个后面有时间会实现一下。
> 另外一个方案就是后端同时存储RAW格式和HTML格式，一个用于编辑，一个用于展示。

明白了，谢谢。我把issue关闭
