### ISSUE TITLE
1.9.8版本，上传长图，图片会变模糊

### ISSUE THREAD

**Issue by WayneLu1230** [margox/braft-editor#383]
1.9.8版本，上传长图，图片会变模糊，普通图片正常

**Comment by margox** [comment]
你图片通过你们后端接口上传的么？你把你们后端返回的图片地址在浏览器里面看看是不是被压缩了。

**Comment by WayneLu1230** [comment]
> 你图片通过你们后端接口上传的么？你把你们后端返回的图片地址在浏览器里面看看是不是被压缩了。

在浏览器打开是被压缩了。同一张图片在另外的地方上传没问题，上传图片的接口是一样的，但在富文本这里上传就被压缩了。在富文本编辑器的多媒体上传窗口上传完图片后，预览的图片就已经模糊了

**Comment by margox** [comment]
看下你的uploadFn那里是如何配置的？

**Comment by WayneLu1230** [comment]
> uploadFn

目前没有用uploadFn来上传图片。现在是编辑完全文后，一起再提交的，通过readRawText.entityMap 获取到图片的base64地址，然后再上传图片的

**Comment by WayneLu1230** [comment]
> 看下你的uploadFn那里是如何配置的？

目前没有用uploadFn来上传图片。现在是编辑完全文后，一起再提交的，通过readRawText.entityMap 获取到图片的base64地址，然后再上传图片的

**Comment by margox** [comment]
额，编辑器内置的生成base64，确实是会压缩到一定分辨率内的，如果你的图片很大，还是用uploadFn来上传吧

**Comment by WayneLu1230** [comment]
> 额，编辑器内置的生成base64，确实是会压缩到一定分辨率内的，如果你的图片很大，还是用uploadFn来上传吧

了解了，谢谢。
