### ISSUE TITLE
Link怎么自定义事件

### ISSUE THREAD

**Issue by Mess1ah** [margox/braft-editor#389]
需要给Link生成的a标签自定义绑定事件，简单的a标签href跳转可能无法满足需求=-=

**Comment by margox** [comment]
额，输出的标签上如果加上onclick处理函数，在展示的时候输出带页面之后，这个函数不一定是在你需要的上下文里面执行的。
一个比较可行的办法是，通过在href里面加上特殊的标记，通过事件代理方式监听你这个内容展示的div里面的所有a标签的点击事件，获取到被点击的a标签的href里面的特殊标记，再根据这个标记来执行你自己的业务

**Comment by Mess1ah** [comment]
> 额，输出的标签上如果加上onclick处理函数，在展示的时候输出带页面之后，这个函数不一定是在你需要的上下文里面执行的。
> 一个比较可行的办法是，通过在href里面加上特殊的标记，通过事件代理方式监听你这个内容展示的div里面的所有a标签的点击事件，获取到被点击的a标签的href里面的特殊标记，再根据这个标记来执行你自己的业务

不好意思才回复，您说的是指在href里面执行js嘛，这样也有点不科学呢，不符合W3C的标准呢

**Comment by margox** [comment]
并不是在href里面执行js，而是像这样:
```html
<div class="content" id="content">
  <p><a href="http://www.baidu.com|foo">Hello World!</a></p>
</p>
```
```js
document.querySelector('#content').addEventListener('click', (event) => {
  if (event.target.nodeName === 'a') {
      let value = event.target.href.split('|')[1]
      if (value === 'foo') {
        console.log(123)
        event.preventDefault()
      }
  }
})
```
其实更标准的做法是通过a标签的data-xxx属性来进行判断，但是编辑器现在不支持设置data属性，所以暂时只能通过在href属性中检测特定的值来实现。

**Comment by Mess1ah** [comment]
get~懂了谢谢~

**Comment by Mess1ah** [comment]
明白了~谢谢~
