### ISSUE TITLE
上传图片的时候，选择拖拽文件上传，第一次拖拽有效，第二次拖拽变成浏览器打开图片了

### ISSUE THREAD

**Issue by jane900618** [margox/braft-editor#39]
上传图片的时候，选择拖拽文件上传，第一次拖拽有效，第二次拖拽变成浏览器打开图片了

**Comment by margox** [comment]
确实有问题，下一版解决掉

**Comment by margox** [comment]
发布了1.3.0，拖拽上传这块的问题修复了，后续版本会支持直接拖放媒体文件到编辑器区域，以及直接粘贴图片到编辑器，不过这一块工作量会比较大，不知道具体何时能完成。

**Comment by jane900618** [comment]
灰常感谢，问题已修复👌，期待更完善😊

**Comment by pikeCol** [comment]
依旧有问题，https://braft.margox.cn/demos/custom
