### ISSUE TITLE
关于图片样式的问题，请教一下

### ISSUE THREAD

**Issue by Mess1ah** [margox/braft-editor#390]
图片外层默认包了一层wrapper，有办法让部分图片display：inline-block嘛？

**Comment by Mess1ah** [comment]
感觉是不是这种case做成自定义emoji才是期望的方案呢=-=但是其实这样也会有点奇怪，用float-left也不是很对呢

**Comment by margox** [comment]
如果是想用emoji功能的话，可以试试emoticon这个表情包扩展哦

**Comment by Mess1ah** [comment]
em，我看到了emoticon这个extension呢，不知道图片内联这种场景是不是用emoticon是唯一的实现方法呢

**Comment by margox** [comment]
你可以更深一步研究一下emoticon的实现，它内部是用来draftjs的entity这个特性来实现的，一般来说内联的内容都用entity来实现会比较好。但是也有缺点，你可以自行研究一下。
编辑器当前使用的atomic block来实现的图片和其他媒体内容的插入。

**Comment by Mess1ah** [comment]
好的呢，谢谢
