### ISSUE TITLE
htmlContent 包含 video 标签时，视频不能显示

### ISSUE THREAD

**Issue by chbinghu** [margox/braft-editor#391]
问题：如果 htmlContent 包含 video 标签，编辑中不能显示视频

Demo：https://codesandbox.io/s/0qj47705yp

**Comment by margox** [comment]
目前音视频需要包裹在特定的div里面才能被识别出来，这个特定的div需要有"media-wrap"这个样式名：
```html
<div class="media-wrap"><video src="xxx" controls/></div>
```

**Comment by margox** [comment]
这个issue先开着，我后面会进行一下优化，不然的话对于非BraftEditor生成的历史html数据确实会有问题。

**Comment by chbinghu** [comment]
> 目前音视频需要包裹在特定的div里面才能被识别出来，这个特定的div需要有"media-wrap"这个样式名：
> 
> ```
> <div class="media-wrap"><video src="xxx" controls/></div>
> ```
@margox 感谢回答，我添加了包裹的 div，视频可以显示出来了。点击的时候会弹出一个播放的弹窗。
十分感谢回答！

**Comment by whwnow** [comment]
同样遇到这个问题，请问作者这个问题优化过了么

**Comment by luopeihai** [comment]
我也遇到了这个问题 跪求作者优化

**Comment by zhayes** [comment]
为什么我的视频依然不能显示
![image](https://user-images.githubusercontent.com/17758062/98652001-f85e2f80-2375-11eb-8953-55db7ce72875.png)

**Comment by wxjzeke** [comment]
写一个自定义的扩展：

```js
const parseCustomAudio = {
  type: 'block',

  name: 'AUDIO',

  importer: (nodeName: string, node: HTMLElement) => {
    if (
      nodeName.toLowerCase() === 'audio' &&
      (!node.parentElement || !node.parentElement.classList.contains('audio-wrap'))
    ) {
      return {
        type: 'atomic',
        data: {
          controls: true,
          url: node.getAttribute('src')
        }
      }
    }
  }
}

// 添加扩展
BraftEditor.use([parseCustomAudio])
```

亲测有效
