### ISSUE TITLE
插入图片可以设置默认的style的吗

### ISSUE THREAD

**Issue by yxxhero** [margox/braft-editor#392]
插入图片可以设置默认的style的吗

**Comment by margox** [comment]
默认的宽高是可以设置的，直接传width和height就行，但是浮动和居左居右现在还不可以

**Comment by yxxhero** [comment]
谢谢您的回复 如何实现  我指的是在插入时默认的格式

**Comment by margox** [comment]
在uploadFn里面，调用param的success的时候传入width和height，试试下面的写法：
```js
param.success({
  url: xxxx,
  width: 100,
  height: 100
})
```

**Comment by margox** [comment]
这样从媒体库插入图片的时候，就会默认100x100的尺寸

**Comment by margox** [comment]
另外也可以通过钩子函数，来在图片插入编辑器之前，拦截并修改插入的数据，https://www.yuque.com/braft-editor/be/gz44tn#gug9gs

**Comment by yxxhero** [comment]
非常感谢您
