### ISSUE TITLE
media的items参数问题

### ISSUE THREAD

**Issue by awmleer** [margox/braft-editor#397]
更新到2.2.8之后ts会报错：

> TS2741: Property 'items' is missing in type '{ uploadFn: (param: any) => void; accepts: { video: boolean; audio: boolean; }; }' but required in type 'MediaType'.

```
<BraftEditor
    //...
    media={{uploadFn: uploadFn, accepts: {video: false, audio: false}}}
/>
```

看了下[文档](https://www.yuque.com/braft-editor/be/gz44tn#0hgysg)上好像并没有提及这个items参数的事情啊？

追溯找到这个items的定义是在`index.d.ts`的179行：
```
export type MediaType = {
  items: any[],
  //...
}
```

**Comment by margox** [comment]
尴尬，少了个问号，我现在改改

**Comment by margox** [comment]
发布了2.2.9你更新试试

**Comment by awmleer** [comment]
可以了～非常感谢🙏
