### ISSUE TITLE
代码块内tab键的提议

### ISSUE THREAD

**Issue by atmjs** [margox/braft-editor#40]
在代码块内能否处理下tab键，现在一tab就跳出编辑器了，其实我只是想在代码块内加个tab

**Comment by margox** [comment]
好，下一版看看能不能加上

**Comment by margox** [comment]
发布了1.3.0，现在在代码块内按tab可以插入缩进了，并且可通过tabIndents属性来指定缩进的空格数

**Comment by atmjs** [comment]
@margox 这效率真6 点赞
