### ISSUE TITLE
create-react-app打包出来有没有优化的方法

### ISSUE THREAD

**Issue by ghost** [margox/braft-editor#400]
create-react-app build了一下，分析打包依赖的时候发现 这个模块占了1.2MB 有优化的方法吗

**Comment by margox** [comment]
create-react-app不reject的话，很难去定制webpack吧，这一块得你自己去想办法优化，可以参考[官网源码](https://github.com/margox/braft-intro) 这个打包并启用gzip压缩之后，整个首页请求的js只有200多k
