### ISSUE TITLE
media的Items设置图片alt问题

### ISSUE THREAD

**Issue by katrina-ZhangZiYue** [margox/braft-editor#401]
查看[文档](https://www.yuque.com/braft-editor/be/gz44tn#0hgysg)，没有看到items的设置，想要在设置items时，设置图片的alt属性，如何实现？

**Comment by margox** [comment]
目前还没有主动设置alt属性的输入框组件之类的，但是可以在uploadFn里面调用param.success的时候设置：https://www.yuque.com/braft-editor/be/gz44tn#mupgqt
```js
 const successFn = (response) => {
    // 假设服务端直接返回文件上传后的地址
    // 上传成功后调用param.success并传入上传后的文件地址
    param.success({
      url: xhr.responseText,
      meta: {
        id: 'xxx',
        title: 'xxx',
        alt: 'xxx',
        loop: true, // 指定音视频是否循环播放
        autoPlay: true, // 指定音视频是否自动播放
        controls: true, // 指定音视频是否显示控制栏
        poster: 'http://xxx/xx.png', // 指定视频播放器的封面
      }
    })
  }
```
另外还可以通过钩子函数，在图片从媒体库插入都编辑器的时候，进行设置：
https://www.yuque.com/braft-editor/be/gz44tn#gug9gs

**Comment by katrina-ZhangZiYue** [comment]
好的，但是设置钩子函数insert-medias，它返回的参数是什么呢？

**Comment by margox** [comment]
例如insert-medias函数的参数的数据，原本是[{type: 'IMAGE', url: 'xxx'}]，你拿到这数据处理一下，然后返回一个包含了meta > alt 属性的新数据就行:

**Comment by katrina-ZhangZiYue** [comment]
好的，实现了，非常感谢

**Comment by margox** [comment]
这些地方后面应该可以改成支持异步返回，这样就可以做更多事情了，比如点击插入媒体的时候，弹出一个弹窗要求填写alt之类的
