### ISSUE TITLE
How to add a custom attr on the <video>

### ISSUE THREAD

**Issue by 951565664** [margox/braft-editor#402]
How to add a custom attr on the `<video>`? When user upload a video ,I want to add a attr such as `controlslist="nodownload"` ,This may enable video without download button.

**Comment by 951565664** [comment]
I tried to implement in Hooks，It seems impossible to increase the attr。

**Comment by margox** [comment]
试试下面的钩子函数：
```js
const videoHooks = {
  'insert-medias':  (medias) => {
    return medias.map(item => {
      return item.type === 'VIDEO' ? {
        ...item,
        meta: {
          ...item.meta,
          controlslist: 'nodownload' 
        }
      } : item
    })
  }
}
```

也可在uploadFn中调用param.success时传入这个meta（meta会整个展开然后附加到输出时的video标签上）
另外在html转化为editorState时，还不支持讲video标签上的所有属性存储到meta对象里面来，所以以上办法都只适用于使用RAW数据存储的情况

**Comment by 951565664** [comment]
@margox 是有用的，非常感谢。我关了
