### ISSUE TITLE
为什么要在modal里实现预览的功能？

### ISSUE THREAD

**Issue by 951565664** [margox/braft-editor#403]
为什么要在modal里实现预览的功能？这和我在编辑区域里播放有什么不同？最重要的是，我的视频可能和编辑区中的假视频不一样宽和高，那么在编辑器中展示的样式和实际的样式会有不同。

**Comment by margox** [comment]
因为编辑器内部是一个动态的区域，每次重新render都会导致播放器重置

**Comment by 951565664** [comment]
嗯。视频这个功能有点弱。是否有简单方法接入react-video 或者video.js 等库？

**Comment by margox** [comment]
这个视频在编辑器内也就是展示用，真正在前台显示的时候，你们是可以选用第三方库的
