### ISSUE TITLE
win7 下面表情包全部成为样式黑白

### ISSUE THREAD

**Issue by 951565664** [margox/braft-editor#404]
https://www.tjvantoll.com/2016/06/15/emoji-on-windows/

**Comment by 951565664** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=620419 说是windows8 修复了这个问题

**Comment by margox** [comment]
试试用[表情包扩展模块](https://github.com/margox/braft-extensions/#%E8%A1%A8%E6%83%85%E5%8C%85%E6%89%A9%E5%B1%95%E6%A8%A1%E5%9D%97)，可以使用真正的图片来代替Emoji字符，就不会有问题了

在线演示： https://braft.margox.cn/demos/emoticon
