### ISSUE TITLE
关于image toolbar是否可以自定义的问题

### ISSUE THREAD

**Issue by FontEndArt** [margox/braft-editor#406]
image toolbar是否可以自定义？
有没有直接实现方式
或者是需要自己去重写一个image组件吗

目前我还在翻看源码/笑哭

希望作者解答下，谢谢！

**Comment by margox** [comment]
https://www.yuque.com/braft-editor/be/gz44tn#d7c9zt 看看这个

**Comment by FontEndArt** [comment]
Thank you！ Thank you！  万分感谢
