### ISSUE TITLE
braft-utils中的insertMedias时候设置容器的position

### ISSUE THREAD

**Issue by FontEndArt** [margox/braft-editor#407]
目的：在insertMedias时候设置容器的position

而insertMedias返回的是editorState
setMediaPosition的参数中有一个mediaBlock的参数   不知道该如何去获取

望指一条明路  谢谢

**Comment by margox** [comment]
这个貌似没有直接的办法，看看能不能在下个版本中优化一下insertMedias的传参，支持直接传入position之类的

**Comment by FontEndArt** [comment]
好嘞！辛苦了！！！
我在自己项目中  先暂时屏蔽了媒体组件在编辑器里面的position控件
然后用样式强制调整了image容器的强制居中显示

然后就是video容器的meta: {loop:true, autoplay: true, controls: true}  这三个没有看到应有的效果
准备先把编辑器搞到在这个项目中能用再说
然后参考你的源码   通过编辑器的扩展按钮添加一个自定义播放器的video
