### ISSUE TITLE
媒体-插入图片间隔

### ISSUE THREAD

**Issue by Cockroach-CN** [margox/braft-editor#408]
插入媒体的图片间隔能去掉吗？
![image](https://user-images.githubusercontent.com/22429749/54403634-b6e23080-470b-11e9-9a78-8a9e186f714f.png)

**Comment by Cockroach-CN** [comment]
插入媒体的图片间隔能去掉吗？

**Comment by margox** [comment]
插入的时候没办法去掉，但是在实际展示的时候，是有办法隐藏这个空隙的，参考： #256

**Comment by Cockroach-CN** [comment]
> 插入的时候没办法去掉，但是在实际展示的时候，是有办法隐藏这个空隙的，参考： #256

但是显示的时候需要再web  ios 和andriod同步都显示， 那就需要三个端都改吧...

**Comment by margox** [comment]
你那边，输出的内容是用在APP内嵌的页面里面的么？ https://github.com/margox/braft-editor/issues/241#issuecomment-429534436 那你试试这个看看
