### ISSUE TITLE
设置中文字体切换无效

### ISSUE THREAD

**Issue by DanzedW** [margox/braft-editor#41]
const fontFamilies = [
  {
    name: '黑',
    family: 'SimHei, Helvetica, sans-serif'
  }, {
    name: '宋',
    family: 'SimSun, Helvetica, sans-serif'
  }, {
    name: '楷体',
    family: 'KaiTi, Helvetica, sans-serif'
  }, {
    name: '微软雅黑',
    family: 'Microsoft YaHei , Helvetica, sans-serif'
  }, {
    name: 'Araial',
    family: 'Arial, Helvetica, sans-serif'
  }, {
    name: 'Georgia',
    family: 'Georgia, serif'
  }, {
    name: 'Impact',
    family: 'Impact, serif'
  }, {
    name: 'Monospace',
    family: '"Courier New", Courier, monospace'
  }, {
    name: 'Tahoma',
    family: "tahoma, arial, 'Hiragino Sans GB', 宋体, sans-serif"
  }
]

**Comment by margox** [comment]
切换无效是指在编辑器里面切换没有看到字体变化，还是没有生成预期的HTML？
![image](https://user-images.githubusercontent.com/7866354/35546981-76568cce-05b1-11e8-9336-a5abf498ab1e.png)

**Comment by DanzedW** [comment]
[](url)没有看到字体变化

**Comment by DanzedW** [comment]
@margox 没有看到字体变化，是我写的配置有问题嘛？
import React from 'react'
import BraftEditor from 'braft-editor'
import 'braft-editor/dist/braft.css'
import style from './newEditor.less'

const set = [
  'undo', 'redo', 'split', 'font-size', 'font-family', 'text-color',
  'bold', 'italic', 'underline', 'strike-through','text-align', 'split', 'headings', 'list_ul', 'list_ol',
  'blockquote', 'split', 'link', 'split', 'media'
]

const fontFamilies = [
  {
    name: '黑体',
    family: '黑体'
  }, {
    name: '宋体',
    family: '宋体'
  }, {
    name: '楷体',
    family: 'KaiTi, Helvetica, sans-serif'
  }, {
    name: '微软雅黑',
    family: 'Microsoft YaHei , Helvetica, sans-serif'
  }, {
    name: 'Araial',
    family: 'Arial, Helvetica, sans-serif'
  }, {
    name: 'Georgia',
    family: 'Georgia, serif'
  }, {
    name: 'Impact',
    family: 'Impact, serif'
  }, {
    name: 'Monospace',
    family: '"Courier New", Courier, monospace'
  }, {
    name: 'Tahoma',
    family: "tahoma, arial, 'Hiragino Sans GB', 宋体, sans-serif"
  }
]

class Demo extends React.Component {

  state = {
  }

  render() {
    const editorProps = {
      placeholder: '请填写内容!',
      controls: set,
      fontFamilies: fontFamilies,
      contentFormat: 'html',
      initialContent: this.props.content,
      onChange: this.handleChange,
      onHTMLChange: this.handleHTMLChange,
      viewWrapper: '#demo',
    }

    return (
      <div id="demo" className={style.demo} >
        <BraftEditor {...editorProps} />
      </div>
    )

  }

  handleChange = (text) => {
    this.setState({ text })
  }

  handleHTMLChange = (html) => {
    this.setState({ html })
  }

  getTEXTContent = () => {
    const { text } = this.state
    return text
  }

  getHTMLContent = () => {
    const { html } = this.state
    console.log(html)
    return html
  }

}

export default Demo

**Comment by margox** [comment]
额，你是什么操作系统什么浏览器呢？ 可能是类似SimHei的写法，在你的系统/浏览器上不支持，你试试下面的配置看看:
```javascript
const fontFamilies = [{
  name: '黑体',
  family: 'SimHei, 黑体'
}, {
  name: '宋体',
  family: 'SimSun, 宋体'
}, {
  name: '楷体',
  family: 'KaiTi, 楷体, Helvetica, sans-serif'
}, {
  name: '微软雅黑',
  family: '微软雅黑, Microsoft YaHei , Helvetica, sans-serif'
}]
```

**Comment by margox** [comment]
我这边在OSX + Chrome上跑，还是能正常显示的

**Comment by DanzedW** [comment]
@margox 
![tim 20180130160228](https://user-images.githubusercontent.com/18656919/35554541-02abc49e-05d7-11e8-909d-e48bb07a2fe5.png)
HTML已经设置了样式，网页依旧失效。好像是因为操作系统对于字体的支持不同产生的。截图是OSX + Chrome，不支持黑体，但支持华文黑体。我准备用WebFont解决这个问题

**Comment by margox** [comment]
中文字体转成webfont后体积都比较大，可能用户把一篇文章都已经看完了，字体资源都还没加载完呢。
如果绝大多数用户都是用的windows系统的话，黑体应该是没问题的。
