### ISSUE TITLE
代码错别字

### ISSUE THREAD

**Issue by YufeeXing** [margox/braft-editor#411]
官网首页的demo显示原代码后，<BraftEditor value={this.state.editorSt_s_te}...,最后这个editorStaste

**Comment by dazhi007** [comment]
介绍页面的`README.md`错别字`感谢JackLam提供的繁体中文语言**自持**，Thanks!`,应该是支持,希望这个能支持 中英双语的 README.md

**Comment by margox** [comment]
感谢反馈。已修改
