### ISSUE TITLE
ExtendControls type 'dropdown' isn't closing dropdown menu on selecting a value from dropdown list 

### ISSUE THREAD

**Issue by liadbe** [margox/braft-editor#413]
Hi,

When using `ExtendControls` property:

```javascript
      const componentControl= {
        key: 'control1',
        type: 'dropdown',
        text: 'My Control',
        showArrow: false,
        autoHide: true,
        component: <MyComponent />
      };
```

The issue is when I'm selecting a value from the dropdown list, the list stays open, and I couldn't find how to make it close on selecting a value.
I saw that on built-in dropdown you're using a _Ref_ to the DropDown component and using _hide()_, but that's not available to me (or is it?).

Thanks.

**Comment by margox** [comment]
Hi, thanks for using this editor, there's an undocumented way to get the instance of your custom dropdown component: 
```jsx
const componentControl = {
  key: 'control1',
  type: 'dropdown',
  text: 'My Control',
  showArrow: false,
  ref: instance => this.myDropdownInstance = instance,
  autoHide: true,
  component: <MyComponent />
};

// then you can close the dropdown at any time you want by calling `this.myDropdownInstance.hide()`
```

**Comment by liadbe** [comment]
Tnx!
