### ISSUE TITLE
insertHTML插入table标签渲染出来span

### ISSUE THREAD

**Issue by GRAMMAC1** [margox/braft-editor#414]
版本: 1.9.7
问题描述: 现在有个需求是往编辑器内部插入表格，字符串是`<table data-role="table"><tbody><tr><td>123</td></tr></tbody></table>`
渲染结果是`<span data-text="true">123</span>`，这种现象是正常的吗？如果需要自己手动插入表格应该如何实现呢？ 新版的table拓展不太适合当前场景

希望作者解答一下，谢谢

**Comment by margox** [comment]
1.x的版本不支持表格的，在2.2以后的版本中，也需要使用扩展模块，才能支持简单的表格功能
https://github.com/margox/braft-extensions/

**Comment by GRAMMAC1** [comment]
`ContentUtils`有实现方法可以支持自己拓展渲染的Map类型吗？

**Comment by margox** [comment]
没有，ContentUtils也是2.x才有的东西。
在2.x里面可以自己去扩展renderMap或者rendererFn，参考：
https://braft.margox.cn/demos/block

**Comment by GRAMMAC1** [comment]
在2.x版本中`editorState`有可以合并`State`的方法吗？我试了push和merge都`TypeError`

**Comment by margox** [comment]
具体是指什么操作？EditorState其实就是draftjs的EditorState

**Comment by GRAMMAC1** [comment]
比如说有一个按钮，然后点击按钮的时候手动插入一些内容，这种场景下需要合并`state`

**Comment by margox** [comment]
你是怎么做的? 报TypeError具体是什么错？你可以参考一下[ContentUtils.insertText])(https://github.com/margox/braft-utils/blob/master/src/content.js#L331)的实现哈，也是用的push

**Comment by GRAMMAC1** [comment]
https://codesandbox.io/embed/4x683m2q04

**Comment by GRAMMAC1** [comment]
这里有个demo我是这么写的没有效果

**Comment by GRAMMAC1** [comment]
`TypeError`是说没有`push`和`merge`这个方法

**Comment by margox** [comment]
push是EditorState的静态方法，并不是editorState的实例上的方法哈，https://draftjs.org/docs/api-reference-editor-state#push
