### ISSUE TITLE
使用dynamic引入时，createEditorState方法无法使用

### ISSUE THREAD

**Issue by webzhai** [margox/braft-editor#418]
在next等ssr框架中使用动态引入时使用BraftEditor.createEditorState会报错’BraftEditor.createEditorState is not a function‘

**Comment by fameoflight** [comment]
@webzhai did you find a workaround?

**Comment by finalevil** [comment]
@fameoflight  could you the this code

`let BraftEditor = null
if(typeof window !== 'undefined' && !!window) {
  BraftEditor = require('braft-editor').default
}

class MyComponent extends PureComponent {
  state = {
    editorState: null
  }
  constructor(props) {
    super(props)
  }
  componentDidMount() {
    const htmlContent = 'HTML content'
    this.setState({
      editorState: BraftEditor.createEditorState(htmlContent)
    })
  }
  render() {
    return (
      <BraftEditor value={this.state.editorState} />
    )
  }
}`

**Comment by finalevil** [comment]
@fameoflight  could you the this code

```
let BraftEditor = null
if(typeof window !== 'undefined' && !!window) {
  BraftEditor = require('braft-editor').default
}

class MyComponent extends PureComponent {
  state = {
    editorState: null
  }
  constructor(props) {
    super(props)
  }
  componentDidMount() {
    const htmlContent = 'HTML content'
    this.setState({
      editorState: BraftEditor.createEditorState(htmlContent)
    })
  }
  render() {
    return (
      <BraftEditor value={this.state.editorState} />
    )
  }
}
```

**Comment by heavenlian** [comment]
const RichTextEdit = dynamic(() => import('../../components/common/RichTextEdit'), { ssr: false });
试试这样弄

**Comment by lyxverycool** [comment]
> @fameoflight you can try the this code, I use this code works fine
> 
> ```
> let BraftEditor = null
> if(typeof window !== 'undefined' && !!window) {
>   BraftEditor = require('braft-editor').default
> }
> 
> class MyComponent extends PureComponent {
>   state = {
>     editorState: null
>   }
>   constructor(props) {
>     super(props)
>   }
>   componentDidMount() {
>     const htmlContent = 'HTML content'
>     this.setState({
>       editorState: BraftEditor.createEditorState(htmlContent)
>     })
>   }
>   render() {
>     return (
>       <BraftEditor value={this.state.editorState} />
>     )
>   }
> }
> ```

yes,and May better if 
`
{
          BraftEditor && <BraftEditor
            value={editorState}
            onChange={this.handleEditorChange}
            onSave={this.submitContent}
          />
        }
`

**Comment by mason-meng** [comment]
这个问题我解决了 https://blog.csdn.net/mengdasheng/article/details/113726981
