### ISSUE TITLE
预览页一直loading

### ISSUE THREAD

**Issue by atmjs** [margox/braft-editor#42]
https://github.com/margox/braft-editor/blob/0edf31a30b7eef144936f4a3eb880a056c2bd48d/example/index.jsx#L20

在这后面加上
`window.previewWindow.document.close()` 应该可以解决

**Comment by atmjs** [comment]
哦 看你们官网时候发现预览一直loading 上面那段代码我没有测试 仅供参考

**Comment by margox** [comment]
http://margox.github.io/braft-editor/ 是这个在线DEMO里面的预览么？

**Comment by atmjs** [comment]
点击编辑器里面的预览按钮打开的那个页面

**Comment by atmjs** [comment]
![image](https://user-images.githubusercontent.com/12792057/35555708-01590f3a-05db-11e8-8738-233b0aef1c94.png)
![image](https://user-images.githubusercontent.com/12792057/35555709-048b1694-05db-11e8-8a56-ef29dd7b3157.png)

**Comment by margox** [comment]
恩，这个预览并不是编辑器自带的功能，算是对扩展功能的一个演示，我这边也只是用了最草率的做法，要用在正式项目里的话，肯定需要开发者专门处理一下的。
另外这个在线DEMO的代码在另外一个项目里面，与本项目example目录里面的代码不是同一套。

**Comment by margox** [comment]
其实就一行代码：
```
window.open().document.write(this.state.htmlContent)
```

**Comment by atmjs** [comment]
嗯 明白了

**Comment by margox** [comment]
不过我有时间，还是把这个DEMO的预览优化一下吧，多谢你的建议

**Comment by atmjs** [comment]
哈哈 不用谢我 做开源项目挺累的 应该感谢你给我增加了一个编辑器的选择。
@margox  对你的 braft-editor 以后有没有更多的规划,比如： 图片粘贴上传，从外部粘贴到编辑器中时的格式保留，增加table功能 等等

**Comment by margox** [comment]
图片粘贴上传是会做的，如果时间充足的话，下一个大版本就加进来。
粘贴外部内容保留格式现在已经是可以的了，只不过肯定不会和原样式一致，这个算是draft-js框架的一个软肋，比如编辑器只能用14/15/16这几个字号，那如果复制的内容里面有13号字体，就会丢失掉样式。
table功能如果有精力的而且需求也比较强烈的哈，会研究一下，draft-js本身不支持table，npm倒是有draft-table的插件，不过我看了一下，无论是体验还是功能性上，都太粗糙了。

**Comment by atmjs** [comment]
https://doodlewind.github.io/slate-doc-cn/  可以了解下这个 感觉扩展性很强
