### ISSUE TITLE
Applying style (color, bg-color, font-size) to multiple block types fails

### ISSUE THREAD

**Issue by liadbe** [margox/braft-editor#420]
When trying to apply certain color (or bg-color/font-size) to multiple block types with different colors, it changes the DOM properly (watching with _inspect_) but the editorState which is sent to the onChange method has the new color applied only to the first block, rest of the block are staying with their previous color.

**Comment by margox** [comment]
Hi, I just published a new version of `braft-utils`(v3.0.11) to resolve this issue
