### ISSUE TITLE
图片上传成功后的回调参数不对

### ISSUE THREAD

**Issue by 791045873** [margox/braft-editor#421]
![image](https://user-images.githubusercontent.com/12742472/55138447-7902f480-516e-11e9-972e-d40864957375.png)
如上图所示，成功后的回调的第一个参数是事件对象，并不是response。
代码源自于文档中的代码示例

**Comment by margox** [comment]
额，successFn的参数是什么类型的并不要紧吧，毕竟我也没有直接用到它的参数，示例中的值也是从xhr.responseText拿到的

**Comment by 791045873** [comment]
呃，好像是这样的。。。
