### ISSUE TITLE
Ty is no defined

### ISSUE THREAD

**Issue by BlackEyeByLee** [margox/braft-editor#423]
生产环境 `js` 压缩（ParallelUglifyPlugin）使用 `uglifyJS` 模式会报 `Ty is no defined`。
用了 `uglifyJS` 则不会。
推测是打包后还存在 `es6` 写法。

目前项目执行方案： 生产环境暂时不打包 | `node_modules` 的代码也经过 `babel` 转义后再压缩

**Comment by margox** [comment]
能追踪一下Ty是哪个地方的么？

**Comment by BlackEyeByLee** [comment]
@margox 生产环境不敢再造坑了。昨天排查压缩代码的时候是在一个遍历器里边的 `Ty is no defined` 。也可能是 `npm` 的问题。

**Comment by margox** [comment]
确定是引入了braft-editor之后导致的这个问题吗？不考虑peerDep的话，braft-editor打包出来的JS文件就只有这一个：https://github.com/margox/braft-editor/blob/master/dist/index.js，里面应该是没有ES6的语法了的
