### ISSUE TITLE
可否添加HTML元素到编辑器

### ISSUE THREAD

**Issue by Viin-zx** [margox/braft-editor#425]
请问下作者，能不能添加自定义HTML元素到编辑器中，并且带有自定义属性的?
1. insert `<div id="1" style="width: 10px; height: 10px;" my-attr="myAttr"></div>`
2. insert `<img id="2" src="./a" alt="" style="width: 10px; height: 10px;" my-attr="myAttr"/>`

有没有办法实现类似这样的，主要是能加样式和自定义属性。求教了。

**Comment by margox** [comment]
当前版本没有直接的办法来实现，近期我会完善这一方面的功能，但是什么时间能发布那就不确定了，手头上的事情有点多

**Comment by Viin-zx** [comment]
辛苦了。
那就现在版本来说，能不能间接的基于现有的元素和工具，实现添加自定义属性功能的。

**Comment by margox** [comment]
现有版本可以直接在编辑器中插入自定义的block（React Component），参考：https://braft.margox.cn/demos/block，本质上就是draft-js中的blockRendererFn和blockRenderMap

**Comment by Viin-zx** [comment]
好的，我研究下，感激不尽。

**Comment by Viin-zx** [comment]
@margox 我需要的就是这个东西，官网教程没有展现出来，找了好几天，非常感谢。

**Comment by margox** [comment]
恩，欢迎加QQ群[725634541]来交流哈，一些比较高级的特性和用法，文档和演示里面都还没有

**Comment by lsner** [comment]
> 现有版本可以直接在编辑器中插入自定义的block（React Component），参考：https://braft.margox.cn/demos/block 本质上就是draft-js中的blockRendererFn和blockRenderMap

请问一下支持自定义的嵌套html嘛

**Comment by tony1211** [comment]
项目实践的扩展自定义block，这里有一个最通俗易懂的文章  [链接](https://www.jianshu.com/p/160610edd056)

**Comment by wangzhengbo** [comment]
按键示例中的按钮，光标移过去，可以修改内容。怎么插入一个button或者一个不可编辑内容的inline-block元素到编辑器呢？不能编辑内容，但支持整体删除。类似于插入一个按钮。按钮文本改不了，可以删除。

**Comment by GrayFrost** [comment]
> 恩，欢迎加QQ群[725634541]来交流哈，一些比较高级的特性和用法，文档和演示里面都还没有

请问有插入行内元素组件的示例或教程吗。官网演示的都是块级元素
