### ISSUE TITLE
V1.3.0,tab键没有缩进功能

### ISSUE THREAD

**Issue by 775822253** [margox/braft-editor#43]
今天看到版本更新到V1.3.0，支持tab键缩进  就更新了本地的包，  按tab键依旧没有效果

**Comment by margox** [comment]
缩进只是针对代码块功能，对于普通的文本编辑，暂时没有支持tab缩进功能。
![image](https://user-images.githubusercontent.com/7866354/35604409-19850f30-067d-11e8-91a3-1f18183ecb63.png)

**Comment by margox** [comment]
对于段落缩进功能，以后可能会做支持，现在建议使用CSS来实现吧
