### ISSUE TITLE
spellcheck attribute doesn't work

### ISSUE THREAD

**Issue by liadbe** [margox/braft-editor#433]
Hi, when trying to use <BraftEditor spellcheck={true} /> (or spellCheck), it seems to ignore this attribute, is there any reason for that?
How could I use contentEditable default spell checking using Braft?

Thanks,
Liad

**Comment by margox** [comment]
Hi! the BraftEditor component accepts a prop named `draftProps` which is an object and will be pass to the Editor component of draftjs directly, so you can use like this:
```js
const draftProps = { spellCheck: true }
```
```jsx
<BraftEditor draftProps={draftProps}/>
```
