### ISSUE TITLE
输入回车换行，在编辑器中是div，但是在保存的时候是p标签，导致没有空行样式

### ISSUE THREAD

**Issue by katrina-ZhangZiYue** [margox/braft-editor#437]
在编辑器中输入回车换行，使文字之间有空行，查看元素是插入了div。但是在保存的之后，转换成html就是p标签，且p标签中没有内容，导致显示的时候就没有空行样式。怎么解决这个问题呢？

**Comment by moxuan120** [comment]
我的没有你这个问题呢，最新版的回车，tab 空格键都可以呀

**Comment by moxuan120** [comment]
ie11使用这个组件工具栏没有那个悬浮提示，你的会不会？

**Comment by katrina-ZhangZiYue** [comment]
我用的Chrome。在编辑器的时候是这样的。
![image](https://user-images.githubusercontent.com/40882696/55937995-eb92ca80-5c6c-11e9-9375-05cb34d03c9d.png)
保存之后出现的html是这样的。
![image](https://user-images.githubusercontent.com/40882696/55938118-2694fe00-5c6d-11e9-866a-a92f8538a7b7.png)

**Comment by katrina-ZhangZiYue** [comment]
之间的空格的样式在显示的时候没有用，就是一个无内容的p标签

**Comment by margox** [comment]
https://github.com/margox/braft-editor/issues/373#issuecomment-466292634 看看这个

**Comment by katrina-ZhangZiYue** [comment]
好的，非常感谢

**Comment by letterSmall** [comment]
想问下，div标签被切换成p标签怎么解决
