### ISSUE TITLE
输入字符光标会条到第一行行首

### ISSUE THREAD

**Issue by luoandy** [margox/braft-editor#44]

**Comment by margox** [comment]
贴一下你的使用代码吧，感觉像是姿势不对导致了循环渲染。

**Comment by luoandy** [comment]
render() {
        const editorProps = {
            contentFormat: 'html',
            height: 500,
            initialContent: this.state.content,
            onChange: this.handleChange,
            onHTMLChange: this.handleHTMLChange,
            media: {
                uploadFn: this.uploadFn,
            }
        };


        return (
            <div className="" style={{border: 'solid 1px #d0d0d0'}}>
                <BraftEditor {...editorProps}/>
            </div>
        )

    }

    handleChange = (content) => {
        this.setState({content});
         this.props.onChange(content);
    };

    handleHTMLChange = (html) => {
        // this.props.s(html)
    };

**Comment by margox** [comment]
initialContent和content需要分开，不要用同一个字段

**Comment by luoandy** [comment]
handleChange这个方法的吗

**Comment by luoandy** [comment]
修改了  在 windos 上面光标还是会条到首行

**Comment by margox** [comment]
你是怎么修改的呢？

**Comment by luoandy** [comment]
我将initialContent去掉了 换成了 content

**Comment by margox** [comment]
贴一下修改后的代码吧，如果你没有需要初始化的内容，initialContent是不需要填的

**Comment by luoandy** [comment]
componentWillReceiveProps(nextProps) {

        if ('value' in nextProps && this.props.value !== nextProps.value) {
            if(this.editorInstance){
                this.editorInstance.setContent(nextProps.value||'', 'html')
            }else{
                this.setState({content: nextProps.value || ''})
            }

        }
    }

    render() {
        const editorProps = {
            contentFormat: 'html',
            height: 500,
            initialContent: this.state.content,
            onChange: this.handleChange,
            onHTMLChange: this.handleHTMLChange,
            media: {
                uploadFn: this.uploadFn,
            }
        };

        return (
            <div className="" style={{border: 'solid 1px #d0d0d0'}}>
                <BraftEditor {...editorProps}/>
            </div>
        )

    }

    handleChange = (content) => {
        this.setState({content});
        this.props.onChange(content);
    };

    handleHTMLChange = (html) => {
        // this.props.s(html)
    };

**Comment by margox** [comment]
![image](https://user-images.githubusercontent.com/7866354/35610412-2370a7ce-069c-11e8-8dc3-95f24b11b12d.png)
这个地方，不要把content传给initialContent，initialContent的值只是初始化用的，不应该再去更改它，initialContent每次改变之后，编辑器内容都会重新初始化一次，光标位置也会初始化。

**Comment by luoandy** [comment]
如果这样子的话  我初始化的时候  就没有从后端读取的数据了

**Comment by margox** [comment]
你初始化的数据不一定要放在content里面:
```javascript
class Demo extends React.Component {
  
  state = {
    htmlConent: '',
    initialContent: ''
  }

  componentDidMount () {

    fetchRemoteContent().then(response => {
      this.setState({
        initialContent: response
      })
    })

  }

  render () {

    return (
      <BraftEditor
        initialContent={initialContent}
        contentFormat="html"
        onChange={this.handleChange}
      />
    )

  }

  handleChange = (htmlConent) => {
    this.setState({ htmlConent })
  }
}
```

**Comment by luoandy** [comment]
修改了可以了  谢谢.

**Comment by haj1023** [comment]
请问是如何解决的 我也遇到这样的情况
