### ISSUE TITLE
文字颜色设置问题

### ISSUE THREAD

**Issue by Yvan0110** [margox/braft-editor#449]
![image](https://user-images.githubusercontent.com/20334318/56544714-d93b5980-65a7-11e9-9228-bcd4050b1d8a.png)

**Comment by margox** [comment]
啊？这个是一个bug啊啊啊，多谢反馈，我会尽快修复

**Comment by margox** [comment]
找到原因了，晚上回去修改

**Comment by Wangzongyao** [comment]
> 找到原因了，晚上回去修改
什么时候更新这个问题呢？项目急着用。

**Comment by margox** [comment]
晚上修改了就发一个版本哈

**Comment by Wangzongyao** [comment]
> 晚上修改了就发一个版本哈

赞！

**Comment by margox** [comment]
@Wangzongyao 已修复，升级一下braft-utils到3.0.12

**Comment by Wangzongyao** [comment]
> @Wangzongyao 已修复，升级一下braft-utils到3.0.12
嗯嗯，感谢哦！
