### ISSUE TITLE
结合 Ant Design Upload 组件上传图片后如何预览？

### ISSUE THREAD

**Issue by theprimone** [margox/braft-editor#452]
看了文档 https://braft.margox.cn/demos/antd-upload

源码是不是不完整？`import { ImageUtils } from 'braft-finder'`并没有使用，不知道是不是这个的问题。

现在上传成功后效果如下图
![](https://i.loli.net/2019/04/23/5cbe7f986c06e.png)

**Comment by margox** [comment]
ImageUtils里面只有一个压缩图片的方法，如果使用了的Antd的Upload，那预览什么的也都是要在Antd的Upload组件里面去做，你可以去看看Antd的文档

**Comment by theprimone** [comment]
那文档里边的预览直接就出来了是怎么回事呢？是因为`URL.createObjectURL`？

**Comment by margox** [comment]
额，直接就出来了是啥意思？

**Comment by theprimone** [comment]
那个文档上传图片之后不是直接在编辑框显示了吗？

**Comment by theprimone** [comment]
看了那个文档我就去集成 Upload 组件了。。。

原来语雀文档才是重点啊。发现 [media](https://www.yuque.com/braft-editor/be/gz44tn#0hgysg) 应该就可以了_(:3J∠)_

**Comment by macc6579** [comment]
> 看了那个文档我就去集成 Upload 组件了。。。
> 
> 原来语雀文档才是重点啊。发现 [media](https://www.yuque.com/braft-editor/be/gz44tn#0hgysg) 应该就可以了_(:3J∠)_
话说盆友 你怎么解决的。。需要 import { ImageUtils } 吗

**Comment by theprimone** [comment]
@macc6579 直接用组件的媒体插件，实现相关方法即可
