### ISSUE TITLE
从外部复制粘贴到编辑器里的内容会过滤掉样式，怎样关闭这个过滤？

### ISSUE THREAD

**Issue by lisun0459** [margox/braft-editor#454]

**Comment by margox** [comment]
是所有样式丢失了么？包括字号颜色之类的？ 因为编辑器内部状态转换的时候没办法做到识别全部的样式，所以只能保留一些支持的样式。如果你这边的情况是所有样式都被过滤了，那你检查一下stripPastedText这个属性是不是传false了，或者再确认一下复制过来的内容是不是富文本内容

**Comment by lisun0459** [comment]
例如很多编辑人员习惯借用一些有复杂样式的编辑器，例如，[新榜编辑器](https://edit.newrank.cn/)，习惯用他们的样式编辑好再copy过来，例如下面这样一个样式
![屏幕快照 2019-05-07 下午1 52 35](https://user-images.githubusercontent.com/15245259/57274942-6e257300-70cf-11e9-8ec6-34894d131bfc.png)
**在新榜编辑器里html是这样的**
![屏幕快照 2019-05-07 下午1 53 59](https://user-images.githubusercontent.com/15245259/57274993-99a85d80-70cf-11e9-8264-afa49bd68234.png)
但是copy到braft里面会过滤了只剩
`<p class="title white count">1</p><p class="brush active"><strong>这是一段内容一段内容一段内容一段内容一段内容</strong></p><p><br/></p>`
里面的<section>和style都会被过滤掉。
stripPastedText这个属性和stripPastedStyles属性都设置了都无效

**Comment by kerrzhao** [comment]
有同样的问题，希望有解决方案

**Comment by margox** [comment]
看下项目readme最前面有一段说明------------------ 原始邮件 ------------------
发件人: "kerrzhao"<notifications@github.com>
发送时间: 2019年6月20日(星期四) 中午11:30
收件人: "margox/braft-editor"<braft-editor@noreply.github.com>;
抄送: "超能刚哥"<margox@foxmail.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [margox/braft-editor] 从外部复制粘贴到编辑器里的内容会过滤掉样式，怎样关闭这个过滤？ (#454)



有同样的问题，希望有解决方案
 
&mdash;
