### ISSUE TITLE
您好，请问是否有disabled 属性 从而在保留内容的情况下 禁用编辑样式

### ISSUE THREAD

**Issue by ChinaBigPan** [margox/braft-editor#46]
非常感谢了，很好用的编辑器

**Comment by margox** [comment]
有这个属性，不过暂时还没暴露出来，现在可以用下面的办法实现:
```javascript
this.editorInstance.setEditorProp('disabled', true)
```
下一版本我把disabled属性暴露出来

**Comment by margox** [comment]
另外，设置这个属性之后，控制按钮还是可用的，试试通过CSS隐藏控制栏吧。。。下一版本这一块需要统一处理一下了。。。。

**Comment by ChinaBigPan** [comment]
谢谢了

**Comment by ChinaBigPan** [comment]
本来想试试把所有的change事件都return false的

**Comment by margox** [comment]
一个最简单的办法是你给编辑器容器设置CSS属性 pointer-events: none;

**Comment by ChinaBigPan** [comment]
您好，您提供的方法不管用 this.refs.braftEditor.setEditorProp('disabled', true)

**Comment by margox** [comment]
尴尬，记错了，是readOnly：
```
this.editorInstance.setEditorProp('readOnly', true)
```

**Comment by ChinaBigPan** [comment]
还是不管用额。。。是我的版本问题么  我是1.1.14

**Comment by margox** [comment]
脚本有报错么？看一下this.refs.braftEditor有没有setEditorProp这个方法

**Comment by ChinaBigPan** [comment]
有是有，不过居然是 Cannot read property 'setEditorProp' of undefined....我的富文本编辑器明明已经渲染了。
难道要写到componentDidMount里？

**Comment by margox** [comment]
恩，可能是时机问题，你也可以试试上面说的CSS属性 pointer-events: none;
```javascript
<div className="editor-wrapper disabled"><BraftEditor /></div>
```
```css
.editor-wrapper.disabled{
  opacity: .7;
  pointer-events: none;
}
```
这个也能有效，虽然不是那么严格。我明天发一个版本支持直接diasble吧

**Comment by ChinaBigPan** [comment]
我试试吧 上方的小按钮 我直接传空数组了，这个我先用着，等明天的支持版，谢谢了

**Comment by margox** [comment]
@ChinaBigPan 1.3.1已发布，新增了disabled属性，可以试试吼
