### ISSUE TITLE
一个页面用两个 braft-editor，通过 antd upload 上传图片后，ContentUtils.insertMedias 总是把图片插入到前一个的编辑器中去

### ISSUE THREAD

**Issue by LXVC** [margox/braft-editor#461]
两个编辑器都是用 getFieldDecorator 包装的

**Comment by margox** [comment]
贴代码，不然我也没办法知道出了什么问题

**Comment by LXVC** [comment]
我找到问题在哪了，我对 `braft-editor` 进行进行了一次封装。对 `extendControls` 这个 `props` 设置了默认值 `[]`,  在 `render` 方法内部 `this.props. extendControls.push` 了 `upload` 组件，由于 `upload` 的`key` 是相同的，而且两个 `Editor` 使用的是同一个数组。解决办法是不给 `extendControls` 设置默认值，而是在使用前这样去取：

`const { extendControls = [] } = this.props`

问题就解决了。
