### ISSUE TITLE
设置了uploadFn后，pasteImage设为true也不生效了

### ISSUE THREAD

**Issue by WayneLu1230** [margox/braft-editor#464]
可以让这两个属性并存吗

**Comment by margox** [comment]
我没理由让这俩属性不兼容啊，这两个属性本身是不会有冲突的，应该是你的uploadFn配置有问题，如果不配置uploadFn，粘贴的时候会直接生成一个内联图片插入到编辑器，你配置了uploadFn然后又有问题的话，粘贴的图片无法正常上传上去，是不会显示出来的。。。。

**Comment by margox** [comment]
贴一下你的uploadFn看看

**Comment by WayneLu1230** [comment]
解决了，确实是uploadFn的问题。。
