### ISSUE TITLE
开放headings api

### ISSUE THREAD

**Issue by huiboliu** [margox/braft-editor#466]
能否开放headings API ，让调用方可以过滤掉一些headings的可选项(实际情况下可能只需要其中的几个选项)。
![image](https://user-images.githubusercontent.com/14231859/57279161-dfb6ee80-70da-11e9-9968-78fd8a34f559.png)

**Comment by margox** [comment]
这个建议可以，下一版本加上，话是你这边能控制disabled的话，应该也能控制display吧，直接隐藏掉呢？

**Comment by huiboliu** [comment]
> 这个建议可以，下一版本加上，话是你这边能控制disabled的话，应该也能控制display吧，直接隐藏掉呢？

是的，现在是通过display:none 来解决了这个问题

**Comment by BosenY** [comment]
+1 感觉开放API控制要比css控制优雅一点

**Comment by marlti7** [comment]
+1 感觉开放API控制要比css控制优雅一点
