### ISSUE TITLE
是否是因为不支持section导致了style会被过滤了？

### ISSUE THREAD

**Issue by lisun0459** [margox/braft-editor#468]
例如很多编辑人员习惯借用一些有复杂样式的编辑器，例如，[新榜编辑器](https://edit.newrank.cn/)，习惯用他们的样式编辑好再copy过来，例如下面这样一个样式
![屏幕快照 2019-05-07 下午1 52 35](https://user-images.githubusercontent.com/15245259/57274942-6e257300-70cf-11e9-8ec6-34894d131bfc.png)
**在新榜编辑器里html是这样的**
![屏幕快照 2019-05-07 下午1 53 59](https://user-images.githubusercontent.com/15245259/57274993-99a85d80-70cf-11e9-8264-afa49bd68234.png)
但是copy到braft里面会过滤了只剩
`<p class="title white count">1</p><p class="brush active"><strong>这是一段内容一段内容一段内容一段内容一段内容</strong></p><p><br/></p>`
里面的section标签和style都会被过滤掉。
stripPastedText这个属性和stripPastedStyles属性都设置了都无效。
微信公众号copy过来的文章也会被过滤掉style和section

**Comment by margox** [comment]
因为这个编辑器使用的内核是draft-js，BraftEditor只是对draft-js的一个外围封装。
而draft-js作为一个React组件，它内部的状态并不是用HTML字符串来维护的，而是一个Immutable对象EditorState，将外部HTML转换为EditorState，用的是类似于穷举转换法，而EditorState本身支持的block类型有限，更不支持嵌套的block，所以几乎没办法将html完整的保留，只能保留一些最基本的样式。
如果对这一块有比较强烈的需求的话，那所有基于draft-js的编辑器都不是一个好的选择。
不过相对于其他基于draft-js的项目，本编辑器提供了一些可以自定义转换规则和扩展block类型的方法，如果你时间充足的话可以看看：[BraftEditor自定义block演示](https://braft.margox.cn/demos/block)

**Comment by lisun0459** [comment]
那么，braft从开发角度来看很方便简单易配置，从使用者(编辑)角度来看，颜值高功能齐全，传图什么的一切都配置好了打算替换了原来的quill，braft实在难以割舍，唯一的缺憾就是EditorState本身支持的block类型有限，要是能让EditorState支持section就完美了，section标签的使用还是很普遍的。刚哥，啥时候能突破一下这个局限？

**Comment by margox** [comment]
你如果只是想扩展一个block类型，那可以试试这样写:
```jsx
const blockRenderMap = Immutable.Map({
  'section': {
    element:  'section'
  }
})

<BraftEditor blockRenderMap={blockRenderMap} />
```

**Comment by lisun0459** [comment]
请问Immutable是从哪里import的？试了一下不引入报Immutable not defined，试了一下import {Immutable}from 'braft-utils';和import {Immutable}from 'braft-editor';会报'Map' of undefined

**Comment by margox** [comment]
```js
import { Map } from 'immutable'

const blockRenderMap = Map({
  'section': {
    element:  'section'
  }
})
```

**Comment by lisun0459** [comment]
好像并没有生效，
![屏幕快照 2019-05-09 上午11 16 50](https://user-images.githubusercontent.com/15245259/57425111-a1d9d780-724c-11e9-88ee-67d0f3fce6c5.png)
到了braft里面还是
<p>这是一段内容一段内容一段内容一段内容一段内容</p>

**Comment by margox** [comment]
额，好像没这么简单，还需要处理一下入参转换的问题，要把section标签转换成section类型的block，https://braft.margox.cn/demos/block，还是要参考一下这个例子

**Comment by lisun0459** [comment]
我看了一下文档，是不是要把这个blockRenderMap合并到DefaultDraftBlockRenderMap，是不是这个意思?但我试了一下报错Draft is not defined
,试想了一下，改成了braft,也是Braft is not defined
[https://draftjs.org/docs/advanced-topics-custom-block-render-map](url)
![1557478965090](https://user-images.githubusercontent.com/15245259/57515529-738bf300-7345-11e9-9384-8c653810a62f.jpg)

**Comment by margox** [comment]
BraftEditor内部会自动合并传入的blockRenderMap，现在你这边是因为只是指定了一个新的block类型，但是编辑器还不知道这个block在输出的时候该转换成怎样的html标签，也不知道在输入的时候把怎样的html标签转换成你这个新增的block、、、
https://braft.margox.cn/demos/block 你看看这个里面关于blockRenderMap的用法，就会知道怎么搞了

**Comment by lisun0459** [comment]
好的，谢谢刚哥，我好好看一下这个例子。

**Comment by America-first-melon** [comment]
> 好的，谢谢刚哥，我好好看一下这个例子。

这例子的写法哟用吗？为什么我写了个`
blockRenderMap：{
'unstyled': {
    element: 'div',
  }
} `不生效呢  生成的还都是p span 这些

**Comment by zhousufa** [comment]
我写了blockImportFn 拦截section标签，返回`const blockRenderMap = Immutable.Map({
  "block-section": {
    element: "section",
    wrapper: <SectionBlockWrapper />,
  },
  "block-foo": {
    element: FooBlockElement,
    wrapper: <FooBlockWrapper />,
  },
});` 但是粘贴的时候SectionBlockWrapper并没有执行，` BraftEditor.createEditorState(p.value, {
      blockImportFn,
      blockExportFn,
    })`用这种方式SectionBlockWrapper就执行了
