### ISSUE TITLE
uploadFn的结果为base64，导致图片显示不了

### ISSUE THREAD

**Issue by HelloLove** [margox/braft-editor#470]
param.success({url: base64String}) 无效，选择图片插入编辑后，src为空,感觉应该是draft把base64过滤掉了，请问怎么解决

**Comment by margox** [comment]
draftjs不会过滤base64的，你贴一下你的uploadFn的全部代码看看

**Comment by HelloLove** [comment]
const uploadFn = useCallback((param: any) => {
    const { file } = param;
    const reader: FileReader = new FileReader();
    reader.readAsDataURL(file);
    param.success({ url: reader.result });
  }, []);

**Comment by margox** [comment]
readAsDataURL是一个异步的操作，你这里有尝试过打印那个reader.result么？只有在reader.onload之后，才能拿到result的值，正确的写法是这样的：
```js
reader.onload = () => {
  param.success({ url: reader.result })
}
```

**Comment by margox** [comment]
你如果不配置uploadFn，编辑器默认就会生成一个base64的图片，只不过会对尺寸进行控制，控制在1280*800以内

**Comment by HelloLove** [comment]
默认生成的貌似不走validateFn

**Comment by margox** [comment]
这倒是，那你按上面的写法修正一下应该就行了

**Comment by HelloLove** [comment]
嗯，成功了，tks
