### ISSUE TITLE
打包后 css失效

### ISSUE THREAD

**Issue by Monsooon** [margox/braft-editor#471]
打包后页面打开就乱了,好像是没有css,能帮忙看一下是什么问题啊吗
![image](https://user-images.githubusercontent.com/22792671/57426141-ac966b80-7250-11e9-912a-cf3d034e0fc8.png)

**Comment by margox** [comment]
检查一下你的css-module配置，是不是对node_modules里面的css文件也开启了

**Comment by Monsooon** [comment]
解决了,是打包的时候cssmin插件将它过滤掉了,多谢
