### ISSUE TITLE
关于HTML标签直接显示

### ISSUE THREAD

**Issue by YufeeXing** [margox/braft-editor#472]
当`createEditorState('<p>Hello <b>World!</b></p>')`,时，如果希望不按html解析。在编辑区域直接显示html源码该怎么办？

**Comment by YufeeXing** [comment]
<p>hello world</p>在编辑区域还显示为<p>hello world</p>

**Comment by margox** [comment]
那你自己先用某个办法把这字符串里面的html字符转换成实体才行，网上很多方法的

**Comment by YufeeXing** [comment]
OK 明白
