### ISSUE TITLE
media下的uploadFn的具体配置属性

### ISSUE THREAD

**Issue by lxhn** [margox/braft-editor#476]
```js
const myUploadFn = (param) => {

  const serverURL = 'http://upload-server'
  const xhr = new XMLHttpRequest
  const fd = new FormData()

  const successFn = (response) => {
    // 假设服务端直接返回文件上传后的地址
    // 上传成功后调用param.success并传入上传后的文件地址
    param.success({
      url: xhr.responseText,
      meta: {
        id: 'xxx',
        title: 'xxx',
        alt: 'xxx',
        loop: true, // 指定音视频是否循环播放
        autoPlay: true, // 指定音视频是否自动播放
        controls: true, // 指定音视频是否显示控制栏
        poster: 'http://xxx/xx.png', // 指定视频播放器的封面
      }
    })
  }

  const progressFn = (event) => {
    // 上传进度发生变化时调用param.progress
    param.progress(event.loaded / event.total * 100)
  }

  const errorFn = (response) => {
    // 上传发生错误时调用param.error
    param.error({
      msg: 'unable to upload.'
    })
  }

  xhr.upload.addEventListener("progress", progressFn, false)
  xhr.addEventListener("load", successFn, false)
  xhr.addEventListener("error", errorFn, false)
  xhr.addEventListener("abort", errorFn, false)

  fd.append('file', param.file)
  xhr.open('POST', serverURL, true)
  xhr.send(fd)

}
```

**Comment by lxhn** [comment]
项目中用到BraftEditor主件，要求使用media属性上传视频，这个要怎么配置呢？谢谢

**Comment by margox** [comment]
额，上面那段代码是有什么看不明白的地方么？有一点需要注意的就是现在视频只支持mp4格式的

**Comment by lxhn** [comment]
视频是mp4格式的，但是我想要配置的话，要更改那些东西呢

**Comment by lxhn** [comment]
const serverURL = 'http://upload-server'
  const xhr = new XMLHttpRequest

**Comment by lxhn** [comment]
const serverURL = 'http://upload-server'
  const xhr = new XMLHttpRequest
这两句的意思是怎样的呢？

**Comment by margox** [comment]
。。。。太基础的JS知识，我没办法一一告诉你，毕竟我也要上班吃饭啊

**Comment by margox** [comment]
要上传视频，首先需要你们后端提供一个视频上传的接口，这个接口接受你传过去的视频文件，然后返回一个上传后的视频URL给你。
在uploadFn里面，你要做的就是通过XHR或者其他别的上传模块，调用后端接口把视频传上去，再把接口返回给你的视频URL，通过param.success传给编辑器

**Comment by lxhn** [comment]
那就是说const serverURL = 'http://upload-server'这个地址是改成后端提供的接口，后端接口返回保存地址，其他的就不做更改了吗

**Comment by margox** [comment]
有2个地方需要调整：
1：就是那个serverURL改成你们自己的接口
2：`xhr.responseText`这个地方，你要根据你们后端的返回格式自行调整

**Comment by lxhn** [comment]
好的，谢谢了
之前主要就是不知道具体要改哪些

**Comment by margox** [comment]
不客气，有问题可以加群聊，issue里面效率比较低

**Comment by lxhn** [comment]
嗯嗯，能发一个群号给我嘛

**Comment by margox** [comment]
交流反馈请加QQ群：725634541

**Comment by lxhn** [comment]
好的

**Comment by Bairuina** [comment]
视频下方为什么会有两个.mp4字段？可以隐藏第二个吗？

**Comment by Bairuina** [comment]
有没有属性可以隐藏视频封面下方的url地址？

**Comment by oceanlvr** [comment]
您好，我在开发上传功能时，发现 `myuploadFn` 返回的 `param.file` 参数为空，我该如何盘查错误呢？期待回复。

![image](https://user-images.githubusercontent.com/36698124/107123896-4c2bd680-68db-11eb-9b85-92f2fa62e708.png)
![image](https://user-images.githubusercontent.com/36698124/107123899-4df59a00-68db-11eb-849d-11c63dc1be22.png)
