### ISSUE TITLE
请问怎么去掉选择标题大小的内置组件

### ISSUE THREAD

**Issue by SanPy** [margox/braft-editor#478]
![image](https://user-images.githubusercontent.com/4796185/57594588-7835ee80-7573-11e9-91fc-7a1ec7e8736c.png)
就是图片上的这个组件，在文档中没有看见这个组件的名称，所以不知道在excludeControls中填什么名字

**Comment by margox** [comment]
这些配置文档里面有写的：[controls](https://www.yuque.com/braft-editor/be/gz44tn#bo49ph)和[excludeControls](https://www.yuque.com/braft-editor/be/gz44tn#1xv9po)

**Comment by SanPy** [comment]
@margox 我知道这两个可以控制组件的显示，但是我不知道这个标题的组件叫什么名字，我在文档中没有找到！

**Comment by margox** [comment]
嗯，这个控件叫headings,文档已经更新
