### ISSUE TITLE
当在编辑器里面删除图片时，没有回调函数吗？？

### ISSUE THREAD

**Issue by JSluowen** [margox/braft-editor#479]

**Comment by margox** [comment]
这个暂时没有太好的办法去实现哈

**Comment by JSluowen** [comment]
我现在遇到一个问题，就是如果选择Ant文件上传模块直接将图片插入到编辑器，我先将图片上传到七牛云，然后返回链接，但是，如果用户上传的图片错误，删除重新上传，那么之前上传的图片就没法在七牛云中删除

**Comment by JSluowen** [comment]
如果选用媒体库，用户一般编辑文章所用的资源都是一次性，根本就不需要使用一个媒体库特意存放记录啊。请问，有什么好方法可以解决这个问题吗

**Comment by margox** [comment]
考虑一下几个点：
1：编辑器的媒体库可以页面没刷新之前保证媒体资源的复用性，也可以将这个媒体库数据列表与你们后端进行同步来保证持久可复用
2：在编辑器中通过按键删除，本身是难以监控的，一个可行的办法就是在onChange中比较前后两次editorState的变化，找出差异进行处理，但如果用户插入了图片之后直接刷新页面了、关机了、断电了，这种情况也不可能处理到。
3：CDN上的容量不值钱，流量才值钱

**Comment by JSluowen** [comment]
恩恩好的，谢谢您的指定
