### ISSUE TITLE
如何添加自定义语言？

### ISSUE THREAD

**Issue by lamjack** [margox/braft-editor#48]
如何添加自己的语言文件，有无API提供，谢谢。

**Comment by margox** [comment]
暂时没有API，如果有需要，可以在src/languages目录里面参考其他2个语言文件然后新增一个你需要的语言文件，然后提个PR

**Comment by lamjack** [comment]
#49 已提交PR。

**Comment by lamjack** [comment]
謝謝。

**Comment by margox** [comment]
@lamjack 感谢你的支持，1.3.2已发布，language属性传入'zh-hant'即可
