### ISSUE TITLE
写了一个扩展，新建的是ok的，提交后重新编辑查看表现不一致？

### ISSUE THREAD

**Issue by lisun0459** [margox/braft-editor#481]
写了一个模板标题样式给运营使用，结果新建后提交再回来查看编辑的时候表现不一致
```jsx
// 编写扩展模块
const underdotExtension = {
    // 指定扩展类型
    type: 'inline-style',
    // 指定该扩展对哪些编辑器生效，不指定includeEditors则对所有编辑器生效
    includeEditors: ['demo-editor-with-underdot-ext'],
    // 指定扩展样式名，推荐使用全大写
    name: 'UNDERDOT',
    // 在编辑器工具栏中增加一个样式控制按钮，text可以为一个react组件
    control: {
        text: '标题样式'
    },
    // 指定该扩展样式的CSS规则，请注意，IE/EDGE浏览器暂时不支持textEmphasis
    style: {
        display: "inline-block",
        background: '#eeeeee',
        color: '#333333',
        padding: '8px 20px 8px 12px',
        borderTopRightRadius: '20px 50%',
        borderBottomRightRadius: '20px 50%',
        margin: "15px 0"
    },
    importer: (nodeName, node) => {
        // 指定html转换为editorState时，何种规则的内容将会附加上该扩展样式
        // 如果编辑器在createEditorState时使用的是RAW数据，并且开启了stripPastedStyles，则可以不指定importer，因为不存在html转editorState的场景
        return nodeName === 'span' && [].find.call(node.style, (styleName) => styleName.indexOf('text-emphasis') !== -1)
    },
    exporter: () => {
        // 指定该样式在输出的html中如何呈现，对于inline-style类型的扩展可以不指定exporter，输出样式即为该扩展的style
        return (
            <span style={{
                display: "inline-block",
                background: '#eeeeee',
                color: '#333333',
                padding: '8px 20px 8px 12px',
                borderTopRightRadius: '20px 50%',
                borderBottomRightRadius: '20px 50%',
                margin: "15px 0"
            }} />
        )
    }
}
```

// 加载扩展模块
BraftEditor.use(underdotExtension);`

提交后再获取内容打出来是符合要求的
`<p><span style="display:inline-block;background:#eeeeee;color:#333333;padding:8px 20px 8px 12px;border-top-right-radius:20px 50%;border-bottom-right-radius:20px 50%;margin:15px 0">这是一个标题</span></p><p></p><p></p>`
提交后再获取下来查看编辑的时候在编辑器里未表现出与新建的一致性
新建的时候是这样的
![屏幕快照 2019-05-13 下午6 33 16](https://user-images.githubusercontent.com/15245259/57615155-9f111680-75ad-11e9-9489-69511510c6cf.png)
提交后再来重编辑查看
表现就是这样的
![屏幕快照 2019-05-13 下午6 33 05](https://user-images.githubusercontent.com/15245259/57615202-bbad4e80-75ad-11e9-8af4-d41793b17190.png)

看了一下element并没渲染编辑器内的样式
而是渲染成了
```html
<div data-offset-key="6tit7-0-0" class="public-DraftStyleDefault-block public-DraftStyleDefault-ltr"><span data-offset-key="6tit7-0-0" style="background-color: rgb(238, 238, 238); color: rgb(51, 51, 51);"><span data-text="true">这是一个标题</span></span></div>
```

**Comment by margox** [comment]
你这里还需要对`importer`进行一下修改，在其中需要对node或者nodeName进行一些组合判断并返回判断值

**Comment by lisun0459** [comment]
是不是和entity扩展结合？https://braft.margox.cn/demos/entity，我试过，想着style被重置至少还有class，二者结合起来用，但是不行，二者结合用不了，顺带问一下扩展有多少种类？扩展在文档里好像没有提及https://www.yuque.com/braft-editor/be/lzwpnr，如果单纯使用entity扩展来实现，也是存在inline-style一样的问题，提交的时候存在class，再获取下来的时候也有并且也不是符合要求的样式，但只要编辑器被动过，focus，这样class就没了这段就会被重置。

**Comment by margox** [comment]
这个inline-style不是也有个importer嘛，你要在importer里面处理好就行了
关于有几种extension，你可以粗略看一下相关的源码： https://github.com/margox/braft-editor/blob/master/src/helpers/extension.js
