### ISSUE TITLE
设置字号等属性的默认值

### ISSUE THREAD

**Issue by kc2525** [margox/braft-editor#487]
如何设置字号等属性的默认值, 没有提供相应的属性

**Comment by margox** [comment]
这个默认值在编辑器这边不太好设置，因为编辑器的操作大多是基于选区的，没有选区的话就没办法设置样式。
要实现你的需求，你可以换个方法，通过外部CSS来设置编辑区域的字体样式之类的，同时在展示页也用同样的方法去设置展示容器的字体样式，而且这样做更灵活。

**Comment by kc2525** [comment]
能不能直接调用改字体大小的方法呢_draftJs.RichUtils.toggleInlineStyle(editState, "FONTSIZE-14"), 试了一下不行不知道是不是样式写的不对
