### ISSUE TITLE
转换成html显示时怎么还原有序列表的样式和无序列表的样式

### ISSUE THREAD

**Issue by WangJM001** [margox/braft-editor#488]
如题

**Comment by You00** [comment]
<div
            className='editor-wrapper'
            dangerouslySetInnerHTML={{__html: "<ol><li>ssss</li><li>234</li></ol>"}}
          />
像这种有序列表在普通div展示时，怎么像在富文本里面显示的一样，前面会有1、2序号

**Comment by chenzhijie521143** [comment]
list-style
