### ISSUE TITLE
getContainerNode is undefined

### ISSUE THREAD

**Issue by HowCanLove** [margox/braft-editor#492]
![image](https://user-images.githubusercontent.com/15058500/58079404-84f5ba80-7be3-11e9-9435-6497f79ae663.png)
这里的问题，我看到已经改好了，大概什么时候会发版呀？

**Comment by Robert2333** [comment]
同样遇到了。囧

**Comment by margox** [comment]
@HowCanLove @Robert2333 发了2.3.1了哈，更新下试试

**Comment by Robert2333** [comment]
修复了，不报错了
@margox
