### ISSUE TITLE
将组件更新至2.3.1之后，无法将raw字符串正确解析出来

### ISSUE THREAD

**Issue by baby1990** [margox/braft-editor#494]
此前我用的是 2.1.9的版本，最近查看了一下模块更新，将模块更新到了2.3.1，发现编辑器无法正确解析 raw 字符串，直接显示了 raw 字符串本身的内容

![image](https://user-images.githubusercontent.com/9276407/58140334-65a56e80-7c71-11e9-9567-2e5ed916d829.png)

难道更新修改了编辑器初始化方式，还是配置方面有所更改

**Comment by lujun5068** [comment]
我也遇到了这个问题，应该是解析方法出了点问题，但是我通过
`BraftEditor.creatEditorState(JSON.parse(rawValue))`
可以hack，最好还是作者修复一下

**Comment by margox** [comment]
已修复

**Comment by chjiyun** [comment]
2.2.9 也有问题，之前是好的啊，这几天突然坏了
"braft-convert": "^2.1.12",
"braft-editor": "^2.2.9",
"braft-extensions": "^0.0.18",

**Comment by margox** [comment]
升级到2.3.7吧------------------ 原始邮件 ------------------
发件人: "chjiyun"<notifications@github.com>
发送时间: 2019年6月25日(星期二) 晚上11:33
收件人: "margox/braft-editor"<braft-editor@noreply.github.com>;
抄送: "超能刚哥"<margox@foxmail.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [margox/braft-editor] 将组件更新至2.3.1之后，无法将raw字符串正确解析出来 (#494)



2.2.9 也有问题，之前是好的啊，这几天突然坏了
 "braft-convert": "^2.1.12",
 "braft-editor": "^2.2.9",
 "braft-extensions": "^0.0.18",
 
&mdash;
