### ISSUE TITLE
当表格列数超过5列，最终生成的html表格排版将会变的混乱

### ISSUE THREAD

**Issue by baby1990** [margox/braft-editor#495]
在编辑器中新建了7列表格：
![image](https://user-images.githubusercontent.com/9276407/58141702-db600900-7c76-11e9-93ba-6e36248fdc32.png)

实际生成的 html 表格样式：
![image](https://user-images.githubusercontent.com/9276407/58141735-f7fc4100-7c76-11e9-9f34-fdf7cb8c6c32.png)

**Comment by margox** [comment]
braft-extensions是啥版本的

**Comment by baby1990** [comment]
> braft-extensions是啥版本的

0.0.16

**Comment by margox** [comment]
升级到0.0.18试试

**Comment by baby1990** [comment]
> 升级到0.0.18试试

好

**Comment by baby1990** [comment]
> 升级到0.0.18试试

问题还在

**Comment by baby1990** [comment]
> 升级到0.0.18试试
升级完，原已编辑过的表格还是混乱状态，不过新创建的表格正常了

顺便看一下问题 #494？

**Comment by margox** [comment]
原先的表格，因为生成的内容已经固化了，所以需要手动修复才行哈，RAW解析的那个，是因为之前有大佬的PR，把我那一块自动适配的逻辑干掉了。。。。我今天晚上发个小笨笨修复一下

**Comment by baby1990** [comment]
> 原先的表格，因为生成的内容已经固化了，所以需要手动修复才行哈，RAW解析的那个，是因为之前有大佬的PR，把我那一块自动适配的逻辑干掉了。。。。我今天晚上发个小笨笨修复一下

👌
