### ISSUE TITLE
bug:在antd form组件中使用编辑器，代码高亮效果失效

### ISSUE THREAD

**Issue by xwjla** [margox/braft-editor#499]
如题

**Comment by margox** [comment]
贴下你的代码看看

**Comment by xwjla** [comment]
return(
      <div className="writeBlog-wrap">
        <Form onSubmit={this.handleSubmit}>
          <Form.Item  label="文章标题">
            {getFieldDecorator('title', {
              rules: [{
                required: true,
                message: '请输入标题',
              }],
            })(
              <Input placeholder="请输入标题"/>
            )}
          </Form.Item>
          <Form.Item  label="文章标签">
            {getFieldDecorator('tag', {
              rules: [{
                required: true,
                message: '请选择一个标签',
              }],
            })(
              <Select placeholder="标签">
                {
                  this.state.tagList.map((item,index)=>{
                    return(<Option value={item.id} key={item.id}>{item.name}</Option>)
                  })
                }
              </Select>
            )}
            <Button onClick={this.showModal}>新增标签</Button>
          </Form.Item>
          <Form.Item label="文章正文">
            {getFieldDecorator('content', {
              validateTrigger: 'onBlur',
              rules: [{
                required: true,
                validator: (_, value, callback) => {
                  if (value.isEmpty()) {
                    callback('请输入正文内容')
                  } else {
                    callback()
                  }
                }
              }],
            })(
              <BraftEditor
                className="my-editor"
                excludeControls={excludeControls}
                extendControls={extendControls}
                placeholder="请输入正文内容"
              />
            )}
          </Form.Item>
          <Form.Item>
            <Button size="large" type="primary" htmlType="submit">发布</Button>
          </Form.Item>
        </Form>
        <Modal
          title="请输入标签名"
          visible={this.state.visible}
          onOk={this.handleOk}
          onCancel={this.handleCancel}
        >
          <Input  onChange={this.onChange}/>
        </Modal>
      </div>
    )

**Comment by xwjla** [comment]
![image](https://user-images.githubusercontent.com/21350855/58255953-af40a700-7da0-11e9-9543-1db8efa957e6.png)

**Comment by margox** [comment]
BraftEditor.use那一段呢？

**Comment by xwjla** [comment]
![image](https://user-images.githubusercontent.com/21350855/58256188-2bd38580-7da1-11e9-80d8-139313f75dc6.png)

**Comment by margox** [comment]
你把那个includeEditors参数去掉试试

**Comment by xwjla** [comment]
去掉后生效了！

**Comment by xwjla** [comment]
非常感谢，赞赞赞！再麻烦您看下另一个issue
