### ISSUE TITLE
能给编辑器设置默认字体大小吗

### ISSUE THREAD

**Issue by xwjla** [margox/braft-editor#507]
现在默认的是16px，我想让他默认14或者12

**Comment by SyMind** [comment]
同样感觉能够设置编辑器默认的一些样式很有必要。

**Comment by margox** [comment]
这个功能编辑器自身不好实现，而且如果按照你们想的那样实现了这个功能，输出内容就限定死了，但是你们换个角度去想一下，是不是可以直接通过css的方式来实现呢？ 比如通过contentClassName\contentStyle来改掉内容区域的CSS？毕竟文字大小是会继承的啊
