### ISSUE TITLE
粘贴内容自带样式去除

### ISSUE THREAD

**Issue by Charlieeeeee** [margox/braft-editor#509]
有办法把粘贴过来的内容自动去除自带样式么

**Comment by margox** [comment]
https://www.yuque.com/braft-editor/be/gz44tn 看文档，有个stripPastedStyles属性，传true就会以纯文本模式粘贴，但是复制过来的HTML中的图片什么的也会被过滤掉

**Comment by Charlieeeeee** [comment]
您好，有没有办法，粘贴内容，只去除样式，但保留标签，就像控件里的清除样式一样。




------------------ 原始邮件 ------------------
发件人: "超能刚哥"<notifications@github.com>;
发送时间: 2019年5月30日(星期四) 中午1:37
收件人: "margox/braft-editor"<braft-editor@noreply.github.com>;
抄送: "┇葒詺村┇烁"<977503861@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [margox/braft-editor] 粘贴内容自带样式去除 (#509)



https://www.yuque.com/braft-editor/be/gz44tn 看文档，有个stripPastedStyles属性，传true就会以纯文本模式粘贴，但是复制过来的HTML中的图片什么的也会被过滤掉

**Comment by margox** [comment]
这个暂时没有直接的办法，但是你可以通过handlePastedText来自处理粘贴的内容，可以加群详聊：725634541
