### ISSUE TITLE
请问修改图片尺寸是否已经上了开发日程？

### ISSUE THREAD

**Issue by weihomechen** [margox/braft-editor#51]
图片上传后不能设置尺寸，觉得这个功能还是蛮重要的，而且readme里面开发计划也提到了修改图片宽度，不知道作者大大是否已经着手开发这个功能？

**Comment by margox** [comment]
感谢关注，比较大的功能开发可能要到年后了，现在公司事情太多，只能抽得出时间来做一些小的功能开发和bug修复啦

**Comment by weihomechen** [comment]
@margox 静候佳音😄
