### ISSUE TITLE
背景颜色内没法选择无背景色

### ISSUE THREAD

**Issue by williamnie** [margox/braft-editor#510]
在一行中设置了背景颜色后，换行还是会携带背景色，而在颜色选项里并不能选择无背景色，这样下面不想有颜色的就没法操作了，
![image](https://user-images.githubusercontent.com/26871884/58624049-e57ea900-8301-11e9-88e6-56a3f76e62b4.png)

**Comment by williamnie** [comment]
可以暂时通过选中，使用清除样式功能，fix住

**Comment by margox** [comment]
其实再次选择相同的颜色，就会清除掉之前设置的颜色，或者你也可以试试[高级取色器扩展](https://braft.margox.cn/demos/color-picker)，这个有个明显的清除按钮，而且可以设置无限颜色

**Comment by williamnie** [comment]
刚刚试了下，可以，我看看换成高级取色器吧
