### ISSUE TITLE
文本链接及图片链接相对路径自动添加前缀

### ISSUE THREAD

**Issue by KiharaRyou** [margox/braft-editor#511]
后端返回html字符串:
`"description":"<p><a href=\"/pages/test\">I am the paragraph</a><p><p><a href=\"/pages/test2\">I am the paragraph2</a><p>"`

前端接收后使用createFrom后直接toHTML:
const editorState = EditorState.createFrom(res.data.description)
console.log(editorState.toHTML())

显示结果：

 `<p><a href="http://localhost:8000/pages/test" target="">I am the paragraph</a></p><p></p><p><a href="http://localhost:8000/pages/test2" target="">I am the paragraph2</a></p><p></p>`

期望结果：
相对路径不要自动添加网址前缀

**Comment by margox** [comment]
今天会发个版本修复一下

**Comment by margox** [comment]
这个问题已修复，忘记告诉你了

**Comment by KiharaRyou** [comment]
> 这个问题已修复，忘记告诉你了

十分感谢
