### ISSUE TITLE
图片拖动功能好像只能拖一次。

### ISSUE THREAD

**Issue by xiewl** [margox/braft-editor#512]
见Video:
https://c-driver-servercp.qunarzz.com/c_driver_server_c_driver_server/13f6bd73d569489cb29662e1c141a9df.mp4

**Comment by margox** [comment]
已确认，下个版本会修复

**Comment by xiewl** [comment]
好的，修复这个的同时还希望能够提供一个开关，有的时候比较不需要这个拖放，但在使用时可能会不小心触发到

**Comment by margox** [comment]
好主意！

**Comment by margox** [comment]
发布了2.3.7,新增了`imageResizable `属性，试试

**Comment by xiewl** [comment]
可以了，谢谢！！

**Comment by rojer95** [comment]
图片拖动功能好像会导致居中失效。
