### ISSUE TITLE
图片无法拷贝粘贴

### ISSUE THREAD

**Issue by gecaitao** [margox/braft-editor#528]
看了代码默认pasteImage是true 但是无法实现图片粘贴

**Comment by margox** [comment]
是从哪里复制的图片？

**Comment by gecaitao** [comment]
> 是从哪里复制的图片？

目前已经解决了。新加的项目，之前开发用了这个组件由于没有使用media这个控件会导致图片拷贝无效，我加上了这个控件，然后用样式隐藏了控件。

**Comment by margox** [comment]
好的

**Comment by 1111mp** [comment]
@margox 请问 只能复制粘贴网络地址的图片吗  我复制粘贴本地的图片的时候就没效果了
