### ISSUE TITLE
File/Folder Dropped event (could be a hook)

### ISSUE THREAD

**Issue by gencer** [margox/braft-editor#532]
你好!

Is it possible to detect when file/folder dropped into editor and pass `files` to a function as a callback? So that we can process dropped files ourselves via custom upload mechanism?

```js
dropped: function(files) {
    // do with files
},
```
or

```js
dropped: function(event) {
  // do with event. files are inside it.
}
```

**Comment by margox** [comment]
try this:
```jsx

const myFileHandler = (files, editor) => {

  // you can process dropped media files here, and insert the processed files later by using `ContentUtils.insertMedias`
 
  // 'handled' must be returned or the editor will handle files itself.
  return 'handled'

}

<BraftEditor handleDroppedFiles={myFileHandler} />
```

**Comment by margox** [comment]
and there are many other handlers you can use to control the editor: 
https://github.com/margox/braft-editor/blob/master/src/configs/handlers.js

**Comment by gencer** [comment]
Awesome! Didn't notice those before.

Thanks!.

**Comment by gencer** [comment]
Using TypeScript, so, see here: https://github.com/margox/braft-editor/pull/533
