### ISSUE TITLE
插入一张图片，并且给图片添加了一个链接，但是链接没有生效

### ISSUE THREAD

**Issue by Dolov** [margox/braft-editor#534]
插入一张图片，并且给图片添加了一个链接，但是链接没有生效

**Comment by margox** [comment]
输出的html内容是正常的么

**Comment by w893308554** [comment]
对的，我也发现这个问题editorState对象转成html，内容里面有<a href='xx'></a>标签，但是生成在页面上富文本内容中没有a标签，点击链接不生效

**Comment by w893308554** [comment]
> 输出的html内容是正常的么

输出的html内容中没有a标签，img标签外面没有包裹a标签，所以点击链接无效。如果只插入超链接是OK的

**Comment by shenjo** [comment]
这个issue关闭了吗，是已经解决了吗 @Dolov 
我现在也遇到了这个问题，html字符串是 <p></p><div class="media-wrap image-wrap"><a style="display:inline-block" href="https://www.baidu.com" target="_blank"><img src="https://s1.ax1x.com/2020/07/22/UH7RSO.png"/></a></div><p></p> 
放到这个编辑器里a标签直接找不到了，求解
