### ISSUE TITLE
视频的下载按钮位置偏离

### ISSUE THREAD

**Issue by Dolov** [margox/braft-editor#536]
视频的下载按钮位置偏离
![WX20190614-171402](https://user-images.githubusercontent.com/19704420/59498399-f1ed2f00-8ec7-11e9-8939-dd23fe929281.png)

**Comment by margox** [comment]
这个应该是IE自己的问题吧，我这边视频预览直接用的video标签

**Comment by Dolov** [comment]
> 这个应该是IE自己的问题吧，我这边视频预览直接用的video标签

我用的 Chrome 浏览器

**Comment by margox** [comment]
我的意思是这玩意儿是浏览器自己的问题，我没有做过任何控制诶
