### ISSUE TITLE
媒体组件，第二次上传时报错。

### ISSUE THREAD

**Issue by zhou0818** [margox/braft-editor#537]
第一次上传成功后，第二次上传报错。
使用了 uploadFn,报错位置是 createThumbnail。貌似这里一直是取0，第二个图片的位置应该是1吧。报错信息如下：
`Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.`
只要调用了 param.success，第二次上传就会报错。

**Comment by kakeiChen** [comment]
> 第一次上传成功后，第二次上传报错。
> 使用了 uploadFn,报错位置是 createThumbnail。貌似这里一直是取0，第二个图片的位置应该是1吧。报错信息如下：
> `Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.`
> 只要调用了 param.success，第二次上传就会报错。

亲，解决了吗？什么问题？

**Comment by CRONWMMM** [comment]
@kakeiChen 这个错误应该是 url 是错的：
```
param.success({
  url: '',
  meta: {}
});
```
这个 url 是 undefined ，点击确定的时候图片就上不去，而且第二次图片也添加不上。
