### ISSUE TITLE
能否支持使用HTML源码呢？发现对这个功能的需求很多哦

### ISSUE THREAD

**Issue by qingsong81** [margox/braft-editor#54]

**Comment by margox** [comment]
本项目是基于draft-js的，和传统的富文本编辑器区别很大，实现HTML源码编辑的功能可能会很不稳定，根本原因是html与raw-data的转化率不能达到百分百，也就是说不是所有的html代码都能转换为draft-js可用的数据，在做粘贴功能的时候已经深受其害，不过后面有空的话，我还是会尝试一下实现这个功能。
