### ISSUE TITLE
colors list error

### ISSUE THREAD

**Issue by lanyulin** [margox/braft-editor#542]
文档上说：如果粘贴了一段带颜色的文字到编辑器里面，并且编辑器的可用颜色列表不包含该颜色，那么编辑器会自动将该颜色临时加入到可用颜色列表。

我复制的文字颜色，编辑器的可用颜色列表是有的，但是依然被添加到了列表里头

![image](https://user-images.githubusercontent.com/13092461/59813845-ac0bed00-9345-11e9-95b3-cd16c2d446eb.png)

**Comment by margox** [comment]
什么版本？------------------ 原始邮件 ------------------
发件人: "lanyulin"<notifications@github.com>
发送时间: 2019年6月20日(星期四) 上午10:25
收件人: "margox/braft-editor"<braft-editor@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [margox/braft-editor] colors list error (#542)



文档上说：如果粘贴了一段带颜色的文字到编辑器里面，并且编辑器的可用颜色列表不包含该颜色，那么编辑器会自动将该颜色临时加入到可用颜色列表。
 
我复制的文字颜色，编辑器的可用颜色列表是有的，但是依然被添加到了列表里头
 

 
&mdash;

**Comment by lanyulin** [comment]
2.3.4

**Comment by margox** [comment]
这两个颜色的色值是完全一样的么？

**Comment by margox** [comment]
哦，看出来了，你那2个都被高亮了，说明是一样的

**Comment by margox** [comment]
原因找到了，稍后发版本修复

**Comment by margox** [comment]
已发布2.3.7,升级试试

**Comment by lanyulin** [comment]
Problem solved. Thanks
