### ISSUE TITLE
图片标签出现乱码

### ISSUE THREAD

**Issue by JSluowen** [margox/braft-editor#547]
![image](https://user-images.githubusercontent.com/40996968/60147802-5b8f0680-9801-11e9-89a8-b8fc014ab5e1.png)

**Comment by yshaow** [comment]
楼上这个问题解决了吗

**Comment by margox** [comment]
这个问题，看看是不是有什么地方的样式干扰了
https://github.com/margox/braft-editor/issues/281
https://github.com/margox/braft-editor/issues/357

**Comment by JSluowen** [comment]
设置了一个全局的font-family ,导致的

**Comment by JSluowen** [comment]
解决了
