### ISSUE TITLE
插入代码的问题

### ISSUE THREAD

**Issue by SadCreeper** [margox/braft-editor#55]
很喜欢这个编辑器，已经集成到我的博客了，希望作者能一直更下去

看到作者刚刚回家过年了，先把issue提了吧，Orz....

插入多行代码后，不会显示在一个代码块里，而是每行代码显示在一个单独的代码块，下面上图：
![image](https://user-images.githubusercontent.com/19741140/35847659-1d8ef6c6-0b56-11e8-8b14-29e24ea753e9.png)
![image](https://user-images.githubusercontent.com/19741140/35847701-4a9a2906-0b56-11e8-8077-c584f23cc10e.png)

**Comment by margox** [comment]
这个? 你的代码是从别处复制过来的么？ 能把复制的代码贴一份看看么？ 我无论是按回车键手动输入多行代码，还是粘贴多行代码，都是正常的呢
![image](https://user-images.githubusercontent.com/7866354/36522963-32055c2c-17da-11e8-8b56-0f07f3fff308.png)

**Comment by margox** [comment]
我知道了，是预览的时候有问题，我看下。。。

**Comment by margox** [comment]
不看不知道，一看吓一跳，原来这个问题一直以来都有，太粗心了自己都没发现。。。

**Comment by margox** [comment]
@SadCreeper 更新一下试试看

**Comment by SadCreeper** [comment]
更新了还是不行呢？
而且我的编辑器里的代码块样式和你的不一样... 你那个明显要好看一些，而且是一整块，我这个每行都有一个框.. 不知道如何DEBUG
![image](https://user-images.githubusercontent.com/19741140/36595082-d29d4774-18db-11e8-9ef7-0768418ac498.png)
![image](https://user-images.githubusercontent.com/19741140/36595098-e1607a38-18db-11e8-94a0-6ca1e9cb3b98.png)

**Comment by margox** [comment]
你审查元素看一下，肯定是有外部样式给pre或code标签加了边框，而且字体也被影响到了，你看一下是哪个样式污染到他了。

另外你审查元素看看预览页面的html，是不是类似下面的结构：
```html
<pre><code>function foo () {</code></pre>
<pre><code>console.log('Hello World!')</code></pre>
<pre><code>}</code></pre>
```
按理说更新之后,`<pre>`不应该是每一行都有了的，只会包裹整个代码块，类似于下面这种：
```html
<pre>
  <code>function foo () {</code>
  <code>console.log('Hello World!')</code>
  <code>}</code>
</pre>
```

**Comment by margox** [comment]
对了，你这个博客文章，外网能访问到么？ 我想去瞧一瞧

**Comment by margox** [comment]
@SadCreeper 想到一个点，你也是用了braft-convert这个包吧？ 这个包我忘记更新了，我去更新一下...Orz

**Comment by SadCreeper** [comment]
找到原因了，是我使用的框架（Laravel）默认集成了 bootstrap，然后被 bootstrap 的样式污染了，我把 bootstrap 去掉了就OK了，我也太粗心了Orz...

给你点个赞，加油

**Comment by SadCreeper** [comment]
着实没想到样式污染还能产生这种BUG，又长知识了哈哈

**Comment by margox** [comment]
那预览页面的代码展示也正常了么？
如果使用了braft-convert的话，现在也可以更新一下了，已经发布1.1.0版本

**Comment by SadCreeper** [comment]
预览的还是有问题，现在跟你的demo同步了，我在你的demo官网上试了一下，发现也是有多个`<pre>`你看下呢：
![image](https://user-images.githubusercontent.com/19741140/36624060-9f49ef84-1945-11e8-87b0-727473cca899.png)
![image](https://user-images.githubusercontent.com/19741140/36624083-ecaf9616-1945-11e8-932e-256eb97b369d.png)

**Comment by margox** [comment]
恩，我的demo还是旧的。你更新一下braft-convert,再重新发布一下文章看看

**Comment by SadCreeper** [comment]
搞定了，你的包更新到 1.4.2 就OK了，辛苦辛苦^ ^

**Comment by margox** [comment]
😂啊？ 1.4.2解决的是IE11的一个问题，和插入代码的没关系啊

**Comment by SadCreeper** [comment]
那就奇怪了，莫非是我上次更新之后没更新成？或者有缓存之类的没清理么

至少现在是没有那个问题了，然后 braft-convert 我也没手动装过

但是现在出现了一个新问题，创建文章之后没什么问题：
![image](https://user-images.githubusercontent.com/19741140/36624280-15a2870c-1948-11e8-9189-4211a0d3f5f8.png)
![image](https://user-images.githubusercontent.com/19741140/36624285-1ed3a068-1948-11e8-9065-33553ebbc844.png)

然后编辑文章的时候，我的做法是把数据库里保存的 htmlContent 取出来放到 initialConten 里，然后出现了问题，代码的格式乱了：

![image](https://user-images.githubusercontent.com/19741140/36624290-31f757de-1948-11e8-8db7-b23a2daf79f0.png)

**Comment by margox** [comment]
对于draft-js来说，要做到html和raw百分百转换几乎是不可能的，现在这个问题就是因为这个转化差异导致的，就好像把一个照片PS之后，丢掉psd源文件，就很难PS回去了一样。
我估计要花多点时间来研究一下怎么保证代码块的重复编辑性了。
最靠谱的办法还是使用raw来保存文章数据 ，或者raw和html各保存一份，编辑的时候用raw，保证万无一失。

**Comment by margox** [comment]
有眉目了，中午之前应该能出一个版

**Comment by SadCreeper** [comment]
可以可以，我刚想试试保存 raw，那就先等你下一版了

**Comment by margox** [comment]
已发布1.4.3，更新一下试试

**Comment by SadCreeper** [comment]
兄弟你速度可以的，这下OK了，很完美

**Comment by margox** [comment]
好的，那这个我先close掉了，这块儿再有问题的话，就再提一个新的issue吧，另外自定义弹窗内容不更新的，你也现在也可以看看，应该是解决掉了的。
