### ISSUE TITLE
添加图文提交数据使用toHTML

### ISSUE THREAD

**Issue by qflchina1234** [margox/braft-editor#551]

**Comment by qflchina1234** [comment]
版本2.3.3 提交数据时是同toHTML方法转换，返回数据为空  使用toRAW返回正常

**Comment by margox** [comment]
升级到最新版试试，另外看看控制台有无警告或者报错

**Comment by qflchina1234** [comment]
@margox  你好   已升级到2.3.7版本 问题依旧存在   控制台提示警告 TypeError: contentState.getBlockForKey is not a function

**Comment by margox** [comment]
首先删除node_modules之后重新安装试试，不行的话试试下面的办法：
1: 检查是否存在多个版本的immutable，编辑器只能用3.7.x的
2: 检查是否安装了其他的基于draft-js的项目
3: 检查draft-js的版本

**Comment by qflchina1234** [comment]
@margox  thanks 问题已解决，存在了多个版本
