### ISSUE TITLE
请问大神2019-06-20 v2.3.7最新版本到哪获取

### ISSUE THREAD

**Issue by Lzw2016** [margox/braft-editor#555]
# 开源首页显示最新版本是 2019-06-20 v2.3.7

![图片](https://user-images.githubusercontent.com/19291563/60598238-eb731880-9dde-11e9-9ffc-27eccada7791.png)

# npm 仓库确显示 version 2.1.26

![图片](https://user-images.githubusercontent.com/19291563/60598272-fb8af800-9dde-11e9-8ec4-b152841b7af9.png)

**Comment by margox** [comment]
你不妨看一下你那个npm网页的URL是什么。。。

**Comment by margox** [comment]
https://www.npmjs.com/package/braft-editor 访问这个就能看到最新版本，你看到的肯定是这个页面：https://www.npmjs.com/package/braft-editor/v/2.1.16

**Comment by Lzw2016** [comment]
多谢指点
