### ISSUE TITLE
和ant design pro 集成时没有外边框

### ISSUE THREAD

**Issue by qteamcheng** [margox/braft-editor#564]
![image](https://user-images.githubusercontent.com/38239481/61179136-fb84c680-a62e-11e9-86bd-b81b733b7972.png)

在一个ant design pro中集成BraftEditor 时，没有显示外边框，谁知道怎么回事？

谢谢

**Comment by z1y1m1** [comment]
怎么解决的？我也遇到同样问题

**Comment by z1y1m1** [comment]
> 怎么解决的？我也遇到同样问题

搞定了，加上样式

.myEditor {
  border: 1px solid #d1d1d1;
  border-radius: 5px;
}
