### ISSUE TITLE
如何扩展可编辑 html 代码？

### ISSUE THREAD

**Issue by LengYXin** [margox/braft-editor#573]
如何扩展 将内容转换成 html 代码直接编辑？
是将内容转换成 文本 格式 编辑后再转回去？

**Comment by margox** [comment]
不太好做，至于为什么，你可以看下[使用前请了解](https://github.com/margox/braft-editor#%E4%BD%BF%E7%94%A8%E5%89%8D%E8%AF%B7%E4%BA%86%E8%A7%A3)

**Comment by LengYXin** [comment]
@margox  使用 [codemirror ]( https://github.com/codemirror/CodeMirror ) 扩展了一个 ，貌似没啥问题。
使用 toHtml 转换 为 html  使用 codemirror 编辑，编辑完成后 使用 createEditorState 又转了回来。能把 默认 的编辑区域转换为  codemirror  的编辑区域就好了。现在是弹出框。看了源码 好像不能替换默认的 编辑区域~

**Comment by margox** [comment]
你试试直接用一个绝地定位的div盖住编辑器区域，在这个div里面放入codemirror呢？然后用一个扩展按钮控制这个div的显示和隐藏
