### ISSUE TITLE
Where do i could find this untranslated text for translate it to russian language

### ISSUE THREAD

**Issue by TheComedian08** [margox/braft-editor#577]
![AwesomeScreenshot-React-App-2019-07-29-16-07-29](https://user-images.githubusercontent.com/24483169/62054083-8ebe1e80-b221-11e9-87ff-8523a4af0313.png)

It is in the media modal. I need to translate Chinese words to russian

**Comment by margox** [comment]
https://github.com/margox/braft-finder here, PR's welcome :)

**Comment by TheComedian08** [comment]
> https://github.com/margox/braft-finder here, PR's welcome :)

thanks!
