### ISSUE TITLE
使用Ant Design upload上传后，报错 e.getSelection is not a function

### ISSUE THREAD

**Issue by macc6579** [margox/braft-editor#587]
![image](https://user-images.githubusercontent.com/11343720/62853492-1d04cb00-bd1f-11e9-8a32-f617a00335d6.png)

阅读draft文档，看上去是光标定位的问题，尝试自己处理，未果。
贴上代码，请大神指教www

` state = { `
 `   editorState: BraftEditor.createEditorState()`
`  };`

 ` componentDidMount() {`
   ` this.fetch();`
 ` }`

    fetch = async () => {
    const { id, fetch } = this.props;
    const {
      form: { setFieldsValue }
    } = this.props;
    await fetch(id);
    setTimeout(() => {
      const { question } = this.props;
      setFieldsValue({
        description: BraftEditor.createEditorState(
          question ? question.getDescription() : ''
        )
      });
    }, 0);

    uploadImage = param => {
    const { user } = this.props;
    uploadImage(param.file, {
      ssoToken: user ? user.get('sso_token') : '',
      upYunSyncPreprocessor: '/both/1080x530'
    }).then(
      url => {
        const imgUrl = url;
        console.log('拿到url了????~~', url);
        const {
          form: { getFieldValue, setFieldsValue }
        } = this.props;
        const editorState = getFieldValue('content');
        setFieldsValue({
          content: ContentUtils.insertMedia(editorState, [
            {
              type: 'IMAGE',
              url: imgUrl
            }
          ])
        });
      },
      err => {
        message.error(err);
      }
    );
     };

    const extendControls = [
      {
        key: 'antd-uploader',
        type: 'component',
        component: (
          <Upload
            accept="image/*"
            showUploadList={false}
            customRequest={this.uploadImage}
          >
            <button
              type="button"
              className="control-item button upload-button"
              data-title="插入图片"
            >
              <Icon type="picture" theme="filled" />
            </button>
          </Upload>
        )
      }
    ];

          <Form.Item label="问题答案" {...formItemLayout}>
            {form.getFieldDecorator('description', {
              initialValue: question ? question.getDescription() : '',
              validateTrigger: 'onBlur',
              rules: [
                {
                  validator: this.validateDescription
                }
              ]
            })(
              <BraftEditor
                className="my-editor"
                controls={controls}
                extendControls={extendControls}
                placeholder="请输入问题答案"
                vaule={editorState}
                onChange={this.handleChange}
              />
            )}
          </Form.Item>

**Comment by macc6579** [comment]
这个问题解决了。
因为用了AntD的组件上传，所以使用antd的上传 方法，我的getFieldValue('content')的字段填写错误，应该与API返回字段一致。
还是由于自己对工具掌握不精，在此分享，希望能给小伙伴带来帮助。
另外QQ群的小伙伴们非常有爱，在此附上群号，响应更及时。
交流反馈QQ群：725634541

**Comment by Ucoon** [comment]
请问“应与API返回字段一致”是指什么，上传图片返回的吗？

**Comment by macc6579** [comment]
> 请问“应与API返回字段一致”是指什么，上传图片返回的吗？

存储图片地址的对应字段

**Comment by Ucoon** [comment]
大佬 因为把上传组件又封成一个自定义组件，所以我把对应字段传进去，还是会报这个错，是为什么

**Comment by Ucoon** [comment]
这是我的代码
```   const extendControls = [
      {
        key: 'antd-uploader',
        type: 'component',
        component: (
          <ActivityUpload
            ossFilePath="activity"
            handleUploadSuccess={url => {
              form.setFieldsValue({
                content: ContentUtils.insertMedias(form.getFieldValue('ossFilePath'), [
                  {
                    type: 'IMAGE',
                    url: url,
                  },
                ]),
              })
              console.log('传输成功' + url)
            }}
          ></ActivityUpload>
        ),
      },
    ]
```

**Comment by Ucoon** [comment]
可以了，我这个真的是因为光标的问题，和你的好像不是一个bug

**Comment by guoxiangwen** [comment]
@Ucoon 什么是光标问题 我也遇到了

**Comment by macc6579** [comment]
> 可以了，我这个真的是因为光标的问题，和你的好像不是一个bug

用的是受控组件吗。。。或者打log出来康康，光标的问题我木有遇到

**Comment by guoxiangwen** [comment]
@macc6579  可以帮我看看吗？

**Comment by macc6579** [comment]
> @macc6579 可以帮我看看吗？

贴出代码？或者给一个能复现问题的链接叭，比如这种
 https://stackblitz.com/

**Comment by guoxiangwen** [comment]
```
import { message, Upload } from 'antd';
import { FormInstance } from 'antd/lib/form/index';
import { UploadChangeParam, UploadFile, UploadProps } from 'antd/lib/upload/interface';
import React, { useEffect, useState } from 'react';

import useGetOSSToken from '@hooks/useGetOSSToken';
import { OSS_CONFIG } from '@kry/kic-config';
import { randomString } from '@shared/utils/index';
import BraftEditor, { ControlType, EditorState, ExtendControlType } from 'braft-editor';
import 'braft-editor/dist/index.css';
import { ImageUtils } from 'braft-finder';
import { ContentUtils } from 'braft-utils';

import 'braft-editor/dist/index.css';

interface IKCSBraftEditor {
  form?: FormInstance;
  onChange?: (value: string) => void;
  value?: string;
}

const KCSBraftEditor: React.FC<IKCSBraftEditor> = ({ onChange, form, value }) => {
  console.log(ImageUtils);
  const [data, setData] = useState<any>(BraftEditor.createEditorState(null));
  const handleChange = (editorState: EditorState) => {
    setData({ data: editorState });
    form && form?.setFieldsValue({ notification: editorState.toHTML() });
    onChange && onChange(editorState.toHTML());
  };
  useEffect(() => {
    setData(BraftEditor.createEditorState(value));
  }, [value]);
  // todo 编辑查看的时候form.set 初始值

  const [uniqueName, setUniqueName] = useState<string>();
  const getRelativePath = () => {
    return `${uniqueName}`;
  };
  const isOutofSize = (filesize: number) => {
    if (5 && 5 * 1024 * 1024 < filesize) {
      return true;
    } else {
      return false;
    }
  };
  const handleBeforeUpload = (file: UploadFile) => {
    if (isOutofSize(file.size)) {
      message.error('上传图片过大，请重新上传');
      return false;
    }

    const filename = file.name || 'unknown';
    const suffix = filename.substr(filename.lastIndexOf('.'));
    setUniqueName(`${randomString()}${suffix}`);
    return true;
  };
  const handleImgChange = (info: UploadChangeParam) => {
    // tslint:disable-next-line:no-shadowed-variable
    const { file, fileList } = info;
    // if (file.status === 'uploading') {
    // }
    // if (file.status === 'error') {
    // }
    if (file.status === 'done') {
      const filepath = getRelativePath();
      file.url = `${OSS_CONFIG.URL}/${filepath}`;
      file.thumbUrl = file.url;
      fileList[fileList.length - 1].url = `${OSS_CONFIG.URL}/${filepath}`;
      fileList[fileList.length - 1].name = `${file.name}`;
      // 通知到上层form表单

      setData(
        ContentUtils.insertMedias(data, [
          {
            type: 'IMAGE',
            url: file.url,
          },
        ])
      );
    }
  };
  const controls = [
    'blockquote',
    'bold',
    'code',
    'clear',
    'emoji',
    'font-family',
    'font-size',
    'fullscreen',
    'headings',
    'hr',
    'italic',
    'letter-spacing',
    'line-height',
    'link',
    'list-ol',
    'list-ul',
    'media',
    'redo',
    'remove-styles',
    'separator',
    'strike-through',
    'superscript',
    'subscript',
    'text-align',
    'text-color',
    'text-indent',
    'underline',
    'undo',
    'table',
  ] as ControlType[];
  const {
    data: { policy, signature, accessKeyId },
  } = useGetOSSToken([]);
  const uploadProps: UploadProps = {
    action: OSS_CONFIG.URL,
    accept: '.png,.jpg,.jpeg',
    data: (file: UploadProps) => {
      return {
        key: `${getRelativePath()}`,
        policy,
        signature,
        OSSAccessKeyId: accessKeyId,
      };
    },
    beforeUpload: handleBeforeUpload,
    onChange: handleImgChange,
    showUploadList: false,
  };
  const extendControls = [
    {
      key: 'antd-uploader',
      type: 'component',
      component: (
        <Upload {...uploadProps} accept="image/*" showUploadList={false}>
          {/* 这里的按钮最好加上type="button"，以避免在表单容器中触发表单提交，用Antd的Button组件则无需如此 */}
          <button type="button" className="control-item button upload-button" data-title="插入图片">
            插入图片
          </button>
        </Upload>
      ),
    },
  ] as ExtendControlType[];
  return (
    <div className="editor-wrapper">
      <BraftEditor
        value={data}
        onChange={handleChange}
        controls={controls}
        extendControls={extendControls}
        placeholder="在这里编辑正文内容"
      />
    </div>
  );
};

export default KCSBraftEditor;

```
![image](https://user-images.githubusercontent.com/7627191/98791881-a504e380-2440-11eb-8d30-925f444b819e.png)
@macc6579
