### ISSUE TITLE
扩展按钮的问题

### ISSUE THREAD

**Issue by SadCreeper** [margox/braft-editor#59]
我添加了一个扩展按钮，类型选取的是 Modal

然后在弹出的 Modal 中我做了一个 html 转 markdown 的功能，这个功能是通过API在后端完成的，转换完之后将 markdown 内容返回来更新 state

此时问题出现了，这个弹出的 Modal 里是显示了这个 state 的，但是在 state 更新后，Modal 里的 children 没有重新渲染，如果关了这个 Modal 重新打开一次就会显示出来更新后的 state

不知道是不是哪里阻止了重新渲染，现在我只能换成了 button 类别的扩展按钮点击后触发一个单独的Modal 来实现

**Comment by margox** [comment]
确实有点问题，我优先解决一下，下一版本解决掉

**Comment by margox** [comment]
@SadCreeper 发了1.4.0版，更新一下试试看？注意一下，自定义的modal，现在必须要指定一个唯一的id：
```javascript
{
    type: 'modal',
    text: 'Bar',
    modal: {
      id: 'test-modal', // v1.4.0新增
      title: '这是一个弹出框',
      showClose: true,
      showCancel: true,
      showConfirm: true,
      confirmable: true,
      onConfirm: () => console.log(1),
      onCancel: () => console.log(2),
      onClose: () => console.log(3),
      children: (
        <div style={{width: 480, height: 320, padding: 30}}>
          <span>Hello World！</span>
        </div>
      )
    }
  }
```

**Comment by SadCreeper** [comment]
刚试了下，确实可以了，不过以前的没加 id 的都不能用了，并且没有任何报错，就是以前用老版的人如果不知道可能要DEBUG好久了23333
