### ISSUE TITLE
用webpack对js压缩后，点击工具栏的多媒体图标时报错

### ISSUE THREAD

**Issue by seraphimrose** [margox/braft-editor#6]
先占个坑…

用webpack打包时不进行JS压缩可以正常使用。压缩后发布到线上想要传图片，点击工具栏时报了一个错: `xx is not a function`，怀疑是压缩后变量名重复？

```jsx
import React from 'react'
import PropTypes from 'prop-types'
import BraftEditor from 'braft-editor'
import 'braft-editor/dist/braft.css'

const controls = [
  'bold',
  'italic',
  'underline',
  'strike-through',
  'text-color',
  'split',
  'text-align',
  'split',
  'list_ul',
  'list_ol',
  'split',
  'link',
  'media',
]

const colors = [
  '#000000',
  '#333333',
  '#999999',
  '#ffffff',
  '#1C89EA',
  '#13ce66',
  '#f7ba2a',
  '#ff4949',
]

const media = upload => ({
  image: true,
  video: true,
  audio: true,
  uploadFn: upload,
})

const RichTextEditor = ({ value, onChange, upload }) => (
  <BraftEditor
    contentFormat="html"
    initialContent={value}
    onHTMLChange={onChange}
    controls={controls}
    colors={colors}
    media={media(upload)}
  />
)

RichTextEditor.propTypes = {
  value: PropTypes.string,
  onChange: PropTypes.func,
  upload: PropTypes.func,
}

export default RichTextEditor

```

**Comment by seraphimrose** [comment]
![screenshot](https://user-images.githubusercontent.com/13270208/30969525-45031b64-a428-11e7-930d-f9e053d5f026.png)

补张图，点击上传图片按钮后，无法弹出modal，报上面这个错

webpack对UglifyJsPlugin的配置：

```javascript
new webpack.optimize.UglifyJsPlugin({
  compress: {
    warnings: false,
  },
  output: {
    comments: false,
  },
}),
```

**Comment by margox** [comment]
点开报错左边的三角形看看具体报错是出现在哪儿？ 在开发者工具里面可以展开压缩的代码的，能找到大体的报错位置

**Comment by margox** [comment]
我这边采用你的配置进行压缩，没有出现错误，另外我原本的压缩配置是：
``javascript
new webpack.optimize.UglifyJsPlugin({
  compress: {
    unused: true,
    dead_code: true,
    warnings: false
  }
})
```

**Comment by seraphimrose** [comment]
![screenshot2](https://user-images.githubusercontent.com/13270208/31005129-ffd04680-a4bc-11e7-8151-915cdf8f8d7f.png)
![screenshot3](https://user-images.githubusercontent.com/13270208/31005143-0ff6aa22-a4bd-11e7-9e90-8bc136abdfb8.png)

**Comment by margox** [comment]
这个e没被压缩之前是setImmediate，这个按理说不应该被压缩的，我的webpack是2.6.1版本，你用的是什么版本呢？ 另外我的babelrc的配置是：
```
{
  "presets": ["es2015", "stage-0", "react"]
}
```

**Comment by seraphimrose** [comment]
webpack@2.7.0

**Comment by margox** [comment]
我试试加个保险，通过window.setImmediate来调用应该就不会被压缩了

**Comment by margox** [comment]
发布了1.1.2, 你更新一下试试

**Comment by seraphimrose** [comment]
更新到1.1.2就好了~

**Comment by margox** [comment]
好的，非常感谢支持，遇到其他的问题欢迎提issue
