### ISSUE TITLE
TS报错问题

### ISSUE THREAD

**Issue by stefaniepei** [margox/braft-editor#60]
TS2322: Type '{ height: number; placeholder: string; ref: (instance: BraftEditor) => BraftEditor; contentFormat...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<BraftEditor> & Readonly<{ children?: ReactNode; }>...'.
  Type '{ height: number; placeholder: string; ref: (instance: BraftEditor) => BraftEditor; contentFormat...' is not assignable to type 'Readonly<editorProps>'.
    Types of property 'contentFormat' are incompatible.
      Type 'string' is not assignable to type 'RawDraftContentState'.

code:
<BraftEditor
                  height={500}
                  placeholder={'最多可输入3000个字符'}
                  ref={(instance) => Store.editorContent = instance}
                  contentFormat='html'
                  initialContent={Store.editorContent} />

功能正常可以跑通

**Comment by stefaniepei** [comment]
![image](https://user-images.githubusercontent.com/1124923/36070713-a4457030-0f3b-11e8-8c73-97b897a11762.png)

**Comment by margox** [comment]
@petitspois 求帮助

**Comment by petitspois** [comment]
我看看

**Comment by stefaniepei** [comment]
@margox  @petitspois  求解决

**Comment by petitspois** [comment]
@stefaniepei 可以关注https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23971
这里正在等待合并！合并更新就好了！
也可以声明类型暂时解决
```js
declare module 'braft-editor';
```
