### ISSUE TITLE
IE11  对象不支持“startsWith”属性或方法

### ISSUE THREAD

**Issue by Errshao** [margox/braft-editor#61]

**Comment by Invincible-Keen** [comment]
同问，作者貌似回家过年了，请问有自己解决了的小伙伴么

**Comment by margox** [comment]
我找个IE11试试。。。

**Comment by margox** [comment]
看了一下，是一些其他的npm包里面用到了startsWith这个方法，你们可以自己加几行代码来polyfill一下：
```javascript
if (!String.prototype.startsWith) {
  String.prototype.startsWith = function (search, pos) {
    return this.substr(!pos || pos < 0 ? 0 : +pos, search.length) === search
  }
}
```
或者使用[babel-polyfill](https://babeljs.io/docs/usage/polyfill/)

**Comment by Invincible-Keen** [comment]
只能用babel-polyfill， 因为自己加prototype的方法解决完startsWith之后还会有其他问题，我试过。但现在的问题是，用了babel-polyfill之后，不报错了，但上传图片的时候弹出框会打不开，暂时还没发现其他问题。IE兼容性问题估计要改的地方应该不少的。

**Comment by margox** [comment]
昨天回家试了一下IE11，加入babel-polyfill之后，插入媒体文件的弹窗也能正常打开，你那边点开弹窗的时候，会报错么? 另外试试更新到1.4.0看看

**Comment by Invincible-Keen** [comment]
我更新了1.4.0，问题还是存在。上传媒体文件要弹两个窗，我这边第一个窗体是可以打开的，但是点击或拖动文件至此这块区域无论是点击弹窗还是拖动文件都不能用。Chrome下一切正常。

**Comment by margox** [comment]
了解了，我晚上回家才有win的电脑，我到时候看一下

**Comment by margox** [comment]
@Errshao @Invincible-Keen 已发布1.4.2，更新试试

**Comment by Invincible-Keen** [comment]
牛逼，更新了1.4.3， 弹框正常了，但是IE下面点击放上去的图片所在那一行，外围会有一个类似layout的一个黑框闪现，另外就是编辑焦点很多时候要点几下才能上去，而在chrome下面没有这些情况。

**Comment by margox** [comment]
其他的问题我回去再看看吧，IE下面确实问题多多的，这个我先close掉咯

**Comment by Invincible-Keen** [comment]
好的，谢啦

**Comment by Errshao** [comment]
谢谢 问题都解决了

**Comment by moxuan120** [comment]
为啥这个组件在ie上很卡，看控制台频繁调用iterable里头的函数。谷歌不会卡。
