### ISSUE TITLE
[媒体库] [新功能建议] 添加媒体库内部组件的定制化

### ISSUE THREAD

**Issue by ruihanma** [margox/braft-editor#634]
### 用来对媒体库的资源进行增删改查

比如可以添加翻页按钮
这样媒体库就能结合网络
进行更灵活的媒体插入组合

_PS 感谢开发者的辛劳
之前用 react-draft-wysiwyg
传个图片 半条命都没了……_

**Comment by margox** [comment]
最近大半年以来空余时间太少了，后面我想慢慢用ts把这个项目重构一下，目前版本的问题太多了 ：(

**Comment by ruihanma** [comment]
> 最近大半年以来空余时间太少了，后面我想慢慢用ts把这个项目重构一下，目前版本的问题太多了 ：(

辛苦了兄弟！加油
