### ISSUE TITLE
您好,请问可以在已经编辑的内容后插入HTML么?

### ISSUE THREAD

**Issue by TnWah** [margox/braft-editor#66]
用insertText只能插入字符串,setContent会整个替换掉内容,如何解决呢?

**Comment by margox** [comment]
暂时没有直接的方法，你可以试试下面的做法：
```javascript
const oldHTML = this.editorInstance.getHTMLContent()
const newHTML = `<p>Hello World!</p>`
this.editorInstance.setContent(oldHTML + newHTML, 'html')
```

**Comment by a-little-boy** [comment]
谢谢,这样可以啦

**Comment by TnWah** [comment]
插入的代码有些标签/样式会被过滤掉,例如原样式


![2018-02-27 09-49-56](https://user-images.githubusercontent.com/27721311/36706226-e7f81c46-1ba3-11e8-9f0e-660bde9facc2.png)
现有样式
![2018-02-27 09-50-57](https://user-images.githubusercontent.com/27721311/36706558-48b95b8e-1ba5-11e8-98e2-2f4fb68166e8.png)
![2018-02-27 09-58-36](https://user-images.githubusercontent.com/27721311/36706560-4dcb9574-1ba5-11e8-9c57-d84ad1affcbb.png)

**Comment by TnWah** [comment]
这些是编辑器本身过滤掉了么?

**Comment by margox** [comment]
是的，富文本编辑器并不是Dreamweaver或者PS，没有哪一款富文本编辑器能做到百分百的还原，基于draft-js的还原度只能更低，你上面的代码片段里面的section标签、float样式和background图片都是不被draft支持的，最后剩下的就只有那几个汉字了

**Comment by margox** [comment]
富文本编辑器本身不能承载太复杂的样式，对于太复杂的样式，最好的办法还是做成图片插入进来

**Comment by NewmanGo** [comment]
你好,用以下 
const oldHTML = this.editorInstance.getHTMLContent()
const newHTML = `<p>Hello World!</p>`
this.editorInstance.setContent(oldHTML + newHTML, 'html')
这种方式来更改内容只能在末尾或者开头加,我怎么才能在焦点处插入自定义的html呢
