### ISSUE TITLE
请问一下，这个编辑器是否能在基于R-N的app上使用呢？

### ISSUE THREAD

**Issue by liangwenzhu** [margox/braft-editor#67]
这个编辑器简直太棒了，但是app端如何使用基于draft的编辑器呢？

**Comment by margox** [comment]
感谢您的关注啊，因为用到了很多DOM和BOM特性，所以目前是没办法直接在RN项目里面用的，而且这个编辑器的交互和界面也没有针对移动端做过特别的适配和优化，所以就算在移动端网页上也不能保证正常使用。
