### ISSUE TITLE
gif图片被强制转换成了png

### ISSUE THREAD

**Issue by TimLiu1** [margox/braft-editor#681]
拷贝gif进入编辑器
查看生成的base64
是png格式
展示也是展示图片

**Comment by zibuyu69** [comment]
我也遇到了这个问题，不知道怎么才能用gif格式

**Comment by TimLiu1** [comment]
呼叫维护人，关注关注

**Comment by margox** [comment]
嗷嗷，要配置一下`media. uploadFn `，在里面执行真正的上传操作，不然默认会生成base64图片
