### ISSUE TITLE
能否增加设置行高的功能

### ISSUE THREAD

**Issue by cpu220** [margox/braft-editor#69]
不知道为什么，也就ueditor有行高的设定。所以能不能添加行高的修改功能

**Comment by margox** [comment]
我记一下。。。后面看一看能不能加上

**Comment by cpu220** [comment]
我自己试了下，写了个选择行高的插件。但是没找到 this.editorInstance 里有向当前行插入 line-height 的方法

**Comment by margox** [comment]
draft框架在这方面很鸡肋的，所有的样式都要自己去实现对应的entity，比如font-size和color这些，并不是直接选中内容的字号和颜色，而且操作entity的属性，还要自己写一系列转换器来将entity转换成实际的html
