### ISSUE TITLE
插入HTML内容异常

### ISSUE THREAD

**Issue by jiankian** [margox/braft-editor#691]
经过测试，插入内容，代码如下：
`ContentUtils.insertText(this.state.editorState, '<img src="http://www.anline.cn/skins/anline/img/logo.png"/>')`
没有正确插入，插入后只显示一个a字符，而且插入HTML内容会自己添加一些span了什么标签，请问如何才能使用原生插入功能。或者类似实现，或者正确插入就行了。
以下方式也不能用
`document.execCommand('insertHTML', false, '<img src="http://www.anline.cn/skins/anline/img/logo.png"/>')`

**Comment by margox** [comment]
insertHTML插入内容，在编辑器里面是会显示为一堆SPAN，但是你输出成最终的html 的时候，应该还是大致正常的
