### ISSUE TITLE
希望增加类似UEditor的一键排版功能

### ISSUE THREAD

**Issue by ixiejun** [margox/braft-editor#692]
对网站编辑来说，一键排版几乎是刚需，主要一键去除掉冗余的html标记，以及从word里复制的时候自带的一大堆style样式，类似UEditor的一键排版。

**Comment by LamTech** [comment]
顶一个

**Comment by margox** [comment]
想draft-js这种框架，就是block editor的思路来实现的，没办法实现传统编辑器那种真正所见即所得的功能:(
