### ISSUE TITLE
react and react-dom should be put into peer dependencies

### ISSUE THREAD

**Issue by ThisIsBarney** [margox/braft-editor#7]

**Comment by ThisIsBarney** [comment]
current version don't work with react 16.0.0 right now

**Comment by margox** [comment]
好的，我用react16试试

**Comment by margox** [comment]
发布了1.1.3版本，更新一下看看

**Comment by ThisIsBarney** [comment]
兄弟，我是说react和react-dom应该放进peerDependencies里哈，放在dependencies里会导致使用其他版本的react时报这个错：

> you have multiple copies of React loaded

现在15.X.X会有问题了。。。😂

**Comment by margox** [comment]
光关注兼容react16去了，第一条给忘了，我再去改改吧

**Comment by ThisIsBarney** [comment]
嗯哈😄

**Comment by margox** [comment]
1.1.4已发，react和react-dom已经添加到peerDependencies

**Comment by ThisIsBarney** [comment]
Well done！

**Comment by margox** [comment]
非常感谢支持，如果遇到其他问题，欢迎提issue🤓😘
