### ISSUE TITLE
感觉插入图片调整宽度的功能非常必要，或者提供个HTML编辑也成...

### ISSUE THREAD

**Issue by lamjack** [margox/braft-editor#70]
RT.

**Comment by margox** [comment]
感谢关注，图片尺寸调整的功能正在开发中了，近期就会发布喔

**Comment by lamjack** [comment]
👍

**Comment by margox** [comment]
@lamjack 已发布1.5.0版本，现在可以手动修改插入图片的宽高了

**Comment by margox** [comment]
![image](https://user-images.githubusercontent.com/7866354/36713485-eb3d8de4-1bc8-11e8-947f-8f4dff0d6efe.png)

**Comment by lamjack** [comment]
👍，如果能再有个html编辑模式就完美了！
