### ISSUE TITLE
有序列表右对齐问题，BraftEditor.createEditorState() 这个方法回填失去了右对齐

### ISSUE THREAD

**Issue by superXJg** [margox/braft-editor#710]
// 这段字符串是 有序列表然后右对齐之后 braft-editor 组件输出的字符串
const str = ‘<ol><li style="text-align:right;">232342</li></ol><p></p>’
BraftEditor.createEditorState(str)

回填之后右对齐失效

**Comment by s2265681** [comment]
居中对齐也失效
