### ISSUE TITLE
从服务器获取的html片段图片无法正常解析

### ISSUE THREAD

**Issue by Andesome** [margox/braft-editor#72]
服务器获取到的HTML片段为：`"<p></p><div class=\"media-wrap image-wrap\"><img src=\"//imgcdn.robo2025.com//product/1519693299261_53.png\"/></div><p></p><p></p><p></p>"`

编辑器解析图片会加上当前地址：`<img src="http://localhost:8000/%22//imgcdn.robo2025.com//product/1519693420831_27.png/%22/" width="auto" height="auto">`
导致图片显示失败，请问怎么解决

**Comment by margox** [comment]
我看看

**Comment by margox** [comment]
请问一下是在浏览器里面会有这个问题呢？ 我用chrome貌似是能正常显示的

**Comment by Andesome** [comment]
已解决，谢谢

**Comment by margox** [comment]
啊？ 怎么解决的呢？

**Comment by zhuchuanwu** [comment]
前端react-native无法显示 如果不手动设置的话

**Comment by qwIvan** [comment]
怎么解决的
