### ISSUE TITLE
与antD 浮层的兼容问题

### ISSUE THREAD

**Issue by cpu220** [margox/braft-editor#73]
1. 看了下git提交commit，发现你是兼容antD，然后试了下。发现如果我将braft-editor嵌入到antd-modal里的时候， 浮层没出来。
   * 原因在于 antD的 .ant-modal-wrap   z-index:1000 . 而 .braft-modal  z-index:999
2.  本来打算扩展下colorPicker，增加自行颜色拾取。结果dropDown只要有click，就直接收起。看了下源码，是registerClickEvent 这里来判断收起

**Comment by margox** [comment]
非常感谢关注
第一个问题，下一版本我改下z-index吧，如果你那边比较急，也可以自行先用CSS改掉 .braft-modal的z-index。
第二个问题，下一版本我加一个hideOnBlur属性，设置为false之后，就不会自动收起了。另外你是自己用dropDown组件来做Color Picker么？因为draft-js的限制，实际上颜色并不是无限可用的，现有的一些基于draft-js的编辑器貌似也都没有实现取色器的功能，不过我这边后面也会尝试实现以下，应该是有曲线救国的方案的。

**Comment by margox** [comment]
另外下一版本下午应该能发

**Comment by cpu220** [comment]
我是暂时简单的放量个input上去自己输入，然后发现只要click就会hide。

**Comment by margox** [comment]
很棒，期待你的pr

**Comment by margox** [comment]
刚才发布了1.5.0版本，增加了自定义DropDown的可配置性:
```javascript
{
  type: 'dropdown',
  width: 80,
  text: <span>下拉框</span>,
  html: '<span style="color:#0f0;">下拉框</span>', // 可以设置控制按钮的html内容
  autoHide: false, // 设置false，组件失去焦点后就不会自动关闭了
  ref: instance => this.customDropDown = instance, // 可以通过this.customDropDown.show()/.hide()来主动控制组件的显示或隐藏
  component: <YourComponent/>
}
```
另外editorInstance增加了一个未公开的实例方法**addTempColors**，用来主动增加可用的颜色:
```javascript
this.editorInstance.addTempColors(['#f00', '#00f'])
```
用户拾取颜色的功能已具备可行性，下一步我就会在颜色选择器中增加滴管功能。

**Comment by cpu220** [comment]
恩好的。lineHeight已完成。我晚上回家pr下
