### ISSUE TITLE
图片小需求建议, 以及bug

### ISSUE THREAD

**Issue by deot** [margox/braft-editor#74]
#### 需求：插入时新增一个`style`（移动端展示要求图片布满）
```
{
    type: 'IMAGE',
    name: 'New Photo',
    url: "xxxxxxxx",
    style: {
        width: "100%"
    }
}
```
#### bug
- 功能：以上插入图片方式`url`为`http:\\***`（`insertMedias`方法），编辑器与预览都显示图片
- 问题：再次编辑时候使用`raw`，图片不显示
- 分析原因：可能是插入图片时，`raw`没有发生改变，`html`改变了

**Comment by margox** [comment]
对于那个添加style的需求，下一版本会增加编辑图片宽高的功能。
那个bug中的再次编辑，是指保存保存之后再次从服务端获取raw data么？

**Comment by deot** [comment]
是的；
场景比较多，服务端同时保存 `html` 和 `raw`;

**Comment by margox** [comment]
你可以看看保存的raw或者从服务端获取到的raw，是不是包含了你新增的图片？

**Comment by deot** [comment]
不好意思，这是我的问题；某一处使用时将`onRawChange `方法写成了 `onRAWChange `

**Comment by margox** [comment]
哈哈

**Comment by margox** [comment]
@deot 对了，下午发了1.5.0版本，可以简单修改插入的图片的尺寸了

**Comment by zhuchuanwu** [comment]
这个不支持自动输入图片大小吗？必须要手动修改图片大小吗

**Comment by eugle** [comment]
设置图片宽高，没办法自适应，在移动端会变形，如何禁用这个控件？
