### ISSUE TITLE
ts的声明文件有问题 + getContent得到的内容问题

### ISSUE THREAD

**Issue by edward12699** [margox/braft-editor#76]
根据调用方式：this.editorInstance.getContent()
d.ts的声明文件是否应该是这样
declare class BraftEditor extends React.Component<BraftEditor.editorProps> { 
		getContent?: (format?: string) => RawDraftContentState;
}
我改成这样才能通过ts的验证
另外，从getContent中得到的是
![image](https://user-images.githubusercontent.com/14276262/36722162-d46be9b6-1be7-11e8-9f83-b9e6c785e8ae.png)
而预期中得到的应该是
![image](https://user-images.githubusercontent.com/14276262/36722192-e0f1c89a-1be7-11e8-8d84-31b7dc3ac732.png)

**Comment by edward12699** [comment]
我的调用方式是：
```js
 let body = this.editorInstance.getContent ? this.editorInstance.getContent() : 's';
        console.log(body);
```

**Comment by margox** [comment]
试试下面的写法：
```javascript
 this.editorInstance.getContent('html')
```
因为getContent方法接受一个参数来指定要返回的内容的格式，默认是raw，返回的是raw格式的数据，传入字符串`html`就会返回html格式的内容

**Comment by edward12699** [comment]
有效，谢谢

**Comment by petitspois** [comment]
@edward12699  声明文件报错？
