### ISSUE TITLE
如何限制用户可输入的字符为n个，当大于n个字符时不能往下继续输入

### ISSUE THREAD

**Issue by zengqiqing** [margox/braft-editor#774]
我发现maxLength并不能阻止富文本的字符输入。有没有好的方法可以限制住字符的输入。我在其他平台发起了提问，https://segmentfault.com/q/1010000022687758望作者如果近段时间有留意到我这个疑问可以解答一下。十分感谢

**Comment by YYL1999** [comment]
还有个方法就是监听了 自己手动拿到值后判断
