### ISSUE TITLE
能否支持直接粘贴图片？

### ISSUE THREAD

**Issue by jjtang616** [margox/braft-editor#79]
是否能够支持直接粘贴图片，便于编辑截图。

**Comment by margox** [comment]
这个功能正在开发中，敬请期待后续版本

**Comment by jjtang616** [comment]
能给个时间点吗？我这边有点急用。哈哈。

**Comment by margox** [comment]
现在工作这边的事情比较多哦，所以要再等几天，预计一周之内吧

**Comment by jjtang616** [comment]
好的，感谢。

**Comment by mushan0x0** [comment]
好像还是没有实现啊

**Comment by margox** [comment]
你这边用的什么版本？是什么浏览器呢？
http://margox.github.io/braft-editor/ 试试在这个在线Demo里面能不能行

**Comment by mushan0x0** [comment]
在线demo可以，用的浏览器是版本65，用的包是1.8.8

超能刚哥 <notifications@github.com> 于 2018年4月13日周五 上午11:38写道：
