### ISSUE TITLE
调用toHTML() 方法， 标签属性丢失

### ISSUE THREAD

**Issue by wenyAlab** [margox/braft-editor#795]
背景：项目需求中 添加超链接需要携带 name 属性 （主要用来做锚点），目前改了源码 实现了添加链接携带 name 属性， 如下图：

![image](https://user-images.githubusercontent.com/27913987/85354036-3b8d4280-b53c-11ea-9d90-688ddb50df06.png)

![image](https://user-images.githubusercontent.com/27913987/85354093-5bbd0180-b53c-11ea-801f-1a6e1c6fa8e5.png)

问题：
当我调用toHTML()， 将编辑器内容转为html后， name属性丢失， 但是使用toRAW()方法可以看到name属性是存在的， 如下图：

toHTML:
![image](https://user-images.githubusercontent.com/27913987/85354819-f407b600-b53d-11ea-9bd1-9ff19500221b.png)

toRAW:
![image](https://user-images.githubusercontent.com/27913987/85354396-0c2b0580-b53d-11ea-8be8-b7f9100c778d.png)

另：hooks中也可以获取到name属性
      const hooks = {
        'toggle-link': ({ href, target, name }) => {
          href = href.indexOf('http') === 0 ? href : `http://${href}`;
          return { href, target, name };
        },
      };

求助：我如何在调用toHTML()之后，保证name属性不会丢失？

**Comment by wenyAlab** [comment]
修改了 braft-convert 的源码， toHTML()方法可以带上name属性了

**Comment by chaoningx** [comment]
不是braft-convert这个源码，应该是braft-utils/dist/content.js这个文件里边的toggleSelectionLink方法吧。参数加上name就好。

**Comment by Prottoy2938** [comment]
Can you share the code,  my `editorState.toHtml()` doesn't return anything.

Issue raised [here](https://github.com/margox/braft-editor/issues/847).

**Comment by marlti7** [comment]
> 修改了 braft-convert 的源码， toHTML()方法可以带上name属性了

该怎么改
