### ISSUE TITLE
请教可否有其他语言实现的RAW格式解析?

### ISSUE THREAD

**Issue by 23233** [margox/braft-editor#797]
#### 但是因为RAW格式 比如说小程序端 RAW格式无法解析 会需要生成 html 或者是 markdown 这部分需要在后端直接进行 请问这种RAW格式解析 是否是braft通用?

**Comment by n3taway** [comment]
> #### 需求是因为 用户生成的 前端因为安全不能接受非RAW格式提交到后端存储!
> #### 但是因为RAW格式 比如说小程序端 RAW格式无法解析 会需要生成 html 或者是 markdown 这部分需要在后端直接进行 请问这种RAW格式解析 是否是braft通用?

老哥，问一下 RAW格式的数据是怎么提交到后端存储的，我这边需要存储raw格式的数据😂

**Comment by 1130204153** [comment]
> #### 需求是因为 用户生成的 前端因为安全不能接受非RAW格式提交到后端存储!
> #### 但是因为RAW格式 比如说小程序端 RAW格式无法解析 会需要生成 html 或者是 markdown 这部分需要在后端直接进行 请问这种RAW格式解析 是否是braft通用?

我也有这个问题，兄弟解决了嘛

**Comment by 23233** [comment]
> > #### 需求是因为 用户生成的 前端因为安全不能接受非RAW格式提交到后端存储!
> > #### 但是因为RAW格式 比如说小程序端 RAW格式无法解析 会需要生成 html 或者是 markdown 这部分需要在后端直接进行 请问这种RAW格式解析 是否是braft通用?
> 
> 我也有这个问题，兄弟解决了嘛

自己后端实现raw解析就行了 本质上就是个json
