### ISSUE TITLE
运行后样式不对， 没有边框

### ISSUE THREAD

**Issue by dengjiayao** [margox/braft-editor#81]

**Comment by margox** [comment]
编辑器没有外边框？ Demo里面的边框不是编辑器自带的，属于外围样式，你给容器加一个边框就行了。

**Comment by dengjiayao** [comment]
嗯， 可以了

**Comment by macc6579** [comment]
> 嗯， 可以了

朋友……你用的是antd吗。。。我设置了下发现没生效，想请教下您是怎么实现的www

**Comment by blackholll** [comment]
```
<div style={{ border:'1px solid'}}>
    <BraftEditor value={'hhh'}  />
</div>
```
@macc6579

**Comment by macc6579** [comment]
> ```
> <div style={{ border:'1px solid'}}>
>     <BraftEditor value={'hhh'}  />
> </div>
> ```
> 
> @macc6579

多谢啦~~
