### ISSUE TITLE
点击media，没有反应

### ISSUE THREAD

**Issue by brucezhangcode** [margox/braft-editor#831]
最新版本，点击media图标，不会弹出媒体选择弹窗，并且也没有报错

`js
const excludeControls = [
  "font-family",
  "letter-spacing",
  "strike-through",
  "superscript",
  "subscript",
  "remove-styles",
  "emoji",
  "code",
  "undo",
  "redo",
  "separator",
  "clear",
];

const media = {
  accepts: {
    image: "image/png,image/jpeg,image/gif,image/webp,image/apng,image/svg",
  },
};

export function Editor(props) {
  const { txt = null, onChange = () => {} } = props;
  const [editorValue, setEditorValue] = useState(
    BraftEditor.createEditorState(txt)
  );

  const onSave = () => {
    onChange(editorValue.toHTML());
  };

  const onInputChange = (value) => {
    setEditorValue(value);
    onChange(value.toHTML());
  };

  const upload = () => {
    // const {
    //   file = [],
    //   progress = (progress) => {},
    //   libraryId = '',
    //   success = (res) => {},
    //   error = (err) => {},
    // } = params;
    // console.log("upload ----", params);
    // TODO:图片上传处理
  };

  return (
    <div
      style={{
        background: "#fafafa",
        width: "80%",
        border: "1px solid #e8e8e8",
      }}
    >
      <BraftEditor
        media={{ accepts: media.accepts, uploadFn: upload }}
        value={editorValue}
        onChange={onInputChange}
        onSave={onSave}
        excludeControls={excludeControls}
      />
    </div>
  );
}
`

**Comment by Firenzia** [comment]
大佬怎么解决的 @beiyu98
