### ISSUE TITLE
间隔插入代码和文字的问题

### ISSUE THREAD

**Issue by SadCreeper** [margox/braft-editor#84]
比如先插入一段文字，再插入一段代码，再插入文字，再插入代码：
![image](https://user-images.githubusercontent.com/19741140/36932929-e2e2641c-1f0b-11e8-807c-3bb57cdc25b5.png)
显示无误，保存后在预览界面也能正确显示：
![image](https://user-images.githubusercontent.com/19741140/36932933-f8e34c18-1f0b-11e8-8997-04a286b6b851.png)
但是在重新编辑时出现了问题，貌似第一个代码块后边的东西全进了代码块：
![image](https://user-images.githubusercontent.com/19741140/36932946-262a608a-1f0c-11e8-8658-f7677f60d542.png)
这时如果再保存，预览界面仍然是正确显示，数据好像没受到影响

**Comment by margox** [comment]
我洗完澡来看看

**Comment by margox** [comment]
已经发布1.6.1,该问题已修复

**Comment by SadCreeper** [comment]
OK，刚哥神速
