### ISSUE TITLE
这个生成的html支持移动端吗

### ISSUE THREAD

**Issue by baohuse** [margox/braft-editor#87]

**Comment by margox** [comment]
这个生成的是HTML + 内联CSS，对于不同的移动端适配方案（例如响应式布局或者flexible方案等），显示效果可能会有差别。

**Comment by cpu220** [comment]
我的方法是，对产出的结果进行px转rem处理 
用这个 /:([1-9]\d*|0)(\.\d*)?px/g， 筛选出所有px单位，然后进行单位替换，数据比例计算。

**Comment by margox** [comment]
@cpu220 膜拜真正の大神
