### ISSUE TITLE
图片操作图标不能正常加载，显示为小方块

### ISSUE THREAD

**Issue by yg1203108068** [margox/braft-editor#886]
如图所示这种情况，请问应该怎么处理?谢谢 👍 
![image](https://user-images.githubusercontent.com/21117981/110439315-469bf900-80f2-11eb-9f0d-a9bdfb2e0ae2.png)

**Comment by gland2015** [comment]
同志们来试试我这个编辑器，开箱即用，功能强大[https://github.com/gland2015/gland](https://github.com/gland2015/gland)，急需star

**Comment by yg1203108068** [comment]
``已解决
`import {DeleteOutlined, PicLeftOutlined, PicRightOutlined, AlignLeftOutlined, AlignCenterOutlined, AlignRightOutlined, LinkOutlined, ArrowsAltOutlined} from "@ant-design/icons";`

`const customControls = [{
    key: 'float-left',
    text: <PicLeftOutlined/>,
    onClick: 'setImageFloat|left'
} ,{
    key: 'float-right',
    text: <PicRightOutlined/>,
    onClick: 'setImageFloat|right'
} ,{
    key: 'align-left',
    text: <AlignLeftOutlined/>,
    onClick: 'setImageAlignment|left'
} ,{
    key: 'align-center',
    text: <AlignCenterOutlined/>,
    onClick: 'setImageAlignment|center'
} ,{
    key: 'align-right',
    text: <AlignRightOutlined/>,
    onClick: 'setImageAlignment|right'
} ,{
    key: 'link',
    text: <LinkOutlined/>,
    onClick: 'toggleLinkEditor'
},{
    key: 'size',
    text: <ArrowsAltOutlined/>,
    onClick: 'toggleSizeEditor'
},{
    key: 'remove',
    text: <DeleteOutlined/>,
    onClick: 'removeImage'
}];`

`<BraftEditor onSave={this.saveToLocal} media={{uploadFn: myUploadFn}}
                                         imageControls={customControls}/>`

**Comment by qq853580228** [comment]
应该是font-family被覆盖了
.bf-media-toolbar > a > span {
      font-family: 'braft-icons' !important;
    }
