### ISSUE TITLE
如果有 initialContent 配置 contentFormat 必须为Html

### ISSUE THREAD

**Issue by PuShaoWei** [margox/braft-editor#91]
如果有 initialContent 配置 contentFormat 必须为Html 否则

invalid RawDraftContentState

**Comment by margox** [comment]
因为编辑器默认就是使用的RawDraftContentState，不建议使用html，因为这样不能保证可重复编辑性，虽然现在为止也没用反馈出现过什么太大的问题。
所以在默认情况下，initialContent需要传RawDraftContentState格式的数据，如果你需要传入的是字符串，那就需要把contentFormat配置为html。

**Comment by margox** [comment]
我下一版本考虑一下要不要把contentFormat的默认值改成html
