### ISSUE TITLE
微信里使用上传不了文件？

### ISSUE THREAD

**Issue by jamieYou** [margox/braft-editor#92]
在微信里，富文本的那个上传图片的功能无效。选择图片后没反应。也没报错。不知到怎么回事orz。
我尝试直接使用 input 组件， 使用 input 的file 属性，onchange是能触发的，但是这个富文本就不知道为什么没有反应。

**Comment by margox** [comment]
ios 微信没问题，你是什么机型？ 有没有使用validateFn呢？
