### ISSUE TITLE
2.3.9版本目前不支持React17 么

### ISSUE THREAD

**Issue by Emmeet** [margox/braft-editor#923]
warning "braft-editor > braft-convert@2.3.0" has incorrect peer dependency "react@^16.0.0".
warning "braft-editor > braft-finder@0.0.19" has incorrect peer dependency "react@^16.4.1".
warning "braft-editor > braft-finder@0.0.19" has incorrect peer dependency "react-dom@^16.4.1".
warning "braft-editor > draft-js@0.10.5" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-rc || ^16.0.0-rc || ^16.0.0".
warning "braft-editor > draft-js@0.10.5" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0-rc || ^16.0.0-rc || ^16.0.0".
warning " > braft-editor@2.3.9" has incorrect peer dependency "react@^15.0.2|| ^16.0.0-rc || ^16.0.0".
warning " > braft-editor@2.3.9" has incorrect peer dependency "react-dom@^15.0.2|| ^16.0.0-rc || ^16.0.0".

页面会直接报错

**Comment by youdianfan** [comment]
重新install一下

**Comment by bertyhell** [comment]
For anyone else hitting this issue, you can install the modules using this command:
```
npm install --legacy-peer-deps
```

**Comment by Emmeet** [comment]
> For anyone else hitting this issue, you can install the modules using this command:
> 
> ```
> npm install --legacy-peer-deps
> ```

Thank You for the Reply
