### ISSUE TITLE
与Ant.Design不兼容

### ISSUE THREAD

**Issue by zenglixin** [margox/braft-editor#94]
你好，我觉得你造的这个轮子挺好的 。但是我把他嵌入在Ant.Design官方提供的Layout页面时会报错Cannot read property 'blocks' of null，请问是我使用问题还是本身兼容性没有解决呢
![image](https://user-images.githubusercontent.com/24795323/37251748-e7bef66c-2550-11e8-81a3-b1c6d4682bff.png)

**Comment by margox** [comment]
contentFormat设置为'html'试试
