### ISSUE TITLE
光标有问题

### ISSUE THREAD

**Issue by stefaniepei** [margox/braft-editor#96]
当initialContent有state控制并赋值的时候，光标会自动移到第一位

![image](https://user-images.githubusercontent.com/1124923/37274336-3d8637a6-2617-11e8-9222-2ce32ca19f10.png)

**Comment by stefaniepei** [comment]
![image](https://user-images.githubusercontent.com/1124923/37274767-64bd12ee-2618-11e8-9792-a4db9751259b.png)

**Comment by margox** [comment]
initialContent 是用于设置初始值的属性，每次更改此属性，编辑器内容都会重新渲染，所以不要多次也没必要改变此属性，如果需要动态同步编辑器的内容，建议另外在state里面加一个字段来存储，不要和initialContent共用，也可以在只在必要的时候通过editorInstance.getContent()来获取编辑器内容

**Comment by stefaniepei** [comment]
非常感谢

**Comment by margox** [comment]
感谢支持，可以加群QQ 725634541交流😯
