### ISSUE TITLE
上传本地图片，如何控制输出格式？

### ISSUE THREAD

**Issue by x8845723** [margox/braft-editor#98]
上传本地图片，有些是输出base64格式的HTML字符串，有些又是二进制。。。。又控制图片输出格式的方法吗？

**Comment by margox** [comment]
是指没有指定uploadFn的情况么？ 这种情况插入编辑器的只是一个blob对象，相当于浏览器的一个缓存，只在浏览器当前生命周期才有效的，无法持久化。如果转成base64，那生成的内容又会巨大，这也不现实。如果需要使用图片上传功能，请指定可用的uploadFn

**Comment by x8845723** [comment]
如何进行指定图片输出格式并输出到HTML字符串中？求指点

**Comment by margox** [comment]
加QQ群 725634541 来交流吧

**Comment by x8845723** [comment]
好的，么么哒
