### ISSUE TITLE
标题1+居中 存储后再次打开变为非居中状态

### ISSUE THREAD

**Issue by BiteBit** [margox/braft-editor#99]
hello，对一段文字同时使用标题1和居中，保存到数据库后再次打开，原先居中的文字不再居中。
请求支援，谢谢。

**Comment by margox** [comment]
Bug已确认，感谢反馈，我会尽快修复并发布新版本。

**Comment by margox** [comment]
@BiteBit 已发布1.7.5，更新试试

**Comment by BiteBit** [comment]
神速！
测试已ok，谢谢支持。
